# De libertarische erfenis: De Amerikaanse Revolutie en klassiek liberalisme

Op de dag van de verkiezingen in 1976 ontving het kandidaatschap van de Libertarische Partij, met Roger L. MacBride als president en David P. Bergland als vice-president, 174.000 stemmen in tweeëndertig staten door het hele land. Het nuchtere Congressional Quarterly classificeerde de jonge Libertarische Partij als de derde grote politieke partij in Amerika. De opmerkelijke groei van deze nieuwe partij is zichtbaar, aangezien ze pas in 1971 van start ging met een handjevol leden die bijeenkwamen in een huiskamer in Colorado. Het jaar daarop organiseerden ze een presidentieel kandidaatschap, dat in twee staten op het stembiljet verscheen. En nu is de Libertarische Partij de derde grote partij van Amerika.

Nog opmerkelijker is dat de Libertarische Partij deze groei wist te bereiken terwijl ze trouw bleef aan een nieuw ideologisch credo: 'libertarisme'. Hiermee bracht ze voor het eerst in een eeuw een partij op het Amerikaanse politieke toneel die zich richtte op principes, in plaats van enkel op het vergaren van banen en geld uit de publieke kas. Deskundigen en politicologen hebben ons vaak verteld dat het unieke van Amerika en haar partijstelsel te vinden is in het gebrek aan ideologie en in het 'pragmatisme' (een eufemisme voor het uitsluitend mikken op het veroveren van belastinggeld en banen van de belastingbetalers). Hoe kunnen we dan de verbazingwekkende groei verklaren van een nieuwe partij die zich openlijk en enthousiast inzet voor een ideologie?

Eén verklaring is dat Amerikanen niet altijd pragmatisch en niet-ideologisch waren. Historici realiseren zich inmiddels dat de Amerikaanse Revolutie niet alleen ideologisch was, maar ook voortkwam uit een sterke toewijding aan het credo en de principes van het libertarisme. De Amerikaanse revolutionairen waren doordrongen van het libertarisme, een ideologie die hen ertoe aanzette zich met hun leven, hun bezit en hun eer te verzetten tegen de schendingen van hun rechten en vrijheden door de Britse imperiale regering. Historici hebben lang gediscussieerd over de exacte oorzaken van de Amerikaanse Revolutie: waren deze constitutioneel, economisch, politiek of ideologisch? Tegenwoordig begrijpen we dat de revolutionairen, als libertariërs, geen tegenstelling zagen tussen morele en politieke rechten aan de ene kant en economische vrijheid aan de andere kant. Sterker nog, zij beschouwden burgerlijke en morele vrijheid, politieke onafhankelijkheid en de vrijheid om te handelen en te produceren als onderdelen van één onmiskenbaar systeem. Adam Smith zou dit systeem in hetzelfde jaar dat de Onafhankelijkheidsverklaring werd geschreven, omschrijven als het 'voor de hand liggende en eenvoudige systeem van natuurlijke vrijheid.'

Het Libertarische credo is ontstaan uit de 'klassiek liberale' bewegingen van de zeventiende en achttiende eeuw in de Westerse wereld, met name vanuit de Engelse Revolutie van de zeventiende eeuw. Deze radicale libertarische beweging was, ondanks dat ze slechts gedeeltelijk succesvol was in haar geboorteplaats Groot-Brittannië, in staat om de Industriële Revolutie in gang te zetten. Hierdoor werd de industrie bevrijd van de verstikkende beperkingen van staatscontrole en gilden die door de overheid gesteund werden. De klassieke liberale beweging vertegenwoordigde een krachtige libertarische 'revolutie' tegen wat we de Oude Orde kunnen noemen: het ancien régime dat zijn onderdanen eeuwenlang had gedomineerd. Vanaf de zestiende eeuw had dit regime, bovenop een ouderwets netwerk van feodale landmonopolies en stedelijke gildebeperkingen, een absolute centrale staat en een koning met goddelijk recht opgelegd. Het resultaat was een Europa dat gevangen zat in een verlammend web van controles, belastingen en monopolistische privileges, die door centrale en lokale overheden aan hun favoriete producenten werden verleend. De combinatie van de nieuwe bureaucratische, oorlogszuchtige centrale staat met bevoorrechte kooplieden - een verbinding die door latere historici 'mercantilisme' zou worden genoemd - en een klasse van heersende feodale landheren, vormde de Oude Orde waartegen de nieuwe beweging van klassieke liberalen en radicalen in de zeventiende en achttiende eeuw opkwam en in opstand kwam.

Het doel van de klassieke liberalen was om individuele vrijheid in al haar facetten te bevorderen. In de economie moesten belastingen flink omlaag, moesten controles en regels verdwijnen, en moest menselijke energie, ondernemingszin en marktwerking de ruimte krijgen om te creëren en te produceren. Dit zou zowel iedereen als de massa van consumenten ten goede komen. Ondernemers moesten de vrijheid hebben om te concurreren, zich te ontwikkelen en innovaties te creëren. De ketenen van controle rondom grond, arbeid en kapitaal moesten worden verbroken. Persoonlijke en burgerlijke vrijheid moesten beschermd worden tegen de plunderingen en tirannie van de koning of zijn aanhangers. Religie, dat eeuwenlang de oorsprong was van bloedige oorlogen tussen verschillende sekten die om de controle over de staat streden, moest bevrijd worden van staatsinmenging. Hierdoor konden alle religies - of geen religie - vreedzaam naast elkaar bestaan. Ook vrede moest de leidraad vormen voor het buitenlands beleid van de nieuwe klassiek-liberalen. Het eeuwenoude regime van imperiale expansie en machtsoverheersing moest plaatsmaken voor een beleid van vrede en vrije handel met alle naties. Aangezien oorlog vaak werd toegeschreven aan permanente legers en marines, en aan militaire macht die altijd op zoek was naar uitbreiding, moesten deze militaire instellingen worden vervangen door vrijwillige lokale milities. Dit zouden burgers zijn die enkel bereid waren om hun eigen huizen en buurten te verdedigen.

Het bekende thema 'scheiding van kerk en staat' was slechts één van de vele met elkaar verbonden motieven. Deze motieven kunnen worden samengevat als 'scheiding van de economie van de staat', 'scheiding van meningsuiting en pers van de staat', 'scheiding van land van de staat' en 'scheiding van oorlog en militaire zaken van de staat'. Eigenlijk gaat het om de scheiding van de staat van vrijwel alles.

De staat moest kortom uiterst klein blijven, met een budget dat zo laag mogelijk was. De klassiek-liberalen hebben nooit een duidelijke theorie over belastingen ontwikkeld, maar zij bestreden elke belastingverhoging en elk nieuw soort belasting met grote tegenstand. In Amerika leidde dit zelfs twee keer tot spanningen die bijna tot de Revolutie resulteerden: de belasting op zegels en de belasting op thee.

De eerste denkers van het libertarische klassieke liberalisme waren de Levelers tijdens de Engelse Revolutie en de filosoof John Locke aan het eind van de zeventiende eeuw. Zij werden gevolgd door de 'True Whig', de radicale libertarische oppositie tegen de 'Whig Settlement', het regime van achttiende-eeuws Groot-Brittannië. John Locke beschreef de natuurlijke rechten van elk individu met betrekking tot zijn persoon en eigendom. De rol van de overheid was strikt beperkt tot het beschermen van deze rechten. In de woorden van de door Locke geïnspireerde Onafhankelijkheidsverklaring: 'Om deze rechten veilig te stellen, zijn er onder de mensen regeringen ingesteld, die hun rechtvaardige macht ontlenen aan de instemming van de geregeerden. Wanneer een regeringsvorm destructief wordt voor deze doeleinden, heeft het volk het recht om deze te veranderen of af te schaffen.'

Hoewel Locke in de Amerikaanse koloniën veel werd gelezen, was zijn abstracte filosofie niet echt gericht op het aanzetten tot revolte. Die taak werd opgepakt door radicale Lockeanen in de achttiende eeuw. Zij schreven op een meer toegankelijke, directe en gepassioneerde manier en passten de basisfilosofie toe op de concrete problemen van de ontdekke regering, en vooral de Britse. Het belangrijkste artikel in deze lijn was 'Cato's Brieven', een serie krantenartikelen die begin 1720 in Londen werden gepubliceerd door de 'True Whigs', John Trenchard en Thomas Gordon. Terwijl Locke had geschreven over de revolutionaire druk die kan ontstaan wanneer de overheid de vrijheid ondermijnt, wijzen Trenchard en Gordon erop dat de overheid altijd de neiging heeft om individuele rechten te schenden. Volgens de 'Brieven van Cato' is de geschiedenis van de mensheid een verslag van een onvermijdelijk conflict tussen Macht en Vrijheid. De Macht (de regering) staat altijd klaar om haar invloed uit te breiden ten koste van de rechten van mensen en hun vrijheden. Daarom, zo betoogt Cato, moet de macht klein worden gehouden en geconfronteerd met voortdurende waakzaamheid en tegenstand van het publiek, om ervoor te zorgen dat deze altijd binnen zijn nauwe grenzen blijft.

> Wij weten uit talloze voorbeelden en ervaringen dat mensen met macht er alles aan doen om deze te behouden, zelfs als dat de meest afschuwelijke middelen vereist. Bijna niemand op aarde heeft ooit afstand gedaan van zijn macht, zolang hij er maar op zijn eigen manier gebruik van kon maken. Het lijkt dan ook zeker dat het welzijn van de wereld of van hun volk niet een van hun motieven is om aan de macht te blijven of om deze op te geven.
>
> Het is de aard van macht om zich voortdurend op te dringen. Elke buitengewone bevoegdheid, verleend op specifieke momenten en bij bijzondere gelegenheden, wordt omgevormd tot een algemene bevoegdheid die altijd gebruikt kan worden, zelfs als er geen uitzonderlijke situatie is. Macht doet nooit vrijwillig afstand van enig voordeel.
>
> Helaas! Macht overschrijdt dagelijks de grenzen van Vrijheid, en doet dat met verontrustend succes. Het evenwicht tussen beiden lijkt bijna verloren. Tirannie heeft bijna de hele aarde in zijn greep en bedreigt de mensheid, wortel en tak. Het maakt de wereld tot een slachthuis en zal zeker doorgaan met vernietigen, totdat het ofwel zelf wordt vernietigd, of, wat het waarschijnlijker maakt, niets anders meer heeft om te vernietigen.1

Dergelijke waarschuwingen werden met veel enthousiasme overgenomen door de Amerikaanse kolonisten. Zij herdrukten 'Cato's Brieven' vele malen in de koloniën, tot aan de tijd van de Revolutie. Deze diepgewortelde houding leidde tot wat de historicus Bernard Bailyn treffend het 'transformerende radicale libertarisme' van de Amerikaanse Revolutie noemde.

De revolutie was niet alleen de eerste succesvolle moderne poging om het juk van het westerse imperialisme van zich af te werpen - op dat moment de machtigste grootmacht ter wereld. Belangrijker was dat de Amerikanen voor het eerst in de geschiedenis hun nieuwe regeringen beperkten met talloze limieten en restricties, vastgelegd in grondwetten en vooral in zogenaamde 'bills of rights' (een verklaring van burgerrechten). Kerk en staat werden in de nieuwe staten strikt van elkaar gescheiden en godsdienstvrijheid werd gewaarborgd. De overblijfselen van het feodalisme werden in alle staten uitgeroeid door de afschaffing van de feodale privileges van erfopvolging en eerstgeboorterecht. (In het eerste geval kan een overleden voorouder land voor altijd aan zijn familie toevertrouwen, waardoor zijn erfgenamen geen deel van het land kunnen verkopen. In het tweede geval bepaalt de wet dat alleen de oudste zoon het eigendom erft.)

De nieuwe federale regering, gevormd op basis van de Artikelen van de Confederatie, had geen recht om belastingen te heffen op het volk. Voor elke fundamentele uitbreiding van haar bevoegdheden was unanieme toestemming van alle deelstaatregeringen vereist. Bovenal was de militaire en oorlogszuchtige macht van de nationale regering beperkt, voortkomend uit terughoudendheid en wantrouwen. De libertariërs van de achttiende eeuw begrepen namelijk dat oorlog, permanente legers en militarisme lange tijd de belangrijkste manieren waren om de staatsmacht uit te breiden.2

Bernard Bailyn heeft de prestaties van de Amerikaanse revolutionairen als volgt samengevat:

> De modernisering van de Amerikaanse politiek en regering tijdens en na de Revolutie vormde een plotselinge, radicale realisatie van het programma dat voor het eerst volledig was uiteengezet door de oppositie-intelligentsia tijdens het bewind van George de Eerste. Terwijl de Engelse oppositie, die zich een weg baande tegen een zelfgenoegzame sociale en politieke orde, alleen had gestreefd en gedroomd, konden de Amerikanen nu handelen. Gedreven door dezelfde aspiraties, maar deel uitmakend van een maatschappij die in veel opzichten modern was en nu politiek bevrijd, grepen zij hun kans. Waar de Engelse oppositie tevergeefs had gepleit voor gedeeltelijke hervormingen, gingen Amerikaanse leiders snel en met weinig sociale ontwrichting over tot de systematische uitvoering van radicale bevrijdingsideeën.
>
> In dit proces hebben ze de belangrijkste thema's van het achttiende-eeuwse radicale libertarisme, die hier werkelijkheid zijn geworden, verankerd in de Amerikaanse politieke cultuur. Het eerste thema is de overtuiging dat macht een kwaad is; misschien een noodzakelijkheid, maar wel een kwalijke. Macht corrumpeert eindeloos en moet op elke mogelijke manier gecontroleerd, beperkt en begrensd worden, zolang dit verenigbaar is met een minimum aan burgerlijke orde. Geschreven grondwetten, de scheiding der machten, verklaringen van burgerrechten, en beperkingen voor de uitvoerende macht, de wetgevende macht en de rechtbanken: dit alles drukt het diepe wantrouwen uit tegen macht dat in het ideologische hart van de Amerikaanse Revolutie ligt. Deze erfenis heeft ons sindsdien blijvend beïnvloed.3

Hoewel het klassieke liberale denken in Engeland begon, bereikte het zijn meest consistente en radicale ontwikkeling -- en zijn grootste belichaming -- in Amerika. Dit kwam doordat de Amerikaanse koloniën vrij waren van het feodale landmonopolie en de aristocratische elite die in Europa zo diep geworteld was. In Amerika waren de heersers Britse koloniale ambtenaren en een handvol bevoorrechte kooplieden, die relatief gemakkelijk aan de kant konden worden geschoven toen de Revolutie uitbrak en de Britse regering werd omvergeworpen. Hierdoor vond het klassieke liberalisme meer steun onder de bevolking en ondervond het veel minder opstandige institutionele weerstand in de Amerikaanse koloniën dan in Europa. Daarnaast hoefden de Amerikaanse opstandelingen, vanwege hun geografische isolatie, zich geen zorgen te maken over aanvallen van nabijgelegen, contrarevolutionaire regeringen, zoals dat bijvoorbeeld wel het geval was in Frankrijk.

## NA DE REVOLUTIE

De modernisering van de Amerikaanse politiek en regering tijdens en na de Revolutie leidde tot een plotselinge en radicale uitvoering van het programma dat voor het eerst volledig was uiteengezet door de oppositie-intelligentsia tijdens het bewind van George de Eerste. Waar de Engelse oppositie, die zich een weg baande tegen een zelfgenoegzame sociale en politieke orde, alleen maar had gedroomd en gestreefd, konden de Amerikanen nu daadwerkelijk handelen. Gedreven door dezelfde aspiraties, maar deel uitmakend van een maatschappij die op veel vlakken modern was en politiek bevrijd, grepen zij hun kans. In tegenstelling tot de Engelse oppositie, die tevergeefs had gepleit voor gedeeltelijke hervormingen, gingen Amerikaanse leiders snel en met weinig sociale ontwrichting over tot de systematische uitvoering van radicale bevrijdingsideeën. In dit proces hebben zij de belangrijkste thema's van het achttiende-eeuwse radicale libertarisme, die hier werkelijkheid zijn geworden, verankerd in de Amerikaanse politieke cultuur. Het eerste thema is het geloof dat macht een kwaad is; misschien een noodzakelijkheid, maar wel een kwalijke. Macht corrumpeert eindeloos en moet op elke mogelijke manier gecontroleerd, beperkt en begrensd worden, zolang dit mogelijk is bij een minimum aan burgerlijke orde. Geschreven grondwetten, de scheiding der machten, verklaringen van burgerrechten, en beperkingen voor de uitvoerende macht, de wetgevende macht en de rechtbanken drukken het diepe wantrouwen tegen macht uit dat in het ideologische hart van de Amerikaanse Revolutie ligt. Deze erfenis heeft ons sindsdien blijvend beïnvloed. Hoewel het klassieke liberale denken in Engeland begon, bereikte het zijn meest consistente en radicale ontwikkeling -- en zijn grootste belichaming -- in Amerika. De Amerikaanse koloniën waren vrij van het feodale landmonopolie en de aristocratische elite die in Europa zo diep geworteld was. In Amerika waren de heersers Britse koloniale ambtenaren en een handvol bevoorrechte kooplieden, die relatief gemakkelijk aan de kant konden worden geschoven toen de Revolutie uitbrak en de Britse regering werd omvergeworpen. Hierdoor vond het klassieke liberalisme meer steun onder de bevolking en ondervond het veel minder institutionele weerstand in de Amerikaanse koloniën dan zijn Europese tegenhanger. Bovendien hoefden de Amerikaanse opstandelingen, vanwege hun geografische isolatie, zich geen zorgen te maken over aanvallen van nabijgelegen, contrarevolutionaire regeringen, zoals dat bijvoorbeeld wel het geval was in Frankrijk.

Zo werd Amerika, meer dan enig ander land, geboren uit een expliciete libertarische revolutie. Het was een revolutie tegen het imperium, tegen belastingen, handelsmonopolies en regulering, en tegen militarisme en uitvoerende macht. Deze revolutie leidde tot regeringen met ongekende beperkingen op hun macht.

Hoewel er in Amerika weinig institutioneel verzet was tegen de opmars van het liberalisme, waren er vanaf het begin machtige elitekrachten actief. Vooral grote kooplieden en planters wilden het Britse 'mercantilistische' systeem met zijn hoge belastingen, controles en overheidsmonopolieprivileges behouden. Deze groepen verzochten om een sterke centrale regering; ze wilden eigenlijk het Britse systeem zonder Groot-Brittannië. Deze conservatieve en reactionaire krachten dienden zich voor het eerst aan tijdens de Revolutie en vormden later in de jaren 1790 de Federalistische partij en de Federalistische regering.

In de negentiende eeuw zette de libertarische impuls zich voort. De Jeffersoniaanse en Jacksoniaanse bewegingen, evenals de Democratisch-Republikeinse en later de Democratische partijen, streefden naar een bijna volledige afschaffing van de overheid in het Amerikaanse leven. Het ideale doel was een regering zonder een staand leger of marine; een regering zonder schulden en zonder directe federale of accijnsbelastingen, met vrijwel geen importtarieven. Dit resulteerde in een verwaarloosbaar niveau van belastingen en uitgaven. De overheid moest zich niet bemoeien met openbare werken of interne verbeteringen. Er was geen controle of regulering, en geld en bankieren moesten vrij, betrouwbaar en ongeïnflateerd blijven. Kortom, in de woorden van H.L. Mencken: 'een regering die er ternauwernood aan ontkomt helemaal geen regering te zijn.'

Het Jeffersoniaanse streven naar bijna geen regering kwam tot stilstand nadat Jefferson aan de macht was gekomen. Eerst maakte hij concessies aan de Federalisten, mogelijk het resultaat van een deal om Federalistische stemmen te krijgen en zo een gelijkspel in het kiescollege te doorbreken. Daarna volgde de ongrondwettelijke aankoop van het Louisiana Territory. Maar vooral de imperialistische drang naar oorlog met Groot-Brittannië in Jeffersons tweede ambtstermijn zorgde voor deze mislukking. Deze neiging leidde tot oorlog en tot een eenpartijstelsel dat vrijwel het volledige federalistische programma invoerde: hoge militaire uitgaven, een centrale bank, een beschermend invoerheffingstarief, directe federale belastingen en openbare werken. Een gepensioneerde Jefferson bleef in Monticello gruwen van de resultaten en inspireerde jonge politici als Martin Van Buren en Thomas Hart Benton om een nieuwe partij op te richten: de Democratische partij. Zij wilden Amerika terugwinnen van het nieuwe Federalisme en de geest van het oude Jeffersoniaanse programma heroveren. Toen de twee jonge leiders zich blindelings aan Andrew Jackson vasthielden als hun redder, was de nieuwe Democratische partij geboren.

De Jacksoniaanse libertariërs hadden een plan: acht jaar Andrew Jackson als president, gevolgd door acht jaar Van Buren en daarna nog acht jaar Benton. Na vierentwintig jaar van bloeiende Jacksoniaanse Democratie zou het Menckeniaanse ideaal van vrijwel geen overheid werkelijkheid zijn geworden. Het leek geen onmogelijke droom, want de Democratische partij was snel de belangrijkste meerderheidspartij van het land geworden. De massa achter het volk was gewonnen voor de libertarische zaak. Jackson had zijn acht jaar in functie achter de rug, waarin de centrale bank werd afgeschchaft en de staatsschuld werd kwijtgescholden. Van Buren had ook vier jaar gediend, waarin de federale overheid onafhankelijk werd van het banksysteem. Maar de verkiezingen van 1840 vormden een uitzondering. Van Buren werd verslagen door een ongekend demagogische campagne, geleid door de eerste grote moderne campagnevoorzitter, Thurlow Weed. Hij was een pionier in alle campagne-uitingen, zoals pakkende slogans, buttons, liedjes en parades, die we nu kennen. De tactieken van Weed zorgden ervoor dat de onbekende Whig, generaal William Henry Harrison, aan de macht kwam. Dit was echter duidelijk een toevallige overwinning. In 1844 waren de Democraten vastbesloten om met dezelfde campagnetactieken terug te vechten en ze waren van plan om dat jaar het presidentschap terug te winnen. Van Buren zou natuurlijk de triomfantelijke koers van de Jacksoniaanse beweging hervatten. Maar toen deed zich een noodlottige gebeurtenis voor: de Democratische partij werd verdeeld over de cruciale kwestie van de slavernij, of beter gezegd over de uitbreiding van de slavernij naar nieuwe gebieden. De makkelijke herverkiezing van Van Buren kwam ten einde door een breuk binnen de partij over de toelating van Texas als slavenstaat. Van Buren was tegen, Jackson was voor, en deze verdeeldheid symboliseerde de bredere scheuren binnen de Democratische partij. Slavernij, de ernstige antiliberale fout binnen het libertarisme van het Democratische programma, stond op om de partij en haar libertarisme volledig te ondermijnen.

De Burgeroorlog ging gepaard met ongekend bloedvergieten en vernietigingen. Het triomferende, bijna eenpartijstelsel van het Republikeinse regime gebruikte deze situatie om zijn statistische, voorheen Whig-programma door te voeren. Dit omvatte nationale regeringsmacht, beschermende invoerrechten, subsidies voor grote bedrijven, inflatoir papiergeld, een hernieuwde controle van de federale overheid over het bankwezen, grootschalige interne verbeteringen, hoge accijnzen en, tijdens de oorlog, dienstplicht en inkomstenbelasting. Bovendien verloren de staten hun eerdere recht op secessie en andere bevoegdheden ten opzichte van de federale overheid. Na de oorlog hervatte de Democratische partij haar libertarische koers. Maar nu stond er een veel langere en moeilijkere weg naar vrijheid voor hen open dan voorheen.

We hebben gezien hoe Amerika de diepste libertarische traditie heeft ontwikkeld. Deze traditie is nog altijd terug te vinden in veel van onze politieke retoriek en wordt weerspiegeld in de pittige, individualistische houding van een groot deel van het Amerikaanse volk ten opzichte van de overheid. In dit land is er veel meer vruchtbare grond voor een heropleving van het libertarisme dan ergens anders.

## WEERSTAND TEGEN VRIJHEID

De Jacksoniaanse libertariërs hadden een duidelijk plan: acht jaar Andrew Jackson als president, gevolgd door acht jaar Van Buren en vervolgens nog eens acht jaar Benton. Na vierentwintig jaar van bloeiende Jacksoniaanse Democratie zou het Menckeniaanse ideaal van bijna geen overheid werkelijkheid zijn geworden. Het was geen onmogelijke droom; de Democratische partij was snel de grootste meerderheidspartij in het land geworden. De massa achter het volk steunde de libertarische zaak. Jackson had zijn acht jaar in functie achter de rug, waarin hij de centrale bank afschafte en de staatsschuld kwijtgescholden werd. Van Buren had vier jaar gediend, waarin de federale overheid onafhankelijk werd van het banksysteem. Echter, de verkiezingen van 1840 waren een uitzondering. Van Buren werd verslagen door een ongekend demagogische campagne, geleid door de eerste grote moderne campagnevoorzitter, Thurlow Weed. Hij was een pionier op het gebied van campagne-uitingen zoals pakkende slogans, buttons, liedjes en parades, die ons nu bekend zijn. Weeds tactieken leidden ertoe dat de onbekende Whig, generaal William Henry Harrison, aan de macht kwam. Dit was echter een toevallige overwinning. In 1844 waren de Democraten vastbesloten om met dezelfde campagnetactieken terug te vechten en van plan om dat jaar het presidentschap terug te winnen. Van Buren zou natuurlijk de triomfantelijke koers van de Jacksoniaanse beweging hervatten. Maar toen deed zich een noodlottige gebeurtenis voor: de Democratische partij werd verdeeld over de cruciale kwestie van de slavernij, of beter gezegd, de uitbreiding van de slavernij naar nieuwe gebieden. De veronderstelde makkelijke herverkiezing van Van Buren strandde door een breuk binnen de partij over de toelating van Texas als slavenstaat. Van Buren was tegen, Jackson was voor, en deze verdeeldheid symboliseerde de bredere scheuren binnen de Democratische partij. Slavernij, een ernstige antiliberale fout binnen het libertarisme van het Democratische programma, ondermijnde de partij en haar libertarisme volledig. De Burgeroorlog ging gepaard met ongekend bloedvergieten en verwoestingen. Het triomferende, bijna eenpartijstelsel van het Republikeinse regime gebruikte deze situatie om zijn statistische, voorheen Whig-programma door te voeren. Dit omvatte nationale regeringsmacht, beschermende invoerrechten, subsidies voor grote bedrijven, inflatoir papiergeld, een hernieuwde controle van de federale overheid over het bankwezen, grootschalige interne verbeteringen, hoge accijnzen en, tijdens de oorlog, dienstplicht en inkomstenbelasting. Bovendien verloren de staten hun vroegere recht op secessie en andere bevoegdheden ten opzichte van de federale overheid. Na de oorlog hervatte de Democratische partij haar libertarische koers. Maar ze stonden nu voor een veel langere en moeilijkere weg naar vrijheid dan voorheen. We hebben gezien hoe Amerika de diepste libertarische traditie heeft ontwikkeld. Deze traditie is nog steeds terug te vinden in veel van onze politieke retoriek en wordt weerspiegeld in de pittige, individualistische houding van een groot deel van het Amerikaanse volk ten opzichte van de overheid. In dit land is er meer vruchtbare grond voor een heropleving van het libertarisme dan ergens anders.

We kunnen nu vaststellen dat de snelle groei van de libertarische beweging en de Libertarische Partij in de jaren zeventig stevig geworteld is in wat Bernard Bailyn beschreef als een krachtige 'permanente erfenis' van de Amerikaanse Revolutie. Maar als deze erfenis zo essentieel is voor de Amerikaanse traditie, wat is er dan misgegaan? Waarom is er nu een nieuwe libertarische beweging nodig om de Amerikaanse droom terug te winnen?

Om deze vraag te beantwoorden, moeten we eerst begrijpen dat het klassieke liberalisme een serieuze bedreiging vormde voor de politieke en economische belangen van de heersende klassen. Deze klassen, waaronder koningen, edelen, aristocraten, bevoorrechte kooplieden, militaire machtsstructuren en staatsbureaucratieën, profiteerden van de Oude Orde. Ondanks drie grote gewelddadige revoluties die door liberalen zijn ontketend --- de Engelse in de 17e eeuw en de Amerikaanse en Franse in de 18e eeuw --- waren de overwinningen in Europa slechts gedeeltelijk. Het verzet was sterk en slaagde erin om monopolies op grondbezit, religieuze instellingen en een oorlogszuchtig buitenlands en militair beleid in stand te houden. Ook wisten ze het kiesrecht enige tijd te beperken tot de rijke elite. De liberalen moesten zich richten op het verbreden van het kiesrecht. Voor beide partijen was immers duidelijk dat de objectieve economische en politieke belangen van de meerderheid van de bevolking lagen in individuele vrijheid. Het is interessant om te vermelden dat aan het begin van de 19e eeuw de laissez-faire krachten bekend stonden als 'liberalen' en 'radicalen' (voor de puristen en consequentere onder hen). De oppositie die de Oude Orde wilde behouden of ernaar terug wilde keren, werd algemeen aangeduid als 'conservatieven'.

Het conservatisme ontstond in het begin van de negentiende eeuw als een bewuste poging om het verfoeide werk van de nieuwe klassiek liberale geest, voortkomend uit de Amerikaanse, Franse en industriële revoluties, ongedaan te maken. Geïnspireerd door de reactionaire Franse denkers Bonald en Maistre, streefde het conservatisme ernaar gelijke rechten en gelijkheid voor de wet te vervangen door de gestructureerde en hiërarchische heerschappij van bevoorrechte elites. Daarnaast wilden zij individuele vrijheid en een minimale overheid vervangen door absolute heerschappij en een grote overheid. Religieuze vrijheid moest wijken voor de theocratische dominantie van een staatskerk. Vrede en vrije handel zouden plaatsmaken voor militarisme, mercantilistische beperkingen en oorlog in het belang van de natiestaat. Ook de opkomst van industrie en productie moest plaatsmaken voor de oude feodale en agrarische orde. Het conservatisme wilde bovendien de nieuwe wereld van massaconsumptie en stijgende levensstandaarden voor iedereen vervangen door de Oude Orde, waarin de massa een kaal bestaan leidde en de heersende elite in luxe consumeerde.

Tegen het midden van de negentiende eeuw begonnen de conservatieven in te zien dat hun zaak gedoemd was als ze bleven vasthouden aan de volledige afschaffing van de Industriële Revolutie en de enorme stijging van de levensstandaard van de massa. Ook hun verzet tegen de verruiming van het kiesrecht plaatste hen openlijk tegenover de belangen van het publiek. Daarom besloot de 'rechtervleugel' --- een term die verwijst naar de plaats waar de vertegenwoordigers van de Oude Orde tijdens de Franse Revolutie in de vergaderzaal zaten --- van koers te veranderen. Ze actualiseerden hun statische credo door hun directe verzet tegen industrialisme en democratisch stemrecht op te geven. In plaats van de openlijke haat en minachting van het oude conservatisme voor de massa, gebruikten de nieuwe conservatieven dubbelhartigheid en demagogie. Ze maakten de massa het hof met de boodschap: 'Ook wij zijn voorstander van industrialisatie en een hogere levensstandaard. Maar om deze doelen te bereiken moeten we de industrie reguleren voor het algemeen belang; we moeten georganiseerde samenwerking opstellen in plaats van het natuurwetmatige 'eet-of-wordt-gegeten' van de vrije en concurrerende markt. En bovenal moeten we de natievernietigende liberale leerstellingen van vrede en vrije handel vervangen door de natieverheerlijkende maatregelen van oorlog, protectionisme, imperium en militaire dapperheid.' Voor al deze veranderingen was natuurlijk een grote overheid nodig in plaats van een minimale overheid.

En zo keerden aan het eind van de negentiende eeuw het statisme en de grote overheid terug, maar nu met een pro-industrieel en pro-welzijnsbeleid. De Oude Orde kwam terug, dit keer echter met een andere samenstelling van begunstigden. Het waren niet meer de aristocratie, de feodale landheren, het leger, de bureaucratie en de bevoorrechte kooplieden, maar nu vooral het leger, de bureaucratie, de verzwakte feodale landheren en vooral de bevoorrechte fabrikanten. Nieuw Rechts, onder leiding van Bismarck in Pruisen, vormde een rechts collectivisme dat was gebaseerd op oorlog, militarisme, protectionisme en verplichte kartelvorming binnen het bedrijfsleven en de industrie. Dit leidde tot een gigantisch netwerk van controles, voorschriften, subsidies en privileges, dat een groot partnerschap vormde tussen de Grote Overheid en specifieke bevoorrechte elementen in de bedrijfswereld en de industrie.

Er moest iets gedaan worden aan het nieuwe fenomeen van een massaal aantal industriële loonarbeiders, het zogenaamde 'proletariaat'. Gedurende de achttiende en vroege negentiende eeuw, en zelfs tot het einde van de negentiende eeuw, steunde de meerderheid van de arbeiders het laissez-faire-principe en de vrije concurrerende markt. Zij zagen dit als de beste optie voor hun lonen en arbeidsomstandigheden, en voor een groeiend aanbod van goedkope consumptiegoederen. Zelfs de vroege vakbonden in Groot-Brittannië waren sterke voorstanders van laissez-faire. Nieuwe conservatieven, geleid door Bismarck in Duitsland en Disraeli in Groot-Brittannië, verzwakten de libertarische wil van de arbeiders. Ze deden dit door krokodillentranen te laten om de omstandigheden van de industriële arbeiders, terwijl ze tegelijk de industrie karteliseerden en reguleren, wat efficiënte concurrentie niet per ongeluk belemmerde. In het begin van de twintigste eeuw werd de nieuwe conservatieve 'bedrijfsstaat' --- het dominante politieke systeem in de Westerse wereld, toen en nu --- verrijkt met zogenaamde 'verantwoordelijke' en corporatistische vakbonden. Deze vakbonden fungeerden als junior partners van de Grote Overheid en bevoordeelden grote bedrijven binnen het nieuwe statistische en corporatistische besluitvormingssysteem.

Om dit nieuwe systeem te vestigen en een Nieuwe Orde te creëren die een gemoderniseerde versie was van het ancien régime van voor de Amerikaanse en Franse revoluties, moesten de nieuwe heersende elites een gigantisch bedrog plegen op het misleide publiek. Dit bedrog houdt tot op de dag van vandaag stand. Terwijl het bestaan van elke regering, of het nu een absolute monarchie of een militaire dictatuur is, steunt op de instemming van de meerderheid van het publiek, moet een democratische regering deze instemming op een meer directe en dagelijkse manier zien te verwerven. Om dat te bereiken, moesten de nieuwe conservatieve elites het publiek op cruciale en fundamentele manieren zien te paaien. De massa's moesten ervan overtuigd worden dat tirannie beter was dan vrijheid, dat een gekartelliseerd en geprivilegieerd industrieel feodalisme voordeliger was voor consumenten dan een vrije, concurrerende markt, dat een gekartelliseerd monopolie moest worden opgelegd in naam van antimonopolie, en dat oorlog en militaire verrijking, ten goede van de heersende elites, werkelijk in het belang waren van het dienstplichtige, belaste en vaak afgeslachte publiek. Hoe zou dit alles gerealiseerd moeten worden?

In alle samenlevingen wordt de publieke opinie gevormd door de intellectuele klassen, de opiniemakers van de maatschappij. De meeste mensen bedenken of verspreiden zelf geen ideeën en concepten; in tegendeel, ze nemen vaak de ideeën over die door professionele intellectuelen en handelaars in gedachten worden gepromoot. Door de geschiedenis heen, zoals we verderop zullen zien, hebben despoten en heersende elites veel meer behoefte gehad aan de diensten van intellectuelen dan aan vreedzame burgers in een vrije samenleving. Staten hebben altijd opiniërende intellectuelen nodig gehad om het publiek te laten geloven dat hun heerschappij wijs, goed en onvermijdelijk is; ze moeten geloven dat de 'keizer kleren heeft'. Tot aan de moderne tijd waren dergelijke intellectuelen doorgaans kerkelijken of toverdokters, de hoeders van de religie. Dit eeuwenoude partnerschap tussen kerk en staat was een hechte samenwerking. De kerk vertelde haar misleide volgelingen dat de koning regeerde op goddelijke aanwijzing en daarom gehoorzaamd moest worden. In ruil daarvoor gaf de koning een aanzienlijk deel van de belastinginkomsten aan de kerk. Daarom was het van groot belang voor de libertarische klassiek-liberalen om successen te behalen in de scheiding van Kerk en Staat. De nieuwe liberale wereld was er een waarin intellectuelen seculier konden zijn en in hun eigen levensonderhoud konden voorzien, los van staatsubsidies.

Om hun nieuwe statistische orde en neomercantilistische corporatieve staat te vestigen, moesten de nieuwe conservatieven een nieuwe alliantie smeden tussen intellectuelen en de staat. In een steeds seculierder tijdperk betekende dit vooral samenwerking met seculiere intellectuelen in plaats van met kerkmensen. Specifiek zochten ze hierbij de samenwerking van een nieuwe generatie professoren, promovendi, historici, leraren, technocratische economen, maatschappelijk werkers, sociologen, artsen en ingenieurs. Deze nieuwe alliantie bestond uit twee delen. In het begin van de negentiende eeuw vertrouwden de conservatieven, die zich lieten overtreffen door hun liberale tegenstanders, sterk op de vermeende deugden van irrationaliteit, romantiek, traditie en theocratie. Door de nadruk te leggen op traditie en irrationele symbolen konden de conservatieven het publiek verleiden om de bevoorrechte hiërarchische heerschappij voort te zetten en om de natiestaat en zijn oorlogsmachine te blijven aanbidden. In het laatste deel van de negentiende eeuw nam het nieuwe conservatisme de schijn van rede en 'wetenschap' aan. Nu was het de wetenschap die beweerde dat de economie en de maatschappij bestuurd moesten worden door technocratische 'experts'. In ruil voor het verspreiden van deze boodschap aan het publiek werden de nieuwe generatie intellectuelen beloond met banen en prestige als verdedigers van de Nieuwe Orde, evenals als planners en regelaars van de nieuw gekarteliseerde economie en maatschappij.

Om de dominantie van het nieuwe statisme over de publieke opinie te waarborgen en de instemming van het publiek te vormen, begonnen de regeringen in de Westerse wereld aan het eind van de negentiende en het begin van de twintigste eeuw met het beheersen van het onderwijs. Ze wilden de ideeën en opvattingen van de mensen beïnvloeden, en dit deden ze door middel van leerplichtwetten en een netwerk van openbare scholen. De openbare scholen werden doelbewust ingezet om jonge leerlingen gehoorzaamheid aan de staat en andere burgerdeugden bij te brengen. Deze statisering van het onderwijs leidde er bovendien toe dat leraren en professionele onderwijskundigen uitgroeiden tot een van de belangrijkste belangen in de uitbreiding van het statisme.

Een van de manieren waarop de nieuwe statistische intellectuelen te werk gingen, was door de betekenis van oude etiketten te veranderen. Op deze manier konden ze de emotionele connotaties die aan deze etiketten verbonden waren, manipuleren in de hoofden van het publiek. De laissez-faire libertariërs stonden lange tijd bekend als 'liberalen', terwijl de meest radicale onder hen als 'radicalen' werden aangeduid. Ze werden ook als 'progressieven' gezien, omdat zij de aanhangers waren van industriële vooruitgang, vrijheid en een stijgende levensstandaard voor consumenten. De nieuwe generatie statistische academici en intellectuelen maakte zich de termen 'liberaal' en 'progressief' eigen. Ze slaagden erin om hun laissez-faire tegenstanders als ouderwets, 'neanderthaler' en 'reactionair' te bestempelen. Zelfs de term 'conservatief' werd aan de klassiek liberalen opgelegd. Zoals we hebben gezien, konden de nieuwe statisten zich ook het begrip 'rede' toe-eigenen.

Als de laissez-faire liberalen verward waren door de opkomst van het statisme en mercantilisme, dat zich als 'progressief' corporatief statisme manifesteerde, was er een andere reden voor de achteruitgang van het klassieke liberalisme aan het eind van de negentiende eeuw: de groei van het socialisme. Dit idee deed zijn intrede in de jaren 1830 en kende na de jaren 1880 een enorme uitbreiding. Het bijzondere aan het socialisme was dat het een verwarrende, hybride beweging was, beïnvloed door de twee al bestaande polaire ideologieën: liberalisme en conservatisme. Van de klassiek-liberalen namen de socialisten een openlijke acceptatie van industrialisme en de Industriële Revolutie over. Ze eerden de 'wetenschap' en de 'rede' en toonden ten minste een retorische toewijding aan klassieke liberale idealen zoals vrede, individuele vrijheid en een stijgende levensstandaard. Inderdaad, de socialisten waren, lang vóór de latere corporatisten, pioniers in het omarmen van wetenschap, rede en industrialisme. Ze namen niet alleen de klassiek-liberale toewijding aan democratie over, maar breidden deze uit met de eis voor een 'uitgebreide democratie', waarin 'het volk' de economie en elkaar zou besturen.

Aan de andere kant namen de socialisten van de conservatieven de toewijding aan dwang en statistische middelen over om hun liberale doelen te bereiken. Industriële harmonie en groei moesten worden gerealiseerd door de staat te laten uitgroeien tot een almachtig instituut dat de economie en de maatschappij regeerde in naam van de 'wetenschap'. Een voorhoede van technocraten zou de volledige controle over ieders leven en bezit overnemen, zogenaamd in naam van het 'volk' en de 'democratie'. Niet tevreden met de liberale verworvenheden van rede en vrijheid voor wetenschappelijk onderzoek, zou de socialistische staat de heerschappij van wetenschappers over de rest invoeren. Evenmin waren de socialisten tevreden met liberalen die arbeiders de vrijheid gaven om onvoorstelbare welvaart te bereiken. De socialistische staat zou in plaats daarvan de heerschappij van arbeiders over anderen instellen - of liever, de heerschappij van politici, bureaucraten en technocraten in hun naam. Ook het liberale credo van gelijkheid van rechten en gelijkheid voor de wet zou door de socialistische staat met voeten getreden worden. In plaats daarvan streefde men naar het monsterlijke en onmogelijke doel van gelijkheid of uniformiteit in resultaten. Of liever gezegd, er zou een nieuwe bevoorrechte elite en nieuwe klasse worden opgericht, zogenaamd in naam van het realiseren van deze onmogelijke gelijkheid.

Het socialisme was een verwarrende en hybride beweging. Het probeerde de liberale idealen van vrijheid, vrede en industriële harmonie en groei te realiseren. Deze doelen kunnen echter alleen worden bereikt door vrijheid en de scheiding van de overheid van vrijwel alle aspecten van het leven. De socialisten hanteerden hiervoor oude conservatieve middelen zoals statisme, collectivisme en hiërarchische privileges. Dit was een beweging die gedoemd was om te falen, en dat gebeurde ook in veel landen waar socialisten in de twintigste eeuw aan de macht kwamen. De massa's werden alleen geconfronteerd met ongekend wanbeleid, hongersnood en armoede.

Maar het ergste van de opkomst van de socialistische beweging was dat deze in staat was de klassiek-liberalen 'ter linkerzijde' te overvleugelen. Hiermee bedoel ik dat ze de partij van hoop, radicalisme en revolutie in de Westerse wereld werden. Zoals de verdedigers van het ancien régime tijdens de Franse Revolutie rechts in de zaal zaten, zo bevonden de liberalen en radicalen zich aan de linkerkant. Van dat moment tot de opkomst van het socialisme werden de libertarische klassiek-liberalen als 'links', zelfs 'extreem links', beschouwd in het ideologische spectrum. Zelfs in 1848 zaten militante laissez-faire Franse liberalen zoals Frédéric Bastiat aan de linkerkant in de nationale vergadering. De klassiek-liberalen waren begonnen als de radicale, revolutionaire partij in het Westen, als de partij van hoop en verandering voor vrijheid, vrede en vooruitgang. Het was een ernstige strategische fout om zich te laten overvleugelen en de socialisten de indruk te geven dat zij de 'partij van links' waren. Dit leidde ertoe dat de liberalen ten onrechte in een verwarde middenpositie werden geplaatst, met socialisme en conservatisme als de tegengestelde polen. Aangezien het libertarisme niets anders is dan een partij van verandering en vooruitgang in de richting van vrijheid, betekende het opgeven van die rol het verlies van een groot deel van hun bestaansrecht - zowel in de realiteit als in de perceptie van het publiek.

Maar dit alles had niet kunnen gebeuren als de klassiek-liberalen zichzelf niet van binnenuit hadden laten verzwakken. Ze hadden kunnen benadrukken -- zoals sommigen van hen inderdaad deden -- dat het socialisme een verwarde en intern inconsistente beweging was, een quasi-conservatieve stroming die absolute monarchie en feodalisme een modern gezicht gaf. Zijzelf waren nog steeds de enige echte radicalen, onverschrokken mensen die zich vasthielden aan niets minder dan de volledige overwinning van het libertarische ideaal.

## Verval van binnenuit

Het socialisme was een verwarrende en hybride beweging. Het probeerde de liberale idealen van vrijheid, vrede en industriële harmonie te realiseren. Deze doelen kunnen echter alleen worden bereikt door vrijheid en de scheiding van de overheid van vrijwel alles. De socialisten maakten gebruik van oude conservatieve methoden zoals statisme, collectivisme en hiërarchische privileges. Dit was een gedoemde beweging die in veel landen waar ze in de twintigste eeuw aan de macht kwamen, alleen maar leidde tot wanbeleid, hongersnood en armoede. Het meest problematische aan de opkomst van het socialisme was dat deze beweging de klassiek-liberalen 'ter linkerzijde' overtrof. Daarmee bedoel ik dat ze de partij werden van hoop, radicalisme en revolutie in de Westerse wereld. Tijdens de Franse Revolutie zaten de verdedigers van het ancien régime rechts in de zaal, terwijl de liberalen en radicalen aan de linkerkant zaten. Van dat moment totdat het socialisme opkwam, werden de libertarische klassiek-liberalen als 'links', zelfs 'extreem links', beschouwd in het ideologische spectrum. In 1848 bijvoorbeeld zaten actieve laissez-faire Franse liberalen zoals Frédéric Bastiat aan de linkerkant van de nationale vergadering. De klassiek-liberalen waren in het Westen begonnen als de radicale, revolutionaire partij voor vrijheid, vrede en vooruitgang. Het was een ernstige strategische fout om de socialisten de kans te geven zich als de 'partij van links' te presenteren. Hierdoor kwamen de liberalen in een verwarrende middenpositie terecht, met socialisme en conservatisme als tegengestelde polen. Aangezien het libertarisme niets meer is dan een beweging voor verandering en vooruitgang richting vrijheid, betekende het opgeven van die rol het verlies van een groot deel van hun bestaansrecht -- zowel in de werkelijkheid als in de perceptie van het publiek. Dit alles had echter niet kunnen gebeuren als de klassiek-liberalen zichzelf niet van binnenuit hadden verzwakt. Ze hadden kunnen benadrukken -- en sommigen deden dat ook -- dat het socialisme een verwarde en intern inconsistente beweging was, een quasi-conservatieve stroming die absolute monarchie en feodalisme een modern gezicht gaf. Zij zelf waren nog steeds de enige echte radicalen, onverschrokken mensen die streefden naar niets minder dan de volledige overwinning van het libertarische ideaal.

Maar na het behalen van indrukwekkende gedeeltelijke overwinningen op het statisme, begonnen de klassiek-liberalen hun radicalisme te verliezen. Hun vasthoudendheid in de strijd tegen het conservatieve statisme, gericht op een definitieve overwinning, nam af. In plaats van deze gedeeltelijke overwinningen te gebruiken als basis voor verdere druk, raakten de klassiek-liberalen hun ijver voor verandering en het zuiveren van principes kwijt. Ze begrepen zich tevreden met het behouden van hun bestaande overwinningen en transformeerden van een radicale naar een conservatieve beweging. Met 'conservatief' doel ik op het tevreden zijn met het handhaven van de status quo. Kortom, de liberalen lieten het veld open voor het socialisme om de partij van hoop en radicalisme te worden. Zelfs latere corporatisten konden zich voordoen als 'liberalen' en 'progressieven', in tegenstelling tot de 'extreem rechtse' en 'conservatieve' klassiek-liberalen. De laatsten lieten zich in een positie dwingen waarin ze niets meer hoopten dan op stilstand, een afwezigheid van verandering. Zo'n strategie is dwaas en onhoudbaar in een wereld die voortdurend verandert.

De degeneratie van het liberalisme betrof niet alleen de houding en strategie, maar ook de principes. De liberalen namen het namelijk voor lief dat de staat de macht om oorlog te voeren, het onderwijs, het geld en bankieren, en de wegen in handen hield. Kortom, ze lieten de controle over alle cruciale machtsfactoren in de samenleving aan de staat over. In tegenstelling tot de totale vijandigheid van de achttiende-eeuwse liberalen jegens de uitvoerende macht en de bureaucratie, tolereerden en verwelkomden de negentiende-eeuwse liberalen zelfs de opschaling van de macht van de uitvoerende macht en de oprichting van een diepgewortelde oligarchische ambtenarenbureaucratie.

Bovendien versmolten principe en strategie in het verval van de achttiende-eeuwse en vroeg-negentiende-eeuwse liberale inzet voor het 'abolitionisme.' Dit was de overtuiging dat, ongeacht of het ging om slavernij of een ander aspect van het statisme, deze instituties zo snel mogelijk moesten worden afgeschaft. De onmiddellijke afschaffing van het statisme, hoewel in de praktijk onwaarschijnlijk, moest worden nagestreefd als de enige morele optie. Het kiezen voor een geleidelijke afschaffing in plaats van een onmiddellijke afschaffing van een kwaadwillende en dwingende instelling, betekent het goedkeuren van dat kwaad en daarmee het schenden van libertarische principes. Zoals de grote abolitionist en libertariër William Lloyd Garrison zei: 'Hoe oprecht we ook aandringen op onmiddellijke afschaffing, het zal, helaas, uiteindelijk een geleidelijke afschaffing zijn. We hebben nooit gezegd dat slavernij in één klap omvergeworpen zou worden; dat het zo zou moeten zijn, zullen we altijd beweren.'

Er waren twee belangrijke veranderingen in de filosofie en ideologie van het klassieke liberalisme. Deze veranderingen vormden zowel een voorbeeld van als een bijdrage aan het verval van het liberalisme als een vitale, progressieve en radicale kracht in de Westerse wereld. De eerste en meest significante verandering was het loslaten van de filosofie van natuurlijke rechten, die vervangen werd door technocratisch utilitarisme. In plaats van vrijheid te baseren op de dwingende moraal van het recht van elk individu op vrijheid en eigendom, werd vrijheid volgens het utilitarisme gezien als de beste manier om een vaag gedefinieerd algemeen welzijn te bereiken. Deze verschuiving van natuurrechten naar utilitarisme had twee ernstige gevolgen. Ten eerste werd de zuiverheid van het doel en de consistentie van het principe onvermijdelijk aangetast. De natuurrechtlibertariër, die zich inzet voor moraliteit en gerechtigheid, strijdt hardnekkig voor het pure principe. De utilitarist daarentegen waardeert vrijheid slechts als een tijdelijk nuttig middel. Wat tijdelijk nuttig is, kan echter met de wind meewaaien, en dat doet het ook. Hierdoor wordt het voor de utilitarist in zijn koele berekening van kosten en baten gemakkelijk om in tal van gevallen voor statisme te kiezen en zo principes op te geven. Dit gebeurde precies met de Benthamitische utilitaristen in Engeland. Aanvankelijk begonnen ze met ad hoc-libertarisme en laissez-faire, maar al snel vonden ze het steeds gemakkelijker om naar statisme af te glijden. Een voorbeeld hiervan was hun streven naar een 'efficiënt' ambtenarenapparaat en uitvoerende macht. Deze efficiëntie kreeg prioriteit en verving zelfs elk begrip van rechtvaardigheid of recht.

Ten tweede, en net zo belangrijk, is het zeldzaam om een utilitariër te vinden die ook radicaal is en ijvert voor de onmiddellijke afschaffing van kwaad en dwang. Utilitaristen, met hun focus op doelmatigheid, verzetten zich bijna onvermijdelijk tegen verstoringen of radicale veranderingen. Er zijn geen utilitaristische revolutionairen geweest. Daarom zijn utilitaristen nooit onmiddellijk abolitionisten. De abolitionist streeft ernaar misstanden en onrecht zo snel mogelijk uit te bannen. Bij het nastreven van dit doel is er geen ruimte voor koele, ad hoc afwegingen van kosten en baten. Hierdoor lieten de klassieke liberale utilitaristen het radicalisme achter zich en werden ze slechts geleidelijke hervormers. Maar door hervormers te worden, plaatsten ze zichzelf ook onvermijdelijk in de rol van adviseurs en efficiëntiedeskundigen voor de staat. Met andere woorden, ze lieten zowel het libertarische principe als een principiële libertarische strategie los. De utilitaristen eindigden als apologeten van de bestaande orde, van de status quo, en waren daardoor kwetsbaar voor de beschuldigingen van socialisten en progressieve corporatisten dat ze enkel bekrompen en conservatieve tegenstanders van verandering waren. Zo begonnen ze als radicalen en revolutionairen, de tegenhangers van de conservatieven, en eindigden ze als het toonbeeld van waartegen ze hadden gevochten.

Deze utilitaristische verlamming van het libertarisme is nog steeds aan de gang. In de begindagen van het economische denken heeft het utilitarisme, onder invloed van Bentham en Ricardo, de vrije markteconomie veroverd. Deze invloed is vandaag de dag nog steeds sterk aanwezig. De huidige vrije markteconomie zit vol met oproepen tot gradualisme, met minachting voor ethiek, rechtvaardigheid en consistente principes. Daarnaast is er een bereidheid om de principes van de vrije markt op te geven zodra de kosten-batenverhouding in het geding komt. Daarom wordt de huidige vrije markteconomie door intellectuelen vaak gezien als een verdediging van een enigszins gewijzigde status quo. En die beschuldiging is te vaak terecht.

Een tweede, versterkende verandering in de ideologie van klassiek-liberalen vond plaats aan het eind van de negentiende eeuw. Toen namen ze, althans voor een paar decennia, de theorieën van het sociaal evolutionisme over, vaak aangeduid als 'sociaal Darwinisme'. Statistische historici hebben sociaal-darwinistische laissez-faire-liberalen zoals Herbert Spencer en William Graham Sumner vaak neergezet als wrede voorvechters van de uitroeiing of in ieder geval de verdwijning van de sociaal 'ongeschikten'. Veel van deze ideeën waren simpelweg een versiering van de gezonde economische en sociologische opvattingen over de vrije markt, gecast in de populaire mode van het evolutionisme. Maar het werkelijk belangrijke en verlammende aspect van hun sociaal-darwinisme was de onwettige overdracht naar de sociale sfeer van de opvatting dat soorten, of later genen, zeer langzaam veranderen over duizenden jaren. De sociaal-darwinistische liberaal liet dus het idee van revolutie of radicale verandering varen. In plaats daarvan koos hij ervoor om achterover te leunen en te wachten op de onvermijdelijke, kleine evolutionaire veranderingen die zich over eeuwen zouden voortzetten. Kortom, negerend dat het liberalisme de macht van de heersende elites had moeten doorbreken door een reeks radicale veranderingen en revoluties, werden de sociaal-darwinisten conservatieven. Zij predikten tegen alle radicale maatregelen en waren alleen voorstander van de meest minutieuze, geleidelijke veranderingen.

In feite is de grote libertariër Spencer een fascinerend voorbeeld van de veranderingen binnen het klassieke liberalisme, een ontwikkeling die in de Verenigde Staten wordt weerspiegeld door William Graham Sumner. Herbert Spencer belichaamt in zekere zin een groot deel van het verval van het liberalisme in de negentiende eeuw. Hij begon als een zeer radicale liberaal, bijna als een pure libertariër. Maar zodra het virus van de sociologie en het sociaal-darwinisme zijn geest binnendrong, liet Spencer het libertarisme als dynamische, radicale historische beweging achter zich. Hij schudde het echter niet louter theoretisch van zich af. Terwijl hij uitkeek naar een uiteindelijke overwinning van pure vrijheid, waarbij 'contract' het zou winnen van 'status' en industrie van militarisme, begon Spencer deze overwinning als onvermijdelijk te beschouwen. Maar hij dacht dat dit pas zou plaatsvinden na millennia van geleidelijke evolutie. Daarom liet hij het liberalisme als een strijdbaar en radicaal credo achter zich. In de praktijk beperkte hij zijn liberalisme tot een vermoeiend en conservatief verzet tegen het groeiende collectivisme en het statisme van zijn tijd.

Maar als het utilitarisme, gesteund door het sociaal-darwinisme, de belangrijkste reden voor het filosofische en ideologische verval van de liberale beweging was, dan was het opgeven van de strikte principes tegen oorlog, imperialisme en militarisme de meest catastrofale oorzaak voor haar ondergang. In land na land werd het klassieke liberalisme vernietigd door de aanlokkelijke roep van de natiestaat en het imperium. In Engeland verloochenenden liberalen aan het eind van de negentiende en het begin van de twintigste eeuw het anti-oorlogs- en anti-imperialistische 'Little Englandisme' van Cobden, Bright en de Manchester School. In plaats daarvan omarmden ze het ongegeneerd getitelde 'Liberal Imperialism' en sloten zich aan bij de conservatieven bij de uitbreiding van het imperium. Ook gingen ze samenwerken met conservatieven en rechtse socialisten in het destructieve imperialisme en collectivisme van de Eerste Wereldoorlog. In Duitsland slaagde Bismarck erin om de eerder bijna triomferende liberalen te splitsen door hen te verleiden met de eenwording van Duitsland via bloed en ijzer. In beide landen leidde dit tot de ondergang van de liberale zaak.

In de Verenigde Staten was de klassieke liberale partij lange tijd de Democratische Partij. In de tweede helft van de negentiende eeuw werd deze vaak aangeduid als 'de partij van de persoonlijke vrijheid'. Het was niet alleen een verdediger van persoonlijke vrijheid, maar ook van economische vrijheid. De partij was een standvastige tegenstander van het drankverbod, de blauwe zondagswetten en de leerplicht. Daarnaast streefde ze naar vrije handel, hard geld (het vermijden van inflatie door de overheid), de scheiding van bankwezen en staat, en een minimaal overheidsoptreden. De Democratische Partij beschouwde staatsmacht als verwaarloosbaar en de federale macht als vrijwel onbestaand. Op het gebied van buitenlands beleid was de Democratische Partij, hoewel minder rigoureus, doorgaans een voorvechter van vrede, antimilitarisme en anti-imperialisme. Echter, zowel het persoonlijke als het economische libertarisme werden verlaten toen de Democratische Partij in 1896 werd overgenomen door de krachten van Bryan. Twee decennia later werd het beleid van non-interventie ruw aan de kant geschoven door Woodrow Wilson. Deze interventie en de daaropvolgende oorlog leidden tot een eeuw van dood en verwoesting, met voortdurende conflicten en nieuwe heerschappijen. Ook bevorderden ze in alle oorlogvoerende landen een nieuw corporatistisch statisme, een welvaartsstaat waarin grote regeringen, bedrijven, vakbonden en intellectuelen samenwerken.

De laatste adempauze van het oude laissez-faire liberalisme in Amerika werd gevormd door moedige en ouder wordende libertariërs. Rond de eeuwwisseling richtten zij samen de Anti-Imperialist League op om de Amerikaanse oorlog tegen Spanje en de daaropvolgende imperialistische oorlog tegen de Filippino's te bestrijden. Deze oorlogen hadden als doel nationale onafhankelijkheid te verwerven, zowel van Spanje als van de Verenigde Staten. Tegenwoordig lijkt het misschien vreemd dat een anti-imperialist geen marxist is, maar het verzet tegen imperialisme begon bij laissez-faire liberalen zoals Cobden en Bright in Engeland en Eugen Richter in Pruisen. In feite bestond de Anti-Imperialist League, onder leiding van de industrieel en econoom Edward Atkinson uit Boston (en inclusief Sumner), grotendeels uit laissez-faire radicalen. Zij hadden al eerder strijd gevoerd voor de afschaffing van de slavernij en waren daarna voorstanders van vrije handel, hard geld en een minimale overheid. Voor hen vormde de strijd tegen het nieuwe Amerikaanse imperialisme een voortzetting van hun levenslange verzet tegen dwang, statisme en onrecht. Dit was hun verzet tegen de grote overheid op elk gebied van het leven, zowel binnenlands als buitenlands.

We hebben het nogal akelige verhaal gevolgd van de ondergang van het klassieke liberalisme, na zijn opkomst en gedeeltelijke triomf in de vorige eeuwen. Wat is dan de reden voor de opleving en bloei van libertarische ideeën en activiteiten in de afgelopen jaren, vooral in de Verenigde Staten? Hoe konden deze krachtige krachten en coalities voor het statisme zoveel toegeven aan een herrezen libertarische beweging? Zou de hernieuwde opmars van het statisme aan het eind van de negentiende en in de twintigste eeuw niet eerder aanleiding tot somberheid moeten geven dan een herleving van een schijnbaar op sterven na dood libertarisme? Waarom bleef het libertarisme niet gewoon dood en begraven?

We hebben gezien waarom het libertarisme van nature als eerste en het sterkst kon opkomen in de Verenigde Staten, een land met een rijke libertarische traditie. Maar we hebben nog niet gekeken naar de vraag: waarom heeft het libertarisme de afgelopen jaren een renaissance doorgemaakt? Welke hedendaagse omstandigheden hebben bijgedragen aan deze verrassende ontwikkeling? We zullen deze vraag uitstellen tot het einde van het boek, totdat we eerst hebben onderzocht wat het libertarische credo is en hoe we dat credo kunnen toepassen om de belangrijkste probleemgebieden in onze samenleving aan te pakken.

**Deel I**

### Het libertarische credo We hebben het best een zorgwekkende verhaal gevolgd over de neergang van het klassieke liberalisme, na de opkomst en gedeeltelijke triomf in voorgaande eeuwen. Wat veroorzaakt dan de opleving en bloei van libertarische ideeën en activiteiten in de afgelopen jaren, vooral in de Verenigde Staten? Hoe konden deze krachtige krachten en coalities van statisme in hemelsnaam zoveel toegeven aan een herrezen libertarische beweging? Zou de weer opkomende invloed van het statisme aan het eind van de negentiende en in de twintigste eeuw niet eerder reden tot somberheid moeten zijn dan een herleving van een schijnbaar stervend libertarisme? Waarom bleef het libertarisme niet gewoon dood en begraven? We hebben gezien waarom het libertarisme van nature het eerst en het sterkst kon ontstaan in de Verenigde Staten, een land met een rijke libertarische traditie. Maar we hebben nog niet bekeken waarom het libertarisme de afgelopen jaren een renaissance heeft doorgemaakt. Welke hedendaagse omstandigheden hebben geleid tot deze verrassende ontwikkeling? We stellen het beantwoorden van deze vraag uit tot het einde van het boek. Eerst moeten we onderzoeken wat het libertarische credo inhoudt en hoe we dit credo kunnen toepassen om belangrijke probleemgebieden in onze samenleving aan te pakken.
