
# Welzijn en de verzorgingsstaat

## WAAROM DE WELVAARTSCRISIS?

Bijna iedereen, ongeacht hun ideologie, is het erover eens dat er iets ernstig mis is met het op hol geslagen welvaartssysteem in de Verenigde Staten. Dit systeem zorgt ervoor dat een steeds groter deel van de bevolking leeft als inactieve, verplichte eisers op de productie van de rest van de samenleving. Enkele cijfers en vergelijkingen zullen de verschillende aspecten van dit probleem schetsen. In 1934, te midden van de grootste depressie in de Amerikaanse geschiedenis en op een dieptepunt in ons economische leven, bedroegen de totale uitgaven van de overheid aan sociale voorzieningen 5,8 miljard dollar. Daarvan was 2,5 miljard dollar bestemd voor directe sociale uitkeringen ('publieke hulp'). In 1976, na vier decennia van de grootste bloei in de Amerikaanse geschiedenis en op een moment dat we de hoogste levensstandaard ter wereld hadden bereikt met een relatief laag werkloosheidsniveau, stegen de totale sociale overheidsuitgaven tot 331,4 miljard dollar. Hierin waren 48,9 miljard dollar aan directe bijstandsuitkeringen inbegrepen. Samenvattend, de totale uitgaven aan sociale voorzieningen stegen in deze vier decennia met maar liefst 5.614 procent, terwijl de directe sociale uitkeringen met 1.856 procent toenamen. Anders gezegd, tussen 1934 en 1976 stegen de uitgaven aan sociale voorzieningen gemiddeld met 133,7 procent per jaar, terwijl de directe sociale uitkeringen gemiddeld met 44,2 procent per jaar toenamen.

Als we kijken naar de directe welzijnssector, zien we dat de uitgaven van 1934 tot 1950 ongeveer gelijkbleven. Daarna schoten ze omhoog, samen met de naoorlogse economische opleving. Van de jaren vijftig tot 1976 steeg de bijstand met maar liefst 84,4 procent per jaar.

Een deel van deze enorme stijgingen kan worden verklaard door inflatie, die de waarde en koopkracht van de dollar heeft verminderd. Wanneer we alle cijfers corrigeren voor inflatie door ze om te rekenen naar 'constante 1958-dollars' (dat wil zeggen dat elke dollar dezelfde koopkracht heeft als in 1958), komen we op de volgende relevante cijfers: - In 1934 waren de totale uitgaven aan sociale voorzieningen 13,7 miljard dollar en de directe bijstand 5,9 miljard dollar. - In 1976 waren de totale uitgaven aan sociale voorzieningen 247,7 miljard dollar en de directe bijstand 36,5 miljard dollar.

Zelfs na correctie voor inflatie, stegen de sociale uitgaven van de overheid in deze 42 jaar met maar liefst 1.798 procent, wat neerkomt op 42,8 procent per jaar. Ook de directe bijstand nam toe met 519 procent, ofwel 12,4 procent per jaar. Daarnaast, als we de cijfers voor directe bijstand in 1950 en 1976 bekijken, gecorrigeerd voor inflatie, dan zien we dat de welzijnsuitgaven in die tussenliggende jaren stegen met 1.077 procent, wat overeenkomt met 41,4 procent per jaar.

Als we de cijfers corrigeren voor bevolkingsgroei (de totale Amerikaanse bevolking was 126 miljoen in 1934 en 215 miljoen in 1976), zien we nog steeds een bijna vertienvoudiging van de totale uitgaven voor sociale voorzieningen. Deze stegen van $ 108 naar $ 1.152 per hoofd van de bevolking in constante 1958-dollars. Ook de directe bijstand neemt toe met meer dan een verdrievoudiging, van $ 47 in 1934 naar $ 170 per hoofd van de bevolking in 1976.

Nog een paar vergelijkingen: van 1955 tot 1976, de jaren van grote welvaart, vervijfvoudigde het totale aantal mensen dat afhankelijk was van bijstand, van 2,2 miljoen naar 11,2 miljoen. Tussen 1952 en 1970 steeg het aantal kinderen van 18 jaar en jonger met 42 procent, maar het aantal bijstandstrekkers nam met 400 procent toe. Hoewel de totale bevolking niet veranderde, steeg het aantal bijstandsgerechtigden in New York City van 330.000 in 1960 naar 1,2 miljoen in 1971. Dit wijst duidelijk op een welvaartscrisis.¹

De crisis blijkt nog veel groter te zijn als we alle sociale steun aan de armen meerekenen bij de 'sociale uitkeringen'. Tussen 1960 en 1969 verdrievoudigde de federale 'hulp aan de armen', van $ 9,5 miljard naar $ 27,7 miljard. De staats- en lokale uitgaven voor sociale voorzieningen stegen van $ 3,3 miljard in 1935 tot $ 46 miljard, wat neerkomt op een stijging van 1.300 procent! De totale uitgaven voor sociale voorzieningen in 1969, inclusief federale, staats- en lokale bijdragen, beliepen maar liefst $ 73,7 miljard.

De meeste mensen zien het hebben van een uitkering als een proces dat buiten de klanten zelf omgaat, bijna als een natuurlijke ramp, zoals een vloedgolf of vulkaanuitbarsting. Dit gebeurt buiten de wil van de mensen die een uitkering ontvangen. Het gebruikelijke gezegde is dat 'armoede' de reden is dat individuen of gezinnen in de bijstand terechtkomen. Maar ongeacht hoe men armoede definieert en op welk inkomensniveau men zich baseert, is het niet te ontkennen dat het aantal mensen of gezinnen onder de 'armoedegrens' sinds de jaren dertig gestaag is afgenomen, en niet andersom. De omvang van de armoede kan dus nauwelijks de spectaculaire groei van het aantal bijstandscliënten verklaren.

De oplossing van het raadsel wordt duidelijk als je je realiseert dat het aantal bijstandsontvangers een 'positieve aanbodfunctie' heeft, zoals dat in de economie wordt genoemd. Met andere woorden: zodra de prikkels om in de bijstand te gaan toenemen, zal ook het aantal bijstandsontvangers stijgen. Een vergelijkbaar effect vindt plaats wanneer de negatieve prikkels om in de bijstand te gaan afnemen. Vreemd genoeg betwist niemand deze conclusie in andere delen van de economie. Neem bijvoorbeeld de situatie waarin iemand, of dat nu de overheid is of een miljardair, een extra $ 10.000 aanbiedt aan iedereen die in een schoenenfabriek wil werken. Het is duidelijk dat daardoor het aantal geïnteresseerde werknemers in de schoenenindustrie zal toenemen. Dit zal ook gebeuren als de negatieve prikkels worden verlaagd, bijvoorbeeld als de overheid belooft dat alle schoenenarbeiders geen inkomstenbelasting hoeven te betalen. Als we dezelfde analyse toepassen op bijstandscliënten zoals we dat doen in de rest van de economie, wordt het antwoord op de welzijnspuzzel glashelder.

Wat zijn de belangrijke prikkels en afschrikkingen om in de bijstand te gaan, en hoe zijn die veranderd? Een cruciale factor is de verhouding tussen het inkomen uit een uitkering en het inkomen uit productieve arbeid. Stel, ter vereenvoudiging, dat het 'gemiddelde' loon voor een 'gemiddelde' arbeider in een bepaalde regio $ 7.000 per jaar bedraagt. Laten we aannemen dat het inkomen uit de bijstand $ 3.000 per jaar is. Dit betekent dat de gemiddelde nettowinst uit werken (vóór belasting) $ 4.000 per jaar is. Als de uitkeringen stijgen tot $ 5.000, of als het gemiddelde loon zakt tot $ 5.000, dan halveert het verschil --- de nettowinst die je maakt door te werken --- van $ 4.000 naar $ 2.000 per jaar. Het is evident dat dit leidt tot een enorme toename in het aantal bijstandsuitkeringen. Dit effect wordt nog versterkt als we in gedachten houden dat werknemers met een inkomen van $ 7.000 hogere belastingen moeten betalen om een omvangrijke groep bijstandsontvangers te onderhouden die vrijwel geen belasting betaalt. We zouden verwachten dat, omdat in de afgelopen periode de uitkeringsniveaus sneller zijn gestegen dan de gemiddelde lonen, steeds meer mensen in de bijstand zullen terechtkomen. Deze trend wordt nog duidelijker als we bedenken dat niet iedereen het 'gemiddelde' inkomen verdient. Vooral 'marginale' werknemers, degenen die onder het gemiddelde inkomen zitten, zullen in grote getale in de bijstand belanden. In ons voorbeeld, als de bijstandsuitkering stijgt tot $ 5.000 per jaar, wat mogen we dan verwachten van werknemers die $ 4.000, $ 5.000 of zelfs $ 6.000 verdienen? De werknemer die voorheen $ 5.000 per jaar verdiende en netto $ 2.000 meer opbracht dan de bijstandsontvanger, ziet nu dat hun verschil is verdwenen. Hij verdient nu niet meer --- en zelfs minder, na aftrek van belastingen --- dan de bijstandscliënt die dankzij de staat in luiheid wordt onderhouden. Is het dan vreemd dat hij overweegt om ook naar de bijstandsvoorzieningen te overstappen?

In de periode van 1952 tot 1970 vervijfvoudigde het aantal bijstandsuitkeringen, van 2 naar 10 miljoen. Tegelijkertijd steeg de gemiddelde maandelijkse uitkering van een bijstandsgezin meer dan verdubbeld, van 82 naar 187 dollar. Dit was een toename van bijna 130 procent, terwijl de consumentenprijzen slechts met 50 procent stegen. Bovendien vergeleek de Citizens Budget Commission van New York City in 1968 de tien staten met de snelst groeiende bijstandsgroepen met de tien staten met de laagste groei. De commissie ontdekte dat de gemiddelde maandelijkse bijstandsuitkering in de tien snelst groeiende staten twee keer zo hoog was als in de tien langzaamste staten. In de eerste groep staten bedroeg de maandelijkse uitkering per persoon gemiddeld 177 dollar, terwijl dit in de laatste groep slechts 88 dollar was.

Een ander voorbeeld van de impact van hoge uitkeringen in verhouding tot het loon dat je kunt verdienen door te werken, werd aangehaald door de McCone Commissie, die de rellen in Watts in 1965 onderzocht. De Commissie ontdekte dat een baan met het minimumloon ongeveer 220 dollar per maand opleverde. Hier moesten echter werkgerelateerde uitgaven zoals kleding en vervoer van worden betaald. In tegenstelling daarmee ontving het gemiddelde bijstandsgezin in het gebied tussen de 177 en 238 dollar per maand, zonder dat daar werkgerelateerde kosten van afgetrokken hoefden te worden.

Een andere belangrijke factor voor de toename van het aantal bijstandsuitkeringen is de afname van de sterke negatieve prikkels om in de bijstand te gaan. Het meest significante obstakel was altijd het stigma dat mensen met een uitkering voelden: het idee dat zij parasiteren en leven van wat anderen produceren, in plaats van zelf bij te dragen. Dit stigma is echter sociaal verzwakt door de opkomst van moderne liberale waarden. Bovendien hebben overheidsinstanties en maatschappelijk werkers de laatste jaren de rode loper uitgerold voor mensen om hen te verwelkomen en zelfs aan te moedigen om zo snel mogelijk in de bijstand te komen. De traditionele visie van de maatschappelijk werker was gericht op het helpen van mensen om zichzelf te helpen en hun onafhankelijkheid te behouden. Het doel was om bijstandsontvangers zo snel mogelijk van de uitkering af te krijgen. Tegenwoordig is het doel van maatschappelijk werkers echter om zoveel mogelijk mensen in de bijstand te krijgen, om hen te informeren over hun 'rechten' en hen te ondersteunen bij het in stand houden van hun situatie. Dit heeft geleid tot een voortdurende versoepeling van de voorwaarden om in aanmerking te komen voor een uitkering. De bureaucratie is verminderd en handhaving van verblijfs-, werk- of inkomensvereisten om een uitkering te krijgen, is vrijwel verdwenen. Iedereen die, hoe gering ook, suggereert dat bijstandsontvangers verplicht zouden moeten worden om werk te accepteren en van de bijstand af te komen, wordt beschouwd als een reactionaire morele melaatse. Nu het oude stigma steeds meer vervaagt, zijn mensen steeds geneigder om snel voor de bijstand te kiezen, in plaats van ervoor terug te deinzen. Irving Kristol heeft scherpzinnig geschreven over de 'welfare explosion' van de jaren zestig:

> Deze 'explosie' werd - deels opzettelijk, deels onbewust - veroorzaakt door overheidsfunctionarissen en ambtenaren die beleid uitvoerden als onderdeel van een 'oorlog tegen armoede'. Interessant is dat veel van dezelfde mensen die deze maatregelen bepleitten en uitvoerden, later verbijsterd waren over de 'bijstandsexplosie'. Het is dan ook niet verwonderlijk dat het enige tijd duurde voordat ze zich realiseerden dat het probleem dat ze probeerden op te lossen, eigenlijk het probleem was dat ze zelf hadden gecreëerd.

Hier zijn de redenen achter de 'welfare explosion' van de jaren zestig:

> Het aantal mensen dat in armoede leeft en recht heeft op een uitkering zal toenemen naarmate de officiële definities van 'armoede' en 'behoeftigheid' worden verhoogd. De Oorlog tegen Armoede heeft deze officiële definities verhoogd, wat automatisch leidde tot een toename van het aantal 'rechthebbenden'.
>
> 2. Het aantal armen dat in aanmerking komt voor een uitkering en daadwerkelijk een aanvraag indient, neemt toe naarmate de uitkeringen stijgen, zoals gebeurde in de jaren zestig. Wanneer bijstandsuitkeringen, inclusief gerelateerde voordelen zoals ziektekostenverzekering en voedselbonnen, concurreren met lage lonen, kiezen veel arme mensen rationeel voor bijstand. In New York, net als in andere grote steden, concurreren bijstandsuitkeringen niet alleen met lage lonen; ze overtreffen ze zelfs.
>
> De terughoudendheid van mensen die recht hebben op een uitkering om deze aan te vragen, zal afnemen. Deze terughoudendheid is vaak gebaseerd op trots, onwetendheid of angst. Wanneer er een georganiseerde campagne wordt opgezet om hen aan te moedigen zich aan te melden, zal dit effect hebben. In de jaren zestig werd zo'n campagne met succes gelanceerd door (a) verschillende gemeenschapsorganisaties die gesponsord en gefinancierd werden door het Office of Economic Opportunity, (b) de Welfare Rights Movement en (c) de sociale beroepsgroep. Deze beroepsgroep bestond nu uit afgestudeerden die het als hun morele plicht zagen om mensen te helpen bij het krijgen van een uitkering, in plaats van, zoals voorheen, hen te ondersteunen bij het afkomen van een uitkering. Bovendien droegen de rechtbanken bij door verschillende wettelijke obstakels, zoals verblijfsvereisten, te verwijderen.
>
> Op de een of andere manier lijkt de stijging van het aantal arme mensen in de bijstand, die bovendien meer genereuze uitkeringen ontvangen, dit land geen prettige plek om te wonen te maken. Zelfs voor de mensen in de bijstand lijkt hun situatie niet merkbaar beter dan toen ze arm waren en geen bijstand kregen. Er lijkt iets mis te zijn gegaan. Een liberaal en meelevend sociaal beleid heeft allerlei onverwachte en perverse gevolgen gehad.4

De mentaliteit die het beroep van maatschappelijk werk droeg, was heel anders - het had een libertarische inslag. Er waren twee hoofdprincipes: (a) alle hulp- en bijstandsuitkeringen zouden vrijwillig moeten zijn, uitgevoerd door particuliere instellingen in plaats van door verplichte belastingheffing van de overheid; en (b) het doel van geven moest zijn om de ontvanger zo snel mogelijk onafhankelijk en productief te maken. Logisch gezien volgt (b) uit (a), omdat geen enkele particuliere instantie over de vrijwel onbeperkte middelen beschikt die kunnen worden verzameld van de geduldige belastingbetaler. Aangezien particuliere fondsen strikt beperkt zijn, is er geen ruimte voor het idee van welzijns'rechten' als een onbeperkte en permanente claim op de productie van anderen. Een ander gevolg van de beperkte fondsen was dat sociale werkers zich realiseerden dat er geen ruimte was voor hulp aan mensen die slecht werkten, weigerden te werken of de hulp misbruikten; vandaar het concept van de 'verdienende' armen versus de 'onverdiende' armen. Zo rekende de 19e-eeuwse Engelse laissez-faire instelling, de Charity Organisation Society, onder de armen die het niet verdienden degenen die geen hulp nodig hadden, bedriegers en de man wiens toestand 'te wijten is aan ondoordachtheid of spaarzaamheid en waarbij er geen hoop is om hem in de toekomst onafhankelijk te maken van liefdadige hulp.'5

Hoewel het Engelse laissez-faire liberalisme over het algemeen de 'Poor Law' als overheidszorg accepteerde, was het standpunt dat dit een sterk ontmoedigend effect zou hebben. Er zouden niet alleen strikte regels moeten zijn om in aanmerking te komen voor hulp, maar de omstandigheden in de werkhuizen zouden ook zo onplezierig moeten zijn dat de opvang in het werkhuis eerder afschrikt dan aantrekkelijk maakt. Voor de 'armen die het niet verdienen', die verantwoordelijk zijn voor hun eigen situatie, kon misbruik van het hulpsysteem alleen worden tegengegaan door het zo onaantrekkelijk mogelijk te maken voor de aanvragers. Dit betekende doorgaans dat men aandrong op een arbeidstest of verblijf in een werkhuis.6

Hoewel een streng afschrikmiddel veel effectiever is dan een open aanbod en een preek over de 'rechten' van ontvangers, pleit het libertarische standpunt voor de volledige afschaffing van de overheidswelvaart. Het richt zich op particuliere liefdadigheid, waarbij de nadruk ligt op het zo snel mogelijk helpen van de 'verdienstelijke armen' naar onafhankelijkheid. Tot de Depressie in de jaren dertig was er immers weinig tot geen overheidswelzijn in de Verenigde Staten. En in die tijd, met een veel lagere algemene levensstandaard, werd er geen massale hongersnood op straat ervaren. Een uitstekend voorbeeld van een succesvol particulier welzijnsprogramma van tegenwoordig is dat van de mormoonse kerk, die drie miljoen leden telt. Dit opmerkelijke volk, dat te maken kreeg met armoede en vervolging, emigreerde in de 19e eeuw naar Utah en omringende staten. Zij tilde zichzelf naar een algemeen niveau van welvaart en rijkdom door middel van spaarzaamheid en hard werken. Slechts heel weinig mormonen ontvangen een uitkering; hen wordt geleerd om onafhankelijk en zelfredzaam te zijn en om de overheid zoveel mogelijk te vermijden. Mormonen zijn gelovig en hebben deze bewonderenswaardige waarden met succes geïnternaliseerd. Bovendien heeft de mormoonse kerk een uitgebreid particulier welzijnsplan voor haar leden, opnieuw met de focus om hen zo snel mogelijk naar onafhankelijkheid te begeleiden.

Let bijvoorbeeld op de volgende principes uit het welzijnsplan van de mormoonse kerk.

> Sinds de oprichting in 1830 heeft de kerk haar leden gestimuleerd om economische onafhankelijkheid op te bouwen en te behouden. Ze heeft spaarzaamheid bevorderd en de ontwikkeling van werkgelegenheid scheppende industrieën aangemoedigd. Daarnaast staat de kerk altijd klaar om behoeftige trouwe leden te helpen.

In 1936 ontwikkelde de mormoonse kerk een welzijnsprogramma.

> Kerkelijk Welzijnsplan. Een systeem dat de vloek van het nietsdoen moet uitbannen, het kwaad van de bijstand moet afschaffen en onafhankelijkheid, industrie, spaarzaamheid en zelfrespect weer op moet bouwen onder onze mensen. Het doel van de kerk is om mensen te helpen zichzelf te helpen. Werk moet het leidende principe zijn in het leven van onze kerkleden.

De maatschappelijk werkers van het programma zijn instructies gegeven om op deze manier te handelen:

> Trouw aan dit principe zullen welzijnswerkers de leden van de kerk aanmoedigen en ondersteunen om zoveel mogelijk voor hun eigen onderhoud te zorgen. Geen enkele ware Heilige der Laatste Dagen zal, zolang hij daartoe lichamelijk in staat is, vrijwillig de verantwoordelijkheid voor zijn eigen levensonderhoud van zich afschuiven. Zolang hij kan, zal hij onder inspiratie van de Almachtige en met zijn eigen arbeid in zijn levensbehoeften voorzien.

De directe doelstellingen van het welzijnsprogramma zijn:

> 1. Mensen die kunnen werken, ondersteunen bij het vinden van betaald werk.
>
> 2. Werkgelegenheid bieden binnen het welzijnsprogramma, daar waar mogelijk, voor degenen die niet in betaald werk kunnen worden geplaatst.
>
> 3. Het verkrijgen van middelen om de mensen in nood, voor wie de kerk verantwoordelijk is, te voorzien van de basisbehoeften.9

Voor zover mogelijk wordt dit programma uitgevoerd in kleine, lokale groepen:

> Gezinnen, buren, quorums, wijkgemeenschappen en andere organisatorische eenheden van de kerk kunnen het nuttig en wenselijk vinden om kleine groepen te vormen om elkaar te ondersteunen. Deze groepen kunnen gewassen planten en oogsten, voedsel verwerken, en voedsel, kleding en brandstof opslaan. Ook kunnen zij andere projecten uitvoeren die voor beide partijen voordelig zijn.10

Specifiek wordt de Mormoonse bisschoppen en priesterschapskorpsen gevraagd hun broeders te ondersteunen bij zelfhulp:

> In zijn tijdelijke rol beschouwt de bisschop elke kwetsbare persoon als een tijdelijk probleem. Hij zorgt voor deze persoon totdat hij zelf kan voorzien in zijn behoeften. Het priesterschapquorum ziet zijn behoeftige lid echter als een aanhoudend probleem. Dit is pas opgelost als zowel in de tijdelijke als in de geestelijke behoeften is voorzien. Een concreet voorbeeld: de bisschop biedt hulp aan een monteur of ambachtsman die tijdelijk zonder werk zit en in de problemen verkeert. Het priesterschapquorum helpt hem om een nieuwe baan te vinden en zorgt ervoor dat hij weer in zijn eigen onderhoud kan voorzien en actief kan zijn in zijn priesterlijke taken.

Concrete rehabilitatieactiviteiten voor leden in nood, die zijn toevertrouwd aan de priesterschapquorums, zijn onder meer:

> 1. Het helpen van quorumleden en hun gezinnen bij het vinden van een vaste baan. In sommige gevallen hebben quorums hun leden ondersteund bij het verkrijgen van betere functies door vakopleidingen, stages en andere mogelijkheden. 2. Het ondersteunen van quorumleden en hun gezinnen bij het starten van een eigen bedrijf.

Het belangrijkste doel van de Mormonse kerk is om werk te vinden voor degenen die hulp nodig hebben. Met dit doel voor ogen,

> Het vinden van geschikte banen als onderdeel van het Welzijnsprogramma is een belangrijke verantwoordelijkheid voor de leden van het priesterschapquorum. Zij, samen met de leden van de Relief Society, moeten altijd alert zijn op arbeidsmogelijkheden. Wanneer ieder lid van de welzijnscommissie zijn of haar taak goed uitvoert, zullen de meeste werklozen een betaalde baan kunnen vinden op groeps- of wijkniveau.11

Andere leden worden als zelfstandigen geholpen. De kerk kan ondersteuning bieden met een kleine lening, en het priesterschapquorum kan de terugbetaling vanuit haar fondsen garanderen. Mormonen die niet geholpen kunnen worden met het vinden van een baan of die niet als zelfstandige kunnen werken, moeten 'waar mogelijk productieve arbeid verrichten op het terrein van de kerk.' De kerk benadrukt dat de ontvanger zoveel mogelijk zelf aan de slag gaat.

> Het is belangrijk dat mensen die ondersteuning krijgen van het programma van de bisschoppen werken naar vermogen, zodat ze verdienen wat ze ontvangen. Werk van een individu in welzijnsprojecten moet als tijdelijk worden beschouwd in plaats van als een vast dienstverband. Het kan echter doorgaan zolang er hulp wordt geboden aan de persoon via het bisschoppelijk magazijnprogramma. Op deze manier wordt het geestelijk welzijn van mensen versterkt, terwijl in hun tijdelijke behoeften wordt voorzien. Bovendien zullen gevoelens van schroom verdwijnen.12

Als er geen ander werk beschikbaar is, kan de bisschop welzijnsontvangers aanwijzen om individuele leden te ondersteunen die hulp nodig hebben. De geholpen leden vergoeden de kerk volgens de geldende loontarieven. Over het algemeen wordt van de hulpontvangers verwacht dat zij in ruil voor de ontvangen steun zoveel mogelijk bijdragen aan het welzijnsprogramma van de kerk, hetzij in geld, producten of door hun arbeid.13

Als aanvulling op dit uitgebreide systeem van particuliere hulp, dat gericht is op het bevorderen van zelfstandigheid, moedigt de mormoonse kerk haar leden ten zeerste aan om geen beroep te doen op publieke bijstand. 'Plaatselijke kerkfunctionarissen worden verzocht het belang van zelfvoorzienendheid te benadrukken voor elk individu, elk gezin en elke kerkgemeenschap, zodat zij onafhankelijk blijven van openbare hulpverlening.' Daarnaast geldt: 'Het aanvragen en accepteren van directe publieke hulp leidt vaak tot de vloek van luiheid en bevordert andere nadelige gevolgen van bijstand. Het ondermijnt iemands onafhankelijkheid, inzet, spaarzaamheid en zelfrespect.'14

Er is geen beter voorbeeld dan de mormoonse kerk voor een particulier, vrijwillig, rationeel en individualistisch welzijnsprogramma. Als de overheid de welzijnszorg zou afschaffen, zou je verwachten dat in het hele land talloze van dit soort programma's voor wederzijdse hulp zouden ontstaan.

Het inspirerende voorbeeld van de mormoonse kerk laat zien dat de belangrijkste bepalende factor voor wie of hoeveel mensen in de bijstand terechtkomen, hun culturele en morele waarden zijn, en niet hun inkomensniveau. Een ander voorbeeld is de groep Albanees-Amerikanen in New York City.

Albanees-Amerikanen zijn een bijzonder arme groep, en in New York wonen ze bijna altijd in de sloppenwijken. Hoewel de statistieken beperkt zijn, ligt hun gemiddelde inkomen zonder twijfel lager dan dat van de beter bekende zwarte en Puerto Ricaanse gemeenschappen. Toch ontvangt geen enkele Albanees-Amerikaan bijstand. Waarom is dat? Vanwege hun trots en onafhankelijkheid. Zoals een van hun leiders het verwoordde: 'Albanezen bedelen niet. Voor Albanezen is het aannemen van een uitkering hetzelfde als bedelen op straat.'15

Naast de invloed van religie en etnische verschillen op waarden heeft professor Banfield in zijn uitstekende boek *The Unheavenly City* het belang aangetoond van wat hij de 'upper-class' en 'lower-class' culturen noemt. De definities van 'klasse' die Banfield hanteert, zijn niet strikt gebonden aan inkomens- of statusniveaus, maar vertonen wel aanzienlijke overlap met gangbare definities. Zijn opvattingen over klasse richten zich op de verschillende houdingen ten opzichte van het heden en de toekomst. Leden van de hogere en middenklasse zijn doorgaans toekomstgericht, doelbewust, rationeel en zelfdisciplinair. Mensen uit de lagere klasse daarentegen zijn vaak sterk op het heden gericht, impulsief, hedonistisch, doelloos en daarom minder geneigd om consistent een baan of carrière na te streven. Personen met de eerstgenoemde waarden hebben doorgaans hogere inkomens en betere banen, terwijl mensen uit de lagere klassen vaak arm zijn, werkloos of afhankelijk van bijstand. Kortom, het economische wel en wee van mensen is op de lange termijn eerder een kwestie van persoonlijke verantwoordelijkheid dan iets dat wordt bepaald door externe factoren, zoals liberalen vaak beweren. Banfield citeert Daniel Rosenblatt's bevindingen over het gebrek aan interesse in medische zorg, dat voortvloeit uit het 'algemene gebrek aan toekomstgerichtheid' onder de arme bevolking in steden:

> Regelmatige controles van auto's om beginnende defecten op te sporen maken bijvoorbeeld geen deel uit van het algemene waardesysteem van arme stadsbewoners. Op een vergelijkbare manier worden huishoudelijke voorwerpen vaak versleten en weggegooid, in plaats van dat ze in een vroeg stadium van slijtage worden gerepareerd. Kopen op afbetaling wordt gemakkelijk geaccepteerd, zonder dat men zich bewust is van de lengte van de betalingen.
>
> Het lichaam kan worden gezien als een soort voorwerp dat versleten raakt, maar niet gerepareerd hoeft te worden. Tanden en kiezen worden vaak zonder zorg achtergelaten; later is er vaak weinig interesse in een eventueel gratis kunstgebit. Kunstgebitten worden in elk geval maar weinige gebruikt. Corrigerende oogonderzoeken, zelfs voor mensen die al een bril dragen, worden vaak verwaarloosd, ongeacht de beschikbare faciliteiten van de kliniek. Het lijkt alsof de middenklasse het lichaam beschouwt als een machine die in optimale staat moet worden gehouden, bijvoorbeeld door middel van prothesen, revalidatie, cosmetische chirurgie of voortdurende behandelingen. Daarentegen zien mensen uit de lagere klasse het lichaam als iets met een beperkte levensduur: iets om van te genieten in de jeugd en dat, naarmate men ouder wordt en aftakelt, stoïcijns moet worden ondergaan en verdragen.16

Banfield merkt bovendien op dat het sterftecijfer onder mensen uit de lagere klassen al generaties lang veel hoger is dan dat van mensen uit de hogere klassen. Veel van dit verschil wordt niet veroorzaakt door armoede of lage inkomens, maar door de waarden en cultuur van mensen in de lagere klasse. Alcoholisme, drugsverslaving, doodslag en geslachtsziekten zijn opvallende en belangrijke doodsoorzaken in deze groep. Ook de kindersterfte is veel hoger onder de lagere klassen, soms tot wel twee tot drie keer hoger dan in de hogere groepen. Dat dit eerder te maken heeft met culturele waarden dan met het inkomensniveau, blijkt uit Banfields vergelijking van Ierse immigranten rond de eeuwwisseling met Russisch-Joodse immigranten in New York City. De Ierse immigranten waren destijds over het algemeen sterk op het heden gericht en vertoonden een 'lagere klasse'-mentaliteit. De Russische Joden, hoewel zij in overbevolkte huurkazernes woonden en waarschijnlijk een lager inkomensniveau hadden dan de Ieren, waren daarentegen ongewoon toekomstgericht, doelbewust en hadden waarden en een mentaliteit die meer met de 'upper class' in overeenstemming waren. Rond de eeuwwisseling was de levensverwachting van een Ierse immigrant op tienjarige leeftijd slechts 38 jaar, terwijl die van de Russisch-Joodse immigrant meer dan 50 jaar was. Daarnaast blijkt uit een studie van zeven steden tussen 1911 en 1916 dat de kindersterfte meer dan drie keer zo hoog was voor de laagste inkomensgroepen in vergelijking met de hoogste, terwijl de Joodse kindersterfte extreem laag was.17

Net als bij ziekte of sterfte, geldt dit ook voor werkloosheid. Deze staat uiteraard in nauw verband met zowel armoede als welzijn. Banfield verwijst naar het onderzoek van professor Michael J. Piore, die de essentiële 'ongeschiktheid voor werk' van veel langdurig werklozen met een laag inkomen aankaart. Piore ontdekte dat hun probleem niet zozeer lag in het vinden of aanleren van vaardigheden voor een vaste, goedbetaalde baan, maar vooral in het gebrek aan persoonlijke moed om aan zo'n baan vast te houden. Deze mensen hebben vaak een hoog absenteïsme, verlaten hun werk zonder opzegtermijn, zijn ongehoorzaam en stelen soms van hun werkgever.18 Verder blijkt uit onderzoek van Peter Doeringer naar de arbeidsmarkt in het getto van Boston in 1968 dat ongeveer 70 procent van de sollicitanten die door buurtwerkgelegenheidscentra waren doorverwezen, een baan aangeboden kreeg. Meer dan de helft van deze aanbiedingen werd echter afgewezen. Van de geaccepteerde sollicitanten behoudt slechts ongeveer 40 procent hun baan langer dan een maand. Doeringer concludeert: 'Een groot deel van de getgatewoordeloozen lijkt eerder het gevolg te zijn van onstabiliteit op het gebied van werk dan van schaarste op de arbeidsmarkt.'19

Het is zeer leerzaam om de opvattingen van professor Banfield en de linkse socioloog Alvin Gouldner over de afstandelijkheid van werkloze mannen uit de lagere klasse te vergelijken. Banfield stelt: 'Mannen die gewend zijn aan een leven op de hoek van de straat, aan vrouwen met een uitkering en aan 'hosselen', zijn zelden bereid om de saaie routines van een 'goede' baan te accepteren.'20 Over het gebrek aan succes van welzijnswerkers in het overtuigen van deze mannen om 'een leven van onverantwoordelijkheid, sensualiteit en losbandige agressie' achter zich te laten, merkt Gouldner op dat ze het aangeboden aanbod onaantrekkelijk vinden:

> 'Geef promiscue seks op, laat vrijelijke agressie en wilde spontaniteit achter je... en jij, of je kinderen, kunnen worden toegelaten tot de wereld van drie vierkante maaltijden per dag, van een middelbare school of misschien zelfs een universitaire opleiding, van rekeningen, zekere banen en respectabiliteit.'21

Het interessante is dat zowel Banfield als Gouldner, ondanks hun tegengestelde waarden, het eens zijn over de essentie van dit proces. Beide wijzen erop dat een groot deel van de hardnekkige werkloosheid onder de lagere klassen, en dus armoede, vrijwillig is vanuit de kant van de werklozen zelf.

De houding van Gouldner is kenmerkend voor veel hedendaagse liberalen en linkse denkers. Ze vinden het schandalig om, zelfs zonder dwang, 'burgerlijke waarden' of 'waarden van de middenklasse' op te dringen aan de unieke en 'natuurlijke' cultuur van de lagere klasse. Eerlijk is eerlijk; dat kan misschien zo zijn. Maar verwacht dan ook niet dat de hardwerkende bourgeoisie gedwongen wordt om de parasitaire waarden van luiheid en onverantwoordelijkheid te ondersteunen en te subsidiëren. Die waarden verafschuwen ze, en ze zijn duidelijk disfunctioneel voor het voortbestaan van elke samenleving. Als mensen 'spontaan' willen zijn, laat ze dat dan doen in hun eigen tijd en met hun eigen middelen. Laat ze de gevolgen van hun keuzes dragen. Het is niet eerlijk om de hardwerkende en 'niet-spontane' mensen te dwingen deze consequenties te accepteren via staatsdwang. Kortom, schaf het welvaartsstelsel af.

Als het grootste probleem van de armen in de lagere klassen het denken vanuit onverantwoordelijkheid is, en als er 'burgerlijke' toekomstgerichte waarden nodig zijn om mensen uit de bijstand en afhankelijkheid te helpen (zoals bij de Mormonen), dan moeten deze waarden in elk geval worden aangemoedigd en niet ontmoedigd in de samenleving. De links-liberale houding van maatschappelijk werkers ontmoedigt de armen direct door bijstand te presenteren als een 'recht' en een morele claim op productie. Bovendien zorgt de gemakkelijke toegang tot uitkeringen ervoor dat de ontvangers minder gemotiveerd zijn om te werken, waardoor onverantwoordelijkheid alleen maar toeneemt. Dit houdt de vicieuze cirkel van armoede en welzijn in stand. Zoals Banfield het verwoordt: 'Er is misschien geen betere manier om bekeerlingen te maken voor het huidige denken dan iedereen een royale uitkering te geven.'22

Over het algemeen hebben conservatieven in hun kritiek op het socialezekerheidsstelsel voornamelijk gefocust op het ethische en morele kwaad van het dwangmatig ontnemen van belastinggeld om nietsnutten te ondersteunen. Linkse critici daarentegen hebben de nadruk gelegd op de demoralisatie van sociale 'klanten' door hun afhankelijkheid van de vrijgevigheid van de staat en zijn bureaucratie. In wezen hebben beide groepen een punt; er is geen tegenstelling tussen hun standpunten. We hebben gezien dat vrijwillige programma's, zoals die van de Mormoonse kerk, zich goed bewust zijn van dit probleem. Vroegere critici van de bijstand die pleitten voor laissez-faire waren zich ook bewust van de gevolgen van demoralisatie, naast de dwang die op degenen werd uitgeoefend die voor de bijstand moesten betalen.

Zo verklaarde de negentiende-eeuwse Engelse voorstander van laissez-faire, Thomas Mackay, dat hervorming van het welzijnsbeleid 'bestaat uit een herschepping en ontwikkeling van de kunst van onafhankelijkheid.' Hij pleitte voor 'niet meer filantropie, maar veeleer voor meer respect voor de waardigheid van het menselijk leven en meer geloof in het vermogen van mensen om hun eigen welzijn te bewerkstelligen.' Mackay uitte zijn minachting voor de voorstanders van meer welzijn, over...

> de plaatsvervangende filantroop die, in een roekeloze race om goedkope populariteit, het belastingtarief dat van zijn buren wordt afgenomen, gebruikt om de kansen op struikelen te vergroten voor de ... menigte die maar al te graag in afhankelijkheid vervalt.23

Mackay voegde hieraan toe dat de hervorming van het welzijnsbeleid moest bestaan uit een herinterpretatie en ontwikkeling van de kunst van onafhankelijkheid. Hij pleitte voor meer respect voor de waardigheid van het menselijk leven en voor geloof in het vermogen van mensen om zelf voor hun welzijn te zorgen. Bovendien had hij een hekel aan voorstanders van meer welzijn. Hij sprak schamper over de plaatsvervangende filantroop, die in een onbezonnen poging tot goedkope populariteit het belastingtarief dat zijn buren wordt opgelegd, gebruikt om het aantal struikelkansen voor de ... menigte die maar al te graag in afhankelijkheid vervalt, te vergroten.

> De 'wettelijke bevoordeling van de armoede' die het socialezekerheidsstelsel met zich meebrengt, 'introduceert een zeer gevaarlijke en soms demoraliserende invloed in onze sociale regelingen. De werkelijke noodzaak ervan is geenszins bewezen. De schijnbare noodzaak komt voornamelijk voort uit het feit dat het systeem zijn eigen afhankelijke bevolking heeft gecreëerd.'24

Uitvoerig over het thema afhankelijkheid merkte Mackay op dat

> Het bitterste aspect van de nood bij de armen komt niet alleen voort uit armoede, maar ook uit het gevoel van afhankelijkheid dat inherent is aan elke vorm van openbare hulp. Dit gevoel kan niet worden weggenomen; het wordt zelfs versterkt door liberale maatregelen van openbare hulp.¹

Mackay concludeerde dat het bitterste aspect van de nood onder de armen niet alleen voortkomt uit armoede, maar ook uit het gevoel van afhankelijkheid dat bij elke vorm van openbare hulp hoort. Dit gevoel is niet te verhelpen; het wordt zelfs versterkt door liberale maatregelen voor sociale bijstand.

> De enige manier waarop de wetgever of de beheerder het pauperisme kan aanpakken, is door de wettelijke uitkeringen voor paupers af te schaffen of te beperken. Er is geen twijfel over; het land kan net zoveel paupers hebben als het kan betalen. Schaf die toelage af of beperk deze. Wanneer dat gebeurt, komen er nieuwe instanties in beeld. Hierdoor wordt het natuurlijke vermogen van de mens om onafhankelijk te zijn, evenals de natuurlijke banden van relatie en vriendschap, gestimuleerd. Onder deze noemer plaats ik particuliere liefdadigheid, in tegenstelling tot openbare liefdadigheid.¹

De Charity Organisation Society, de belangrijkste particuliere liefdadigheidsinstelling van Engeland aan het eind van de negentiende eeuw, werkte precies volgens het principe dat hulp zelfhulp stimuleert. Zoals de historicus Mowat over de Society opmerkt:

> De C.O.S. belichaamde een idee van liefdadigheid dat beweerde de verdeeldheid in de samenleving te overbruggen, armoede te bestrijden en een gelukkige, zelfredzame gemeenschap te creëren. Men geloofde dat het ernstigste probleem van armoede de degradatie van het karakter van de arme man of vrouw was. Ongerichte liefdadigheid verergerde de situatie alleen maar; het leidde tot demoralisatie. Echte liefdadigheid vereiste daarentegen vriendschap en een doordachte aanpak. Het soort hulp dat het zelfrespect van mensen zou herstellen en hen in staat zou stellen om voor henzelf en hun gezinnen te zorgen.¹

Een van de grimmigste gevolgen van de bijstand is misschien wel dat het zelfhulp actief ontmoedigt. Dit gebeurt doordat de financiële prikkel voor herstel wordt weggenomen. Er wordt geschat dat elke dollar die gehandicapten investeren in hun eigen revalidatie hen gemiddeld tussen de 10 en 17 dollar oplevert in de contante waarde van hun toekomstige inkomsten. Maar deze stimulans wordt ondermijnd door het feit dat ze, wanneer ze revalideren, hun bijstandsuitkering, invaliditeitsuitkering van de Sociale Zekerheid en arbeidsongevallenvergoeding verliezen. Daardoor besluiten veel gehandicapten om niet te investeren in hun eigen revalidatie.¹ Bovendien zijn veel mensen inmiddels bekend met de verlammende effecten van het socialezekerheidsstelsel. Dit stelsel stopt de betalingen zodra de ontvanger, in schril contrast met particuliere verzekeringsfondsen, zo dapper is om na zijn 62e te gaan werken en een inkomen te verwerven.¹

In deze tijd, waarin de meeste mensen met argusogen naar de bevolkingsgroei kijken, hebben maar weinig antipopulatieactivisten aandacht besteed aan een ander nadelig effect van het welvaartssysteem. Omdat bijstandsgezinnen betaald worden op basis van het aantal kinderen, levert het systeem een belangrijke subsidie voor de opvoeding van meer kinderen. Bovendien zijn het vooral de mensen die het zich het minst kunnen veroorloven, die gestimuleerd worden om meer kinderen te krijgen. Het gevolg hiervan is dat hun afhankelijkheid van bijstand aanhoudt, en er in feite generaties ontstaan die permanent afhankelijk zijn van deze hulp.

De laatste jaren is er veel gesproken over de oproep aan de overheid om kinderdagverblijven beschikbaar te stellen voor de opvang van kinderen van werkende moeders. Er wordt gesteld dat de markt er niet in geslaagd is om deze broodnodige service te bieden.

Aangezien het de taak van de markt is om in dringende consumentenbehoeften te voorzien, rijst de vraag waarom de markt in dit geval lijkt te falen. Het antwoord ligt in de uitgebreide en kostbare wettelijke beperkingen die de overheid aan het aanbod van kinderopvang heeft opgelegd. In feite is het volkomen legaal om je kinderen bij een vriend of familielid onder te brengen, ongeacht wie die persoon is of hoe zijn appartement eruitziet. Ook kun je een buurman inhuren om op één of twee kinderen te passen. Zodra die vriend of buurman echter een iets grotere onderneming opstart, treden de overheidsregels in werking. De staat dringt er over het algemeen op aan dat soortgelijke kinderdagverblijven een vergunning verkrijgen. Daarbij wordt een vergunning vaak alleen verleend als er altijd geregistreerde verpleegkundigen aanwezig zijn, er minimaal speeltuinfaciliteiten zijn en de faciliteit aan bepaalde grootte-eisen voldoet. Bovendien zijn er talloze andere absurde en dure eisen die de overheid niet oplegt aan vrienden, familieleden en buren -- of zelfs aan moeders zelf. Door deze beperkingen te verwijderen, zal de markt zich aanpassen en voldoen aan de vraag.

De dichter Ned O'Gorman runt al dertien jaar met beperkte middelen een succesvol, particulier gefinancierd kinderdagverblijf in Harlem. Toch dreigt hij failliet te gaan door de bureaucratische regels van de gemeente New York. Hoewel de stad de 'toewijding en effectiviteit' van O'Gormans centrum, The Storefront, erkent, dreigt zij met boetes en zelfs met de gedwongen sluiting van het centrum. Dit gebeurt tenzij er een door de staat gecertificeerde maatschappelijk werker aanwezig is wanneer er vijf of meer kinderen zijn. Zoals O'Gorman verontwaardigd opmerkt:

> Waarom zou ik in hemelsnaam iemand moeten aannemen die een diploma heeft waarop staat dat hij sociaal werk heeft gestudeerd en gekwalificeerd is om een kinderdagverblijf te leiden? Als ik na dertien jaar ervaring in Harlem niet gekwalificeerd ben, wie is dat dan wel?29

Het voorbeeld van de kinderopvang illustreert een belangrijke waarheid over de markt: als er een tekort lijkt te zijn aan aanbod dat niet aan een duidelijke vraag voldoet, kijk dan naar de overheid als mogelijke oorzaak van het probleem. Geef de markt de ruimte en er zal geen gebrek zijn aan kinderdagverblijven, net zoals er ook geen tekort is aan motels, wasmachines, tv-toestellen of andere alledaagse benodigdheden.

## LASTEN EN SUBSIDIES VAN DE WELVAARTSSTAAT

Helpt de moderne welvaartsstaat de armen echt? Het gangbare idee, dat de welvaartsstaat heeft bevorderd en in stand gehouden, is dat deze inkomen en rijkdom herverdeelt van de rijken naar de armen. Het progressieve belastingsysteem haalt geld weg bij de rijken, terwijl verschillende sociale voorzieningen en andere diensten dat geld onder de armen verdelen. Maar zelfs liberalen, de grootste voorstanders van de welvaartsstaat, beginnen te beseffen dat elk aspect van dit idee slechts een gekoesterde mythe is. Overheidscontracten, vooral die van het leger, sluizen belastinggeld naar bevoorrechte bedrijven en goedbetaalde industriële arbeiders. Minimumloonwetten leiden op tragische wijze tot werkloosheid, vooral onder de armste en laagst opgeleide werknemers in het Zuiden, onder zwarte tieners in de getto's en onder beroepsgehandicapten. Een minimumloon garandeert immers niet dat iemand werk heeft; het verbiedt slechts, via de wet, dat iemand kan worden aangenomen voor een loon dat lager is dan het vastgestelde minimum. Hierdoor ontstaat er werkloosheid. Economen hebben aangetoond dat verhogingen van het federale minimumloon de welbekende werkgelegenheidskloof tussen zwarte en blanke tieners hebben vergroot en de werkloosheid onder zwarte mannen hebben opgestuwd van ongeveer 8 procent aan het begin van de naoorlogse periode naar meer dan 35 procent nu. De werkloosheid onder zwarte jongeren is daardoor veel ernstiger dan de massale werkloosheid in de jaren dertig (20-25 procent).30

We hebben al gezien hoe het hoger onderwijs door de staat inkomen herverdeelt van armere naar rijkere burgers. Talloze vergunningsrestricties van de overheid, die in verschillende beroepen zijn doorgevoerd, sluiten armere en minder geschoolde arbeiders uit van deze banen. Het wordt steeds duidelijker dat stadsvernieuwingsprogramma's, die zogenaamd bedoeld zijn om de sloppenwijken van de armen te helpen, in feite hun huizen afbreken. Hierdoor worden de armen gedwongen om onder nog slechtere omstandigheden te wonen, ten voordele van rijkere gesubsidieerde huurders, bouwvakbonden, bevoorrechte projectontwikkelaars en commerciële belangen in de binnenstad. Vakbonden, ooit geliefd bij liberalen, worden nu vaak bekritiseerd omdat zij hun privileges van de overheid gebruiken om armere arbeiders en leden van minderheidsgroepen uit te sluiten. De steunmaatregelen in de landbouw, die door de federale overheid steeds verder worden verhoogd, belasten de belastingbetaler en drijven de voedselprijzen op. Dit benadeelt vooral arme consumenten en helpt niet de arme boeren, maar juist de rijke boeren die een groot deel van het land bezitten. Omdat boeren betaald worden per pond of per bushel product, profiteert het steunprogramma vooral de welgestelde boeren. Vaak worden boeren zelfs betaald om niet te produceren, wat leidt tot aanzienlijke werkloosheid onder het armste segment van de boerenbevolking, zoals pachters en werknemers op de boerderij. Bepalingen in bestemmingswetten in de groeiende buitenwijken van de Verenigde Staten dienen om de armste burgers uit te sluiten, vaak zwarte mensen die proberen te verhuizen van de binnensteden naar de buitenwijken waar de werkgelegenheid toeneemt. De U.S. Postal Service hanteert hoge monopolietarieven op eersteklaspost, een kostenpost die door het grote publiek wordt gedragen om de distributie van kranten en tijdschriften te subsidiëren. De FHA subsidieert hypotheken voor welgestelde huiseigenaren. Het Federal Bureau of Reclamation biedt irrigatiewater aan rijke boeren in het Westen, waardoor stedelijke armen geen toegang meer hebben tot water en gedwongen zijn hogere waterlasten te betalen. De Rural Electrification Administration en de Tennessee Valley Authority subsidiëren de elektriciteitsvoorziening voor vermogende boeren, voorsteden en bedrijven. Zoals professor Brozen sardonisch opmerkt:

> Elektriciteit voor armlastige bedrijven zoals de Aluminum Corporation of America en de DuPont Company wordt gesubsidieerd door de belastingvrije status van de Tennessee Valley Authority. Dit betekent dat 27 procent van de elektriciteitsprijs wordt gebruikt om de belastingen te dekken die aan particuliere nutsbedrijven worden opgelegd.31

De overheidsregulering leidt tot monopolies en kartelvorming in grote delen van de industrie. Dit resulteert in hogere prijzen voor consumenten en beperkt de productie, alternatieven en verbeteringen van producten. Denk bijvoorbeeld aan de regulering van de spoorwegen, openbare nutsbedrijven, luchtvaartmaatschappijen en wetten met betrekking tot olieprijzen. De Civil Aeronautics Board kent vliegroutes toe aan bevoorrechte maatschappijen en houdt kleinere concurrenten buiten de deur, of drijft ze zelfs uit de markt. Staats- en federale wetten over olieprijzen creëren strikte productiebeperkingen voor ruwe olie, waardoor de olieprijzen stijgen, die bovendien nog verder worden opgedreven door importbeperkingen. Overal in het land verstrekt de overheid absolute monopolieposities aan gas-, elektriciteits- en telefoonbedrijven. Dit beschermt deze bedrijven tegen concurrentie en stelt de overheid in staat om hun tarieven te bepalen, zodat zij een gegarandeerde winst behalen. Het verhaal is overal hetzelfde: een systematische afroming van de massa door de 'verzorgingsstaat'.32

De meeste mensen geloven dat het Amerikaanse belastingsysteem in principe de rijken veel zwaarder belast dan de armen. Daarom wordt het vaak gezien als een manier om inkomen te herverdelen van hogere naar lagere inkomensklassen. (Er zijn natuurlijk andere vormen van herverdeling, zoals de belastingbetaler die betaalt voor bedrijven als Lockheed of General Dynamics.) Maar zelfs de federale inkomstenbelasting, waarvan velen denken dat deze 'progressief' is---met een hogere belasting voor de rijken dan voor de armen, en de middenklasse daartussen---werkt niet echt zo als we naar andere aspecten van deze belasting kijken. Neem bijvoorbeeld de belasting op sociale zekerheid. Deze belasting is duidelijk 'regressief', omdat zij vooral de armen en de middenklasse treft. Iemand met een basisinkomen van $8.000 betaalt dezelfde sociale zekerheid belasting---die elk jaar toeneemt---als iemand die $1.000.000 per jaar verdient. Bovendien betalen vermogenswinsten, die meestal aan rijke aandeelhouders en eigenaren van onroerend goed toekomen, veel minder belasting dan reguliere inkomsten. Private trusts en stichtingen zijn vrijgesteld van belasting, en rente die wordt verdiend op staats- en gemeentelijke obligaties is ook vrijgesteld van de federale inkomstenbelasting. Hieronder volgen de schattingen van het percentage van het inkomen dat door elke 'inkomensklasse' aan federale belastingen wordt betaald:

__________________________________________________________

1965

+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| **Inkomen Klassen** Elektriciteit voor zwakkere bedrijven zoals de Aluminum Corporation of America en de DuPont Company krijgt subsidie door de belastingvrije status van de Tennessee Valley Authority. Dit betekent dat 27 procent van de elektriciteitsprijs gaat naar de belastingen die aan particuliere nutsbedrijven moeten worden betaald.31 De overheidsregulering leidt tot monopolies en kartelvorming in grote delen van de industrie. Dit resulteert in hogere prijzen voor consumenten en beperkt de productie, alternatieven en verbeteringen van producten. Denk bijvoorbeeld aan de regulering van de spoorwegen, openbare nutsbedrijven, luchtvaartmaatschappijen en wetten met betrekking tot olieprijzen. De Civil Aeronautics Board kent vliegroutes toe aan bevoorrechte maatschappijen en houdt kleinere concurrenten buiten de deur of drijft ze zelfs uit de markt. Staats- en federale wetten over olieprijzen creëren strikte productiebeperkingen voor ruwe olie, waardoor de olieprijzen stijgen, terwijl importbeperkingen de prijzen nog verder verhogen. Overal in het land verleent de overheid gas-, elektriciteits- en telefoonbedrijven een absoluut monopolie. Dit beschermt deze bedrijven tegen concurrentie en stelt de overheid in staat om hun tarieven te bepalen, zodat zij gegarandeerd winst maken. Het verhaal is overal hetzelfde: een systematische afroming van de massa door de 'verzorgingsstaat'.32 De meeste mensen denken dat het Amerikaanse belastingsysteem in principe de rijken zwaarder belast dan de armen. Daarom wordt het vaak gezien als een manier om inkomen te herverdelen van hogere naar lagere inkomensklassen. (Er zijn natuurlijk ook andere vormen van herverdeling, zoals de belastingbetaler die betaalt voor Lockheed of General Dynamics.) Maar zelfs de federale inkomstenbelasting, waarvan velen menen dat deze 'progressief' is---in de zin dat de rijken meer betalen dan de armen, met de middenklasse er tussenin---werkt niet altijd zo als we andere aspecten van deze belasting in overweging nemen. Neem bijvoorbeeld de belasting op sociale zekerheid. Deze belasting is duidelijk 'regressief', omdat ze vooral de armen en de middenklasse treft. Iemand met een basisinkomen van $8.000 betaalt evenveel sociale zekerheid belasting---die elk jaar toeneemt---als iemand die $1.000.000 per jaar verdient. Daarnaast betalen vermogenswinsten, die doorgaans naar rijke aandeelhouders en eigenaren van onroerend goed gaan, veel minder belasting dan reguliere inkomsten. Private trusts en stichtingen zijn vrijgesteld van belasting, en rente op staats- en gemeentelijke obligaties is ook vrijgesteld van de federale inkomstenbelasting. Hieronder volgen schattingen van het percentage van het inkomen dat door elke 'inkomensklasse' aan federale belastingen wordt betaald: | Percentage van het inkomen dat aan federale belasting wordt betaald |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |                                                                     |
| Onder de $2.000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | 19                                                                  |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |                                                                     |
| $2.000--$4.000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | 16                                                                  |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |                                                                     |
| **Inkomen Klassen** $4.000--$6.000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | 17                                                                  |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |                                                                     |
| $6.000--$8.000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | 17                                                                  |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |                                                                     |
| $8.000--$10.000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | 18                                                                  |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |                                                                     |
| $10.000--$15.000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | 19                                                                  |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |                                                                     |
| Boven de €15.000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | 32                                                                  |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+

> Gemiddeld 22

__________________________________________________________

Als federale belastingen nauwelijks 'progressief' zijn, dan is de impact van staats- en lokale belastingen bijna sterk regressief. Eigendomsbelastingen zijn (a) proportioneel, (b) alleen van toepassing op eigenaren van onroerend goed en (c) afhankelijk van de politieke wensen van lokale taxateurs.

Omzetbelasting en accijnzen raken de armen het zwaarst. Hierna vind je een schatting van het percentage van het totale inkomen dat door staats- en lokale belastingen wordt onttrokken:

__________________________________________________________

1965

+----------------------------------+--------------------------------------------------------------------------------+
| Inkomen Klassen                  | Percentage van het inkomen dat aan staats- en lokale belastingen wordt besteed |
|                                  |                                                                                |
| Onder de $2.000                 | 25                                                                             |
|                                  |                                                                                |
| Tussen de $2.000 en $4.000     | 11                                                                             |
|                                  |                                                                                |
| Tussen de $4.000 en $6.000     | 10                                                                             |
|                                  |                                                                                |
| Tussen de $6.000 en $8.000     | 9                                                                              |
|                                  |                                                                                |
| Tussen de $8.000 en $10.000    | 9                                                                              |
|                                  |                                                                                |
| Tussen de $10.000 en $15.000   | 9                                                                              |
|                                  |                                                                                |
| Boven de $15.000                | 7                                                                              |
+----------------------------------+--------------------------------------------------------------------------------+

> GEMIDDELDE 9

__________________________________________________________

Hieronder staan de samengevoegde schattingen van de totale impact van belastingen --- federaal, staats- en lokaal --- op verschillende inkomensklassen:

__________________________________________________________

1965

+----------------------------------+----------------------------------------------------------+
| Inkomstengroepen                 | Percentage van het inkomen dat aan belastingen gaat: 33% |
|                                  |                                                          |
| Onder de $2.000                 | 44                                                       |
|                                  |                                                          |
| Tussen de $2.000 en $4.000     | 27                                                       |
|                                  |                                                          |
| Tussen de $4.000 en $6.000     | 27                                                       |
|                                  |                                                          |
| Tussen de $6.000 en $8.000     | 26                                                       |
|                                  |                                                          |
| Tussen de $8.000 en $10.000    | 27                                                       |
|                                  |                                                          |
| Tussen de $10.000 en $15.000   | 27                                                       |
|                                  |                                                          |
| Boven de $15.000                | 38                                                       |
+----------------------------------+----------------------------------------------------------+

> GEMIDDELD 31

__________________________________________________________

Nog recentere schattingen (1968) van de totale impact van belastingen op alle overheidsniveaus bevestigen dit ruimschoots. Ze tonen ook een veel grotere relatieve stijging aan wat betreft de belastingdruk op de laagste inkomensgroepen in de afgelopen drie jaar.

__________________________________________________________

1968

+----------------------------------+----------------------------------------------------------+
| Inkomstengroepen                 | Percentage van het inkomen dat aan belastingen gaat: 34% |
|                                  |                                                          |
| Onder de $2.000                 | 50                                                       |
|                                  |                                                          |
| $2.000--$4.000                 | 35                                                       |
|                                  |                                                          |
| $4.000--$6.000                 | 31                                                       |
|                                  |                                                          |
| $6.000--$8.000                 | 30                                                       |
|                                  |                                                          |
| $8.000--$10.000                | 29                                                       |
|                                  |                                                          |
| $10.000--$15.000               | 30                                                       |
|                                  |                                                          |
| $15.000--$25.000               | 30                                                       |
|                                  |                                                          |
| $25.000--$50.000               | 33                                                       |
|                                  |                                                          |
| Boven de $50.000                | 45                                                       |
+----------------------------------+----------------------------------------------------------+

_________________________________________________________

Veel economen proberen de impact van deze vaak misleidende cijfers te nuanceren. Ze stellen dat mensen in de categorie 'onder de $2.000' bijvoorbeeld meer ontvangen aan uitkeringen en andere 'transferbetalingen' dan ze aan belastingen betalen. Maar dit negeert het belangrijke feit dat binnen elke categorie niet iedereen zowel ontvanger van uitkeringen als belastingbetaler is. De belastingbetalers in de laatste groep worden zwaar belast om de eerste groep te subsidiëren. Kortom, de armen en de middenklasse betalen voor de gesubsidieerde volkshuisvesting van andere arme en middeninkomensgroepen. Vooral de werkende armen moeten een aanzienlijk bedrag bijdragen aan de subsidies voor de sociaal zwakkeren.

Er is genoeg inkomensherverdeling in dit land: naar Lockheed, naar uitkeringstrekkers, noem maar op. Maar de 'rijken' worden niet belast om voor de 'armen' te betalen. De herverdeling gebeurt binnen de inkomensgroepen; sommige armen worden gedwongen om voor andere armen bij te dragen.

Andere belastinginschattingen bevestigen dit verontrustende beeld. De Tax Foundation schat bijvoorbeeld dat federale, staats- en lokale belastingen 34 procent van het totale inkomen innemen van mensen die minder dan $3.000 per jaar verdienen.

Het doel van deze discussie is niet om te pleiten voor een 'echt' progressieve inkomstenbelastingstructuur of om de rijken uit te persen. Het gaat erom te benadrukken dat de moderne welvaartsstaat, die vaak wordt geprezen als een manier om de rijken te laten bijdragen aan de armen, dit in werkelijkheid niet doet. Integendeel, het te veel belasten van de rijken zou rampzalige gevolgen hebben, niet alleen voor hen, maar ook voor de armen en de middenklasse. De rijken dragen namelijk in verhouding meer bij in de vorm van spaargeld, investeringskapitaal en ondernemerschap. Dit draagt bij aan technologische innovaties en heeft ervoor gezorgd dat de Verenigde Staten de hoogste levensstandaard heeft bereikt voor de meeste mensen in de geschiedenis. De rijken onder druk zetten zou niet alleen diep immoreel zijn, maar ook deze belangrijke kwaliteiten zoals spaarzaamheid, zakelijke vooruitziendheid en investeringen bestraffen, die onze opmerkelijke levensstandaard mogelijk hebben gemaakt. Het zou als het doden van de kip die de gouden eieren legt, zijn.

## Wat kan de overheid doen?

Wat kan de overheid doen om de armen te helpen? Het enige juiste antwoord is ook het libertarische antwoord: stap opzij. Wanneer de overheid de productieve energie van alle bevolkingsgroepen---rijk, middenklasse en arm---ruimte geeft, zal dat leiden tot een aanzienlijke verbetering van het welzijn en de levensstandaard van iedereen. Dit geldt vooral voor de armen, die zogenaamd geholpen worden door de zogenaamde 'verzorgingsstaat'.

Er zijn vier belangrijke manieren waarop de overheid het Amerikaanse volk meer ruimte kan geven. Ten eerste kan ze alle belastingen afschaffen of op zijn minst sterk verlagen. Deze belastingen remmen namelijk productieve energie, sparen, investeren en technologische vooruitgang. Het creëren van banen en het verhogen van lonen, als gevolg van het afschaffen van deze belastingen, zou vooral de lagere inkomensgroepen ten goede komen. Zoals professor Brozen opmerkt:

> Met minder pogingen om de staatsmacht in te zetten tegen inkomensongelijkheid, zou die ongelijkheid sneller afnemen. Lage lonen zouden sneller stijgen door een hoger niveau van sparen en kapitaalvorming, waardoor de ongelijkheid zou verminderen naarmate het inkomen van de werknemers toeneemt.36

De beste manier om de armen te helpen, is door de belastingen te verlagen en sparen, investeren en het creëren van banen alle ruimte te geven. Zoals Dr. F.A. Harper jaren geleden al aangaf, zijn productieve investeringen de 'grootste economische liefdadigheid.' Harper schreef:

> Volgens de ene opvatting is het delen van een boterham de manier om liefdadigheid te bedrijven. De andere opvatting pleit voor het besparen en het gebruik van middelen om extra broden te produceren. Dit wordt gezien als de grootste economische liefdadigheid.
>
> De twee visies staan lijnrecht tegenover elkaar omdat de methoden elkaar uitsluiten in het gebruik van iemands tijd en middelen bij alle dagelijkse keuzes.
>
> Het verschil in opvatting komt voort uit uiteenlopende ideeën over de aard van de economie. De eerste visie gaat ervan uit dat het totaal aan economische goederen constant is. De tweede visie gelooft dat er een mogelijkheid is om de productie uit te breiden zonder een noodzakelijke limiet.
>
> Het verschil tussen de twee visies komt overeen met het verschil tussen een twee- en een driedimensionaal perspectief op productie. De tweedimensionale omvang is op elk moment van de tijd vastgelegd, terwijl de derde dimensie -- en daarmee de totale omvang -- onbeperkt kan worden uitgebreid door middel van besparingen en middelen.
>
> De hele geschiedenis van de mensheid weerspreekt het idee dat er een vast totaal aan economische goederen bestaat. De geschiedenis laat zien dat besparingen en de uitbreiding van gereedschappen de enige manieren zijn om een significante toename te realiseren.37

De libertarische schrijfster Isabel Paterson verwoordde het prachtig:

> Wat betreft de particuliere filantroop en de particuliere kapitalist die als zodanig opereert, laten we het voorbeeld nemen van een echt behoeftige man die niet arbeidsongeschikt is. Stel dat de filantroop hem voedsel, kleding en onderdak biedt. Nadat hij daarvan gebruik heeft gemaakt, is de man weer precies waar hij eerder was, met mogelijk de gewoonte van afhankelijkheid als extra bagage. Maar stel je voor dat iemand zonder welwillende motieven, die gewoon om zijn eigen redenen werk wil hebben, de behoeftige man inhuurt voor een loon. In dit geval heeft de werkgever geen goede daad verricht, maar de situatie van de werknemer is wel degelijk veranderd. Wat is dan het essentiële verschil tussen deze twee handelingen?
>
> De niet-filantropische werkgever heeft de man die hij in dienst heeft genomen, weer in de productielijn geïntegreerd, in het grotere energiecircuit. De filantroop daarentegen kan alleen maar energie omleiden, wat betekent dat er geen mogelijkheid is voor de man om terug te keren naar de productie. Hierdoor is de kans kleiner dat de ontvanger van zijn goedheid daadwerkelijk werk vindt.
>
> Als we de volledige rol van oprechte filantropen door de eeuwen heen onder de loep nemen, blijkt dat ze samen met hun strikt filantropische activiteiten de mensheid nooit meer dan een tiende van het voordeel hebben geboden dan de inspanningen van Thomas Alva Edison, die doorgaans uit eigenbelang verricht werden. Dit geldt des te meer voor de grotere geesten die de wetenschappelijke principes ontwikkelden die Edison toepaste. Ontelbare speculatieve denkers, uitvinders en organisatoren hebben bijgedragen aan het comfort, de gezondheid en het geluk van hun medemensen, en dat terwijl dat niet hun oorspronkelijke doel was.38

Ten tweede zou, als gevolg van een drastische verlaging of zelfs afschaffing van belastingen, een gelijkwaardige vermindering van de overheidsuitgaven plaatsvinden. Schaarse economische middelen zouden niet langer worden verspild aan onproductieve uitgaven. Dit omvat bijvoorbeeld miljarden voor het ruimteprogramma, openbare werken of het militair-industriële complex. In plaats daarvan zouden deze middelen beschikbaar komen voor de productie van goederen en diensten waar de consument naar verlangt. De toenemende beschikbaarheid van goederen en diensten zou leiden tot nieuwe en betere producten voor consumenten, en dat tegen veel lagere prijzen. We zouden niet langer te lijden hebben onder de inefficiënties en de schade aan de productiviteit die voortkomen uit overheidssubsidies en -contracten. Bovendien zouden veel wetenschappers en ingenieurs, die nu bezig zijn met verspilling in militair onderzoek en andere overheidsuitgaven, kunnen overstappen naar vreedzame en productieve activiteiten en innovaties die de consumenten ten goede komen.39

Ten derde, als de overheid zou stoppen met de vele manieren waarop ze de armen belast om de rijken te subsidiëren, zoals eerder genoemd (bijvoorbeeld hoger onderwijs, landbouwsubsidies, irrigatie, Lockheed, enzovoort), zou ze de armen daadwerkelijk helpen. Door te stoppen met het belasten van de armen zou de overheid hun productieve activiteiten ontlasten.

Ten slotte is een van de belangrijkste manieren waarop de overheid de armen kan helpen, het wegnemen van haar eigen directe obstakels voor hun productieve energie. Minimumloonwetten leiden ervoor dat de armste en minst productieve leden van de bevolking werkloos worden. De voordelen die de overheid verleent aan vakbonden maken het voor de armste arbeiders en mensen uit minderheidsgroepen moeilijker om toegang te krijgen tot productief en goedbetaald werk. Daarnaast beletten vergunningseisen, het verbod op gokken en andere overheidsbeperkingen de armen om kleine bedrijfjes te starten en zelf werkgelegenheid te creëren. Daarom heeft de overheid overal zware beperkingen opgelegd aan de handel, variërend van een algeheel verbod tot hoge licentiekosten. Venten was ooit de klassieke manier voor immigranten, die arm waren en geen kapitaal hadden, om ondernemers te worden en uiteindelijk grote zakenlieden te ontwikkelen. Maar deze weg is nu afgesloten, grotendeels om monopolievoordelen te creëren voor de winkels in elke stad, die vrezen winst te verliezen door de stevige concurrentie van straatventers.

Typerend voor de manier waarop de overheid de productieve activiteiten van de armen heeft gefrustreerd, is het verhaal van neurochirurg Dr. Thomas Matthew. Hij is de oprichter van de zelfhulporganisatie voor zwarten, NEGRO, die obligaties uitgeeft om haar activiteiten te bekostigen. Halverwege de jaren zestig richtte Dr. Matthew, ondanks tegenwerkingen van de New Yorkse overheid, een succesvol interraciaal ziekenhuis op in de zwarte wijk Jamaica, Queens. Al snel ontdekte hij echter dat het openbaar vervoer in Jamaica zo slecht was dat het vervoer voor patiënten en personeel absoluut onvoldoende was. Daarom kocht Dr. Matthew een paar bussen en richtte hij een reguliere busdienst op in Jamaica, die zowel regelmatig als efficiënt functioneerde. Het probleem was alleen dat Dr. Matthew geen stadslicentie had om een buslijn te exploiteren. Dit privilege is namelijk voorbehouden aan inefficiënte, maar beschermde monopolies. De vindingrijke Dr. Matthew ontdekte dat de stad geen bussen zonder vergunning toestond om tarieven in rekening te brengen. Daarom maakte hij zijn busdienst gratis. Passagiers die dat wilden, konden echter een bedrijfsobligatie van 25 cent kopen als ze met de bus wilden reizen.

De busdienst van Matthew was zo succesvol dat hij een tweede buslijn in Harlem opzette. Begin 1968, echter, werd de regering van New York City bezorgd en trad ze hard op. De overheid stapte naar de rechter en legde beide lijnen stil omdat ze zonder vergunning werden geëxploiteerd.

Een paar jaar later namen Dr. Matthew en zijn collega's een ongebruikt pand in Harlem in gebruik, dat eigendom was van het stadsbestuur. (Het stadsbestuur van New York is de grootste 'slumlord' van de stad. Het bezit een enorme hoeveelheid bruikbare gebouwen die verlaten zijn omdat ze de hoge onroerendgoedbelasting niet betalen, waardoor ze wegrotten en onbewoonbaar worden.) In dit gebouw richtte Dr. Matthew een goedkoop ziekenhuis op, in een tijd waarin de ziekenhuiskosten de pan uit rezen en ziekenhuisruimte schaars was. Uiteindelijk slaagde de stad er ook in om dit ziekenhuis buiten werking te stellen, met als argument 'brandovertredingen.' Keer op keer was het de rol van de overheid om de economische activiteiten van de armen te hinderen, in gebied na gebied. Het is dan ook geen verrassing dat, toen Dr. Matthew door een blanke ambtenaar van de regering van New York City werd gevraagd hoe deze het beste zelfhulpprojecten voor zwarten kon ondersteunen, Matthew antwoordde: 'Ga uit onze weg en laat ons iets proberen.'

Een ander voorbeeld van het functioneren van de overheid vond enkele jaren geleden plaats. De federale regering en de regering van New York City kondigden luidkeels aan dat ze een groep van 37 gebouwen in Harlem zouden renoveren. Maar in plaats van, zoals gebruikelijk in de particuliere sector, elk huis afzonderlijk te restaureren, gunde de overheid één contract voor het hele pakket van 37 gebouwen. Hierdoor konden kleine, zwarte bouwbedrijven niet bieden en ging het prijscontract vanzelfsprekend naar een groot blank bedrijf. Een ander voorbeeld: in 1966 kondigde de federale Small Business Administration trots een programma aan om nieuwe kleine bedrijven in zwarte handen te ondersteunen. Maar de overheid legde aan de leningen een aantal belangrijke beperkingen op. Ten eerste moest elke lener 'op armoedeniveau' zijn. Aangezien de allerarmsten niet geneigd zijn om een eigen bedrijf te starten, sloten deze voorwaarden veel kleine bedrijven uit. Vooral eigenaars met een gemiddeld laag inkomen - precies degenen die waarschijnlijk kleine ondernemers zouden zijn - werden hierdoor benadeeld. Bovenop deze beperkingen voegde de SBA van New York nog een eis toe: alle zwarten die dergelijke leningen wilden, moesten 'een echte behoefte in hun gemeenschap aantonen' om een merkbare 'economische leegte' te vullen. Deze behoefte en leegte moesten volledig naar tevredenheid van bureaucraten worden aangetoond, die vaak ver van de werkelijke economische situatie stonden.

Er werd onderzoek gedaan naar de geschatte stroom overheidsgeld (federaal en district) naar het getto van Shaw-Cardozo in Washington, D.C. Dit gebied heeft een laag inkomen onder de zwarte bevolking, en de stroom werd vergeleken met het bedrag aan belastingen dat het gebied aan de overheid betaalt. In het fiscale jaar 1967 telde het Shaw-Cardozo-gebied 84.000 inwoners, waarvan 79.000 zwart, met een gemiddeld gezinsinkomen van $5.600 per jaar. Het totale, verdiende persoonlijke inkomen voor de inwoners van het gebied bedroeg dat jaar 126,5 miljoen dollar. De totale waarde van de overheidsuitkeringen die naar het district gingen -- van sociale zekerheidsuitkeringen tot de geschatte uitgaven voor openbare scholen -- werd in dat fiscale jaar geschat op $45,7 miljoen. Dit betekent dat er bijna 40% van het totale inkomen van Shaw-Cardozo aan subsidies komt. Maar daarnaast is er ook een totale uitstroom van belastingen uit Shaw-Cardozo, die naar schatting op $50 miljoen ligt. Dit leidt tot een netto-uitstroom van $4,3 miljoen uit dit laaginkomengetto. Kun je nog steeds volhouden dat de afschaffing van de enorme, onproductieve welvaartsstaat de armen zou schaden?

De overheid zou de armen -- en de rest van de samenleving -- het beste kunnen helpen door zich op de achtergrond te houden. Ze moet haar grote en verlammende netwerk van belastingen, subsidies, inefficiënties en monopolieprivileges opheffen. Zoals professor Brozen het samenvatte in zijn analyse van de 'verzorgingsstaat':

> De staat is vaak een middel geweest om welvaart te creëren voor een enkeling, ten koste van velen. De markt heeft op een efficiënte manier voor veel welvaart gezorgd, zelfs voor een selecte groep. De staat heeft zijn methodes niet veranderd sinds de Romeinse tijd, waar brood en spelen voor de massa's zorgden voor de afleiding. Hoewel hij nu doet alsof hij onderwijs, medicijnen, gratis melk en podiumkunsten aanbiedt, blijft de staat de bron van monopolistische privileges en macht voor een selecte groep. Dit alles gebeurt achter de façade van welzijn voor velen. Dit welzijn zou veel overvloediger zijn als politici de middelen die ze gebruiken om de illusie te creëren dat ze om hun kiezers geven, niet onteigenen.

## DE NEGATIEVE INKOMSTENBELASTING

Er wordt een onderzoek gedaan naar de geschatte stroom overheidsgeld (zowel federaal als lokaal) naar het getto van Shaw-Cardozo in Washington, D.C. Dit gebied heeft te maken met lage inkomens onder de zwarte bevolking. De uitkeringen worden vergeleken met de belastinginkomsten die het gebied aan de overheid bijdraagt. In het fiscale jaar 1967 telde Shaw-Cardozo 84.000 inwoners, waarvan 79.000 zwart, met een gemiddeld gezinsinkomen van $5.600 per jaar. Het totale verdiende persoonlijke inkomen in dat jaar bedroeg 126,5 miljoen dollar. De geschatte waarde van de overheidsuitkeringen die naar het district gingen, van sociale uitkeringen tot geschatte uitgaven voor openbare scholen, was in 1967 $45,7 miljoen. Dit zou betekenen dat er bijna 40% van het totale inkomen van Shaw-Cardozo afkomstig is uit subsidies. Aan de andere kant was de totale uitstroom van belastingen uit Shaw-Cardozo naar schatting $50 miljoen. Dit leidt tot een netto-uitstroom van $4,3 miljoen uit dit laaginkomengetto. Kun je nog steeds volhouden dat het afschaffen van de enorme, onproductieve welvaartsstaat de armen zou schaden? De overheid zou de armen -- en de rest van de samenleving -- beter kunnen helpen door zich op de achtergrond te houden. Ze zou haar omvangrijke en verlammende netwerk van belastingen, subsidies, inefficiënties en monopolieprivileges moeten afschaffen. Zoals professor Brozen het samenvat in zijn analyse van de 'verzorgingsstaat': 'De staat is vaak een middel geweest om welvaart te creëren voor enkelen, ten koste van velen. De markt heeft voor veel welvaart gezorgd, zelfs voor een selecte groep, en dit met relatief lage kosten. De staat heeft zijn methodes niet veranderd sinds de Romeinse tijd, waar brood en spelen de massa moesten vermaken. Hoewel hij nu doet alsof hij onderwijs, gezondheidszorg, gratis melk en podiumkunsten aanbiedt, blijft de overheid een bron van monopolistische privileges en macht voor enkelen. Dit alles gebeurt achter de façade van welzijn voor velen -- welzijn dat overvloediger zou zijn als politici de middelen die ze gebruiken om de illusie te scheppen dat ze om hun kiezers geven, niet onteigenen.'

Helaas is de recente trend -- die wordt gesteund door een breed scala aan voorstanders, variërend van president Nixon en Milton Friedman aan de rechterkant tot een groot aantal aan de linkerkant -- om het huidige welvaartssysteem af te schaffen, niet gericht op vrijheid, maar eerder op het tegenovergestelde. Deze nieuwe ontwikkeling betreft het 'gegarandeerd jaarinkomen', de 'negatieve inkomstenbelasting' of het 'Family Assistance Plan' van president Nixon. Met een beroep op de inefficiëntie, onrechtvaardigheid en bureaucratie van het huidige systeem, zou het gegarandeerd jaarinkomen de bijstand eenvoudiger, 'efficiënter' en automatisch maken. Hierbij betaalt de belastingdienst elk jaar geld aan gezinnen die minder verdienen dan een bepaald basisinkomen. Deze automatische voldoening wordt natuurlijk gefinancierd door belastingen die worden geheven op werkende gezinnen die meer verdienen dan het basisbedrag. De geschatte kosten van dit ogenschijnlijk keurige en simpele systeem zouden slechts enkele miljarden dollar per jaar bedragen.

Maar er is een belangrijk addertje onder het gras: de kosten zijn geschat op basis van de aanname dat zowel de mensen met een uitkering als degenen die deze uitkering financieren, in dezelfde mate zullen blijven werken als voorheen. Deze aanname roept echter vragen op. Het grootste probleem is het aanzienlijke ontmoedigende effect dat het gegarandeerd jaarinkomen zal hebben op zowel de belastingbetaler als de ontvanger.

Het enige wat het huidige socialezekerheidsstelsel voor een totale ramp behoedt, is de bureaucratie en het stigma dat verbonden is aan het ontvangen van een uitkering. Ontvangers van een uitkering dragen nog steeds een psychisch stigma, hoewel dit de laatste jaren is afgenomen. Daarnaast hebben ze te maken met een typische, inefficiënte en onpersoonlijke bureaucratie. Echter, doordat het gegarandeerd jaarinkomen de bijstand efficiënt, eenvoudig en automatisch maakt, zullen de belangrijkste obstakels en ontmoedigingen voor het 'aanbod van welzijn' verdwijnen. Dit zal resulteren in een massale toestroom naar de gegarandeerde bijstand. Bovendien zal iedereen deze nieuwe bijstand beschouwen als een automatisch 'recht', in plaats van als een voorrecht of geschenk, waardoor alle stigma's zullen verdwijnen.

Stel je voor dat $4.000 per jaar de 'armoedegrens' is. Iedereen met een inkomen onder die grens ontvangt automatisch het verschil van de overheid, simpelweg door het invullen van de belastingaangifte. Wie geen inkomen heeft, krijgt $4.000 van de overheid. Iemand die $3.000 verdient, ontvangt $1.000, enzovoort. Het lijkt duidelijk dat er geen enkele reden is voor iemand die minder dan $4.000 per jaar verdient om door te blijven werken. Waarom zou hij dat doen, als zijn buurman die niet werkt uiteindelijk hetzelfde inkomen heeft als hij? Kortom, het netto-inkomen uit arbeid zal dan nul zijn. De hele werkende bevolking die onder de magische grens van $4.000 zit, zal stoppen met werken en naar de 'rechtmatige' bijstand stromen.

Maar dat is nog niet alles. Hoe zit het met de mensen die $4.000 verdienen, of zelfs net iets daarboven? De man die $4.500 per jaar verdient, zal snel merken dat de luie sloeber naast hem, die weigert te werken, zijn $4.000 van de federale overheid krijgt. Hierdoor blijft zijn eigen netto-inkomen, na veertig uur hard werken per week, beperkt tot slechts $500 per jaar. Hij stopt daarom met werken en schakelt over naar de negatieve belasting. Hetzelfde zal ongetwijfeld ook gelden voor mensen die $5.000 per jaar verdienen, enzovoort.

Het rampzalige proces is nog lang niet voorbij. Als alle mensen die minder dan $4.000 verdienen, maar ook degenen die aanzienlijk meer verdienen, stoppen met werken en naar de bijstand gaan, zullen de totale uitkeringen enorm stijgen. Deze uitkeringen kunnen alleen gefinancierd worden door de mensen met een hoger inkomen die blijven werken zwaarder te belasten. Maar hierdoor zal hun netto-inkomen na belastingen sterk dalen, waardoor ook velen van hen zullen stoppen met werken en de bijstand in zullen gaan. Laten we eens kijken naar een man die $6.000 per jaar verdient. Aanvankelijk heeft hij een netto-inkomen uit arbeid van slechts $2.000. Wanneer hij, laten we zeggen, $500 per jaar moet betalen om de werkloosheidsuitkeringen van niet-werkenden te financieren, blijft er nog maar $1.500 over. Als hij daarnaast ook nog eens $1.000 moet bijdragen om de snelle groei van anderen te ondersteunen, daalt zijn netto-inkomen naar $500 en gaat hij ook de bijstand in. De logische conclusie van het gegarandeerde jaarinkomen is dus een vicieuze spiraal die leidt naar een ramp, met als resultaat dat bijna niemand meer werkt en iedereen werkloos is.

Naast dit alles zijn er nog enkele belangrijke extra overwegingen. In de praktijk zal de uitkering, eenmaal vastgesteld op $4.000, natuurlijk niet daar blijven. De druk van bijstandscliënten en andere belangengroepen zal er elk jaar toe leiden dat het basisniveau onverbiddelijk verhoogd wordt. Dit brengt de vicieuze spiraal en de economische ramp alleen maar dichterbij. Bovendien zal het gegarandeerd jaarinkomen, in tegenstelling tot de hoop van conservatieve voorstanders, niet het bestaande lappendeken van sociale voorzieningen vervangen. Het zal gewoon bovenop de bestaande programma's komen. Dit is precies wat er is gebeurd met de ouderdomsprogramma's van de staten. Het belangrijkste onderwerp binnen het federale Sociale Zekerheidsprogramma van de New Deal was dat het op een efficiënte manier de toenmalige lappendeken van ouderdomsprogramma's zou vervangen. In werkelijkheid is dat niet gebeurd; de oudedagsvoorzieningen zijn nu veel hoger dan in de jaren dertig. Een steeds groter wordende structuur van Sociale Zekerheid is simpelweg toegevoegd aan de bestaande programma's. Tot slot is het idee van president Nixon dat validen van de nieuwe bijstand gedwongen zouden worden om te werken, een duidelijke leugen. Ten eerste zouden ze alleen 'geschikte' banen moeten vinden. De universiteit van de staatsinstellingen voor werkloosheidszorg laat zien dat er bijna nooit 'geschikte' banen beschikbaar zijn.

De verschillende regelingen voor een gegarandeerd jaarinkomen bieden geen echte vervanging voor het algemeen erkende kwaad van het socialezekerheidsstelsel; in plaats daarvan zouden ze ons alleen maar dieper in dat kwaad storten. De enige werkbare oplossing is de libertarische: de afschaffing van sociale voorzieningen ten gunste van vrijheid en vrijwilligheid voor iedereen, zowel arm als rijk.
