
# De publieke sector, II: Straten en wegen

## DE STRATEN BESCHERMEN

Afschaffing van de publieke sector houdt in dat alle stukken land, inclusief straten en wegen, privébezit zouden worden van individuen, bedrijven, coöperaties of andere vrijwillige groeperingen van mensen en kapitaal. Het feit dat alle straten en landgebieden privé-eigendom zijn, zou veel van de schijnbaar onoplosbare problemen van particuliere exploitatie oplossen. We moeten ons denken heroriënteren en nadenken over een wereld waarin al het land privébezit is.

Neem bijvoorbeeld politiebescherming. Hoe zou dit geregeld zijn in een volledig private economie? Een deel van het antwoord wordt duidelijk als we kijken naar een wereld met uitsluitend privébezit van land en straten. Denk aan het Times Square-gebied in New York City, dat bekend staat om zijn criminaliteit en waar het stadsbestuur weinig politiebescherming biedt. Iedere New Yorker weet eigenlijk dat hij op straat leeft en zich, niet alleen op Times Square, maar overal, in een bijna 'anarchistische' situatie bevindt, waarbij hij alleen afhankelijk is van de normale vreedzaamheid en goede wil van zijn medeburgers. De politiebescherming in New York is minimaal. Dit kwam op dramatische wijze naar voren tijdens een recente politiestaking van een week. In die periode nam de criminaliteit geen enkele vorm aan die verschilde van de normale toestand wanneer de politie zogenaamd alert en aan het werk is. Stel je nu voor dat het Times Square-gebied, inclusief de straten, privébezit is van bijvoorbeeld de 'Times Square Merchants Association'. De winkeliers zouden goed beseffen dat als de criminaliteit in hun gebied zou toenemen met veel overvallen en berovingen, hun klanten weg zouden blijven en voor concurrerende gebieden zouden kiezen. Het zou dus in het economische belang van de winkeliersvereniging zijn om te zorgen voor efficiënte en overvloedige politiebescherming. Op die manier zouden klanten aangetrokken worden naar hun buurt in plaats van afgestoten. Particuliere bedrijven proberen immers altijd klanten aan te trekken en te behouden. Maar wat heb je aan aantrekkelijke winkeldisplays, mooie verlichting en vriendelijke service, als klanten het risico lopen beroofd of aangevallen te worden terwijl ze door de buurt lopen?

De winkeliersvereniging zou door hun winstbejag en de wens om verliezen te voorkomen gestimuleerd worden om niet alleen voldoende politiebescherming te bieden, maar ook vriendelijke en klantgerichte service. Overheidspolitieagenten hebben geen stimulans om efficiënt te werken of zich in te leven in de behoeften van hun 'klanten'. Bovendien lopen ze constant het risico om hun macht op een brutale en dwingende manier te misbruiken. Politiegeweld is een bekend probleem binnen het politiesysteem en wordt alleen ingedamd door de klachten van de getreiterde burgers. Maar als de particuliere handelarenpolitie de verleiding toegeeft om de klanten van de winkeliers te intimideren, zullen deze klanten snel wegblijven en ergens anders hun aankopen doen. Daarom zal de winkeliersvereniging ervoor zorgen dat hun politie zowel vriendelijk als goed vertegenwoordigd is.

Zulke efficiënte en hoogwaardige politiebescherming zou in heel Nederland gelden, voor alle privéstraten en terreinen. Fabrieken zouden de toegang tot hun straten bewaken, handelsfirma's voor hun gebieden zorgen en wegbedrijven veilige en effectieve politiebescherming bieden voor hun tolwegen en andere wegen in privébezit. Hetzelfde geldt voor woonwijken. We kunnen ons twee mogelijke typen privébezit van straten in zulke buurten voorstellen. In het eerste type zouden alle landeigenaren in een bepaald blok gezamenlijk eigenaar kunnen zijn van dat blok, laten we zeggen als de '85th St. Block Company.' Deze maatschappij zou dan de politiebescherming verzorgen, waarbij de kosten ofwel rechtstreeks door de huiseigenaren betaald worden, of via de huur van de huurders als het blok huurappartementen bevat. Huiseigenaren hebben natuurlijk direct belang bij de veiligheid van hun blok, terwijl verhuurders hun huurders willen aantrekken door veilige straten aan te bieden, naast gebruikelijke diensten zoals verwarming, water en conciërgediensten. Vragen waarom huisbazen voor veilige straten moeten zorgen in een libertarische, volledig autonome maatschappij is net zo absurd als vragen waarom ze hun huurders zouden moeten voorzien van verwarming of warm water. Door concurrentie en de vraag van consumenten zijn zij verplicht om zulke diensten te leveren. Bovendien zal, of we het nu hebben over huiseigenaren of huurwoningen, de waarde van het kapitaal van grond en woning afhankelijk zijn van de veiligheid van de straat en van andere bekende kenmerken van het huis en de buurt. Veilige en goed bewaakte straten verhogen de waarde van het land en de huizen van de landeigenaar op dezelfde manier als goed onderhouden huizen dat doen. Straten met veel criminaliteit zullen de waarde van het land en de huizen echter zeker verlagen, net zoals vervallen huizen dat doen. Aangezien landeigenaren altijd de voorkeur geven aan hogere marktwaarden voor hun eigendom, is er een ingebouwde prikkel om te zorgen voor efficiënte, goed onderhouden en veilige straten.

Een andere vorm van privébezit van straten in woonwijken zou kunnen bestaan uit privé-straatbedrijven. Deze bedrijven zijn uitsluitend eigenaar van de straten en niet van de huizen of gebouwen die erop staan. De straatbedrijven zouden de grondeigenaren laten betalen voor het onderhoud, de verbetering en de beveiliging van hun straten. Veilige, goed verlichte en goed onderhouden straten zouden landeigenaren en huurders aanmoedigen om zich daar te vestigen. In tegenstelling daarmee zouden onveilige, slecht verlichte en verwaarloosde straten hen afschrikken. Een levendig gebruik van de straten door landeigenaren en auto's zou de winsten en aandelenwaarden van de straatbedrijven verhogen. Een slechte uitstraling van de straten zou daarentegen gebruikers afschrikken en de winsten en aandelenwaarden van de privé-straatbedrijven doen dalen. Daarom zullen de straateigenaren hun best doen om een effectieve straatdienst te bieden, inclusief politiebescherming, om tevreden gebruikers te garanderen. Ze worden gedreven door de behoefte om winst te maken, de waarde van hun kapitaal te verhogen en verliezen te vermijden. Het is veel verstandiger om te vertrouwen op de economische belangen van landeigenaren of straatbedrijven dan op het twijfelachtige 'altruïsme' van bureaucraten en overheidsfunctionarissen.

Op dit punt in de discussie zal iemand ongetwijfeld de vraag stellen: Wat als straten eigendom zijn van straatbedrijven en een of andere vreemde of tirannieke straateigenaar plotseling besluit om de toegang tot zijn straat te blokkeren voor een aangrenzende huiseigenaar? Hoe kan die persoon dan in- of uitgaan? Verliest hij dan voorgoed toegang, of moet hij een enorm bedrag betalen om naar binnen of naar buiten te mogen? Het antwoord op deze vraag is hetzelfde als bij een vergelijkbaar probleem met grondbezit. Stel je voor dat iedereen die huizen bezit rondom iemands eigendom deze persoon plotseling zou verbieden om zijn terrein te betreden. Het antwoord is dat iedereen die in een libertarische samenleving een huis of straat koopt, ervoor zorgt dat het koop- of huurcontract volledige toegang garandeert voor welke termijn dan ook. Met zo'n vooraf vastgelegde 'erfdienstbaarheid' zou een plotselinge blokkade niet geaccepteerd worden, omdat dit een inbreuk op het eigendomsrecht van de landeigenaar zou zijn.

Er is niets nieuws of verrassends aan het principe van deze beoogde libertarische samenleving. We zijn al bekend met de positieve effecten van concurrentie tussen lokale en interregionale transportmiddelen. In de negentiende eeuw bijvoorbeeld, zorgden de particuliere spoorwegen die door het hele land zijn aangelegd voor een aanzienlijke stimulans voor de ontwikkeling van hun gebieden. Elke spoorweg deed zijn best om immigratie en economische groei in zijn regio te bevorderen. Dit had als doel de winst, landwaarde en het kapitaal te verhogen. Spoorwegmaatschappijen waren hiertoe genoodzaakt, want anders zouden mensen en markten hun gebied verlaten ten gunste van havens, steden en gebieden die door concurrerende spoorwegen werden bediend. Hetzelfde principe geldt als alle straten en wegen ook privébezit zijn. We kennen ook de beveiliging die particuliere handelaren en organisaties bieden. Winkels hebben bewakers en toezichters in dienst; banken zorgen voor beveiligers; fabrieken hebben ook toezichters; winkelcentra hebben hun bewakingspersoneel, enzovoort. In een libertarische samenleving zou dit gezonde en functionerende systeem eenvoudigweg ook op straat worden toegepast. Het is geen toeval dat er veel meer overvallen en berovingen plaatsvinden op straat voor winkels dan in de winkels zelf. Dit komt omdat de winkels zijn beveiligd door waakzame privébewakers, terwijl we op straat moeten vertrouwen op de 'anarchie' van de politie van de overheid. In verschillende blokken van New York City zijn in de afgelopen jaren, als reactie op het toenemende criminaliteitsprobleem, particuliere bewakers ingehuurd. Deze bewakers patrouilleren in de blokken met vrijwillige bijdragen van huiseigenaren en verhuurders. De criminaliteit in deze blokken is hierdoor al aanzienlijk verminderd. Het probleem is echter dat deze initiatieven slechts sporadisch en inefficiënt zijn geweest. Straten zijn immers geen eigendom van de bewoners, waardoor er geen effectief mechanisme bestaat om kapitaal te verzamelen voor permanente en efficiënte bescherming. Bovendien kunnen de patrouillerende wachtposten wettelijk gezien niet gewapend zijn, omdat ze zich niet op het terrein van hun werkgevers bevinden. Ze kunnen, in tegenstelling tot eigenaren van winkels en andere panden, ook niet iedereen aan de tand voelen die zich verdacht gedraagt maar nog geen misdaad heeft gepleegd. Kortom, ze kunnen niet de financiële of administratieve acties ondernemen die eigenaren met hun eigendom wel kunnen uitvoeren.

Bovendien zou een politie die betaald wordt door de landeigenaren en bewoners van een blok of buurt niet alleen een einde maken aan politiegeweld tegen klanten. Dit systeem zou ook ervoor zorgen dat de politie niet langer wordt gezien als een vreemde 'imperiale' kolonisator, die er niet is om de gemeenschap te dienen, maar om deze te onderdrukken. In Amerika hebben we momenteel de situatie dat zwarte gebieden worden bewaakt door politie die is ingehuurd door centrale stedelijke overheden, overheden die als vreemd worden ervaren door de zwarte gemeenschappen. Als de politie zou worden gesteund, gecontroleerd en betaald door de bewoners en landeigenaren zelf, zou dat een heel ander verhaal zijn. Dan zouden zij hun klanten daadwerkelijk van dienst zijn, in plaats van hen te onderdrukken namens een vreemde autoriteit.

Eén blok in Harlem laat een scherp contrast zien tussen de voordelen van publieke en private bescherming. Aan West 135th Street, tussen Seventh en Eighth Avenues, staat het politiebureau van het 82nd Precinct van de New York City Police Department. Desondanks kon de aanwezigheid van de politie een golf van nachtelijke overvallen op verschillende winkels in het blok niet voorkomen. Uiteindelijk besloten in de winter van 1966 15 winkeliers in het blok samen te werken en een bewaker in te huren. Deze bewaker patrouilleerde de hele nacht in het blok. Hij werd ingehuurd via het beveiligingsbedrijf Leroy V. George om de taken te vervullen die de politie eerder niet kon bieden, ondanks hun onroerendgoedbelasting.1

De succesvolste en best georganiseerde privépolitie in de Amerikaanse geschiedenis was de spoorwegpolitie. Veel spoorwegmaatschappijen stelden deze in om letsel of diefstal van reizigers en vracht te voorkomen. De moderne spoorwegpolitie werd aan het einde van de Eerste Wereldoorlog opgericht door de Protection Section van de American Railway Association. Zij functioneerden zo goed dat in 1929 het aantal schadeclaims voor diefstal met maar liefst 93 procent was gedaald. Arrestaties door de spoorwegpolitie, die tijdens het grote onderzoek naar hun activiteiten in het begin van de jaren dertig in totaal 10.000 agenten telde, resulteerden in een veel hoger percentage veroordelingen dan de reguliere politie. Dit percentage varieerde van 83 tot 97 procent. De spoorwegpolitie was gewapend, kon normale arrestaties verrichten en werd door een onsympathieke criminoloog afgeschilderd als een organisatie met een uitstekende reputatie op het gebied van zowel karakter als bekwaamheid.2

## Straatregels

Een van de onbetwistbare gevolgen van het feit dat alle grond in het land in handen zou zijn van particuliere eigenaren en bedrijven, zou de grotere rijkdom en diversiteit van Amerikaanse buurten zijn. De manier waarop politiebescherming wordt verleend en de regels die door privépolitie worden toegepast, zouden afhangen van de wensen van de eigenaren van het land of de straat. In verdachte woonwijken zou het bijvoorbeeld kunnen vereisen dat alle mensen of auto's die het gebied willen betreden, eerst toestemming vragen aan een bewoner of goedgekeurd worden via een telefoontje vanaf de poort. Kortom, dezelfde eigendomsregels die nu vaak gelden in particuliere appartementen of familielandgoederen, zouden hier van toepassing zijn. In andere, meer losbandige gebieden zou iedereen vrijelijk naar binnen mogen en zou er een uiteenlopende mate van toezicht kunnen zijn. Commerciële gebieden zouden waarschijnlijk toegankelijk zijn voor iedereen, om klanten niet af te schrikken. Dit zou ruimte bieden voor de wensen en waarden van de bewoners en eigenaren in de verschillende gebieden van het land.

Men zou kunnen stellen dat dit alles de vrijheid biedt 'om te discrimineren' op het gebied van huisvesting of het gebruik van de straat. Daarover bestaat geen twijfel. Essentieel voor het libertarische credo is het recht van iedereen om te bepalen wie zijn eigendom mag betreden of gebruiken, mits de ander daar ook mee instemt.

'Discriminatie' in de zin van het maken van een gunstige of ongunstige keuze, ongeacht de criteria die iemand gebruikt, is een essentieel onderdeel van keuzevrijheid en daarmee van een vrije samenleving. In de vrije markt is dergelijke discriminatie echter kostbaar en zal de betrokken eigenaar daarvoor moeten betalen.

Stel je voor dat iemand in een vrije samenleving een huis of een appartementencomplex verhuurt. Hij zou gewoon de markthuur kunnen vragen en verder niets doen. Maar dat brengt risico's met zich mee. Misschien besluit hij om geen woningen te verhuren aan gezinnen met jonge kinderen, omdat hij vreest dat zijn eigendom daardoor beschadigd raakt. Aan de andere kant kan hij ervoor kiezen om een hogere huurprijs te vragen om het verhoogde risico te compenseren. Dit betekent dat de vrije markthuur voor zulke gezinnen dan hoger zal zijn dan voor anderen. In de meeste gevallen zal dit op de vrijemarkteconomie gebeuren. Maar hoe zit het met persoonlijke, in plaats van puur economische, 'discriminatie' door de verhuurder? Stel dat de verhuurder een groot bewonderaar is van twee meter lange Zweeds-Amerikanen en besluit zijn appartementen alleen aan gezinnen uit die groep te verhuren. In een vrije maatschappij heeft hij daar het recht toe, maar het is duidelijk dat hij hierdoor een aanzienlijk financieel verlies zou lijden. Hij zou huurder na huurder afwijzen in een eindeloze zoektocht naar lange Zweeds-Amerikanen. Hoewel dit als een extreem voorbeeld kan worden gezien, geldt hetzelfde effect --- zij het in verschillende mate --- voor elke vorm van persoonlijke discriminatie op de markt. Als de verhuurder bijvoorbeeld een hekel heeft aan roodharigen en besluit zijn appartementen niet aan hen te verhuren, zal hij ook verliezen, zij het niet zo ernstig als in het eerste geval.

Hoe dan ook, wanneer iemand dergelijke 'discriminatie' toepast op de vrije markt, moet hij de kosten daarvan dragen. Dit kan betekenen dat hij winst misloopt of dat hij als consument diensten verliest. Als een consument ervoor kiest om goederen te boycotten die worden verkocht door mensen die hij niet mag---ongeacht of die afkeer terecht is of niet---zal hij verstoken blijven van goederen of diensten die hij anders zou hebben gekocht.

In een vrije samenleving stellen alle eigenaren van onroerend goed regels op voor het gebruik van hun eigendom of de toegang daartoe. Hoe strikter de regels, hoe minder mensen ervan gebruik zullen maken. De eigenaar zal dan moeten afwegen of de striktheid van de toelating opweegt tegen het verlies aan inkomsten. Een verhuurder kan bijvoorbeeld 'discrimineren' door te eisen --- zoals George Pullman deed in zijn 'company town' in Illinois aan het einde van de negentiende eeuw --- dat al zijn huurders altijd in jasje en das verschijnen. Hij zou dit kunnen doen, maar het is twijfelachtig of veel huurders ervoor zouden kiezen om in een dergelijk gebouw te wonen of daar te blijven. In dat geval zou de verhuurder ernstige verliezen lijden.

Het principe dat eigendom door de eigenaren wordt beheerd, vormt ook een weerlegging van een gangbaar argument voor overheidsinterventie in de economie. Vaak wordt gesteld: 'De overheid stelt tenslotte verkeersregels op - zoals rood en groen licht, rechtsrijden en maximumsnelheid. Iedereen kan zich voorstellen dat het verkeer in chaos zou ontaarden zonder zulke regels. Waarom zou de overheid dan niet ingrijpen in de rest van de economie?' De denkfout hier is niet dat verkeer gereguleerd moet worden; zulke regels zijn zeker nodig. Maar het cruciale punt is dat deze regels altijd worden vastgesteld door de personen die eigenaar zijn van de wegen en deze beheren. De overheid heeft verkeersregels opgesteld omdat zij de eigenaar is van de straten en wegen en deze daarom beheert. In een libertarische samenleving met privé-eigendom zouden de privé-eigenaren de regels opstellen voor het gebruik van hun wegen.

Maar zouden de verkeersregels niet 'chaotisch' zijn in een puur vrije maatschappij? Zouden sommige wegowners niet rood aanwijzen voor 'stop', anderen misschien groen of blauw? En zouden sommige wegen niet rechts worden bereden terwijl andere links worden gebruikt? Zulke vragen zijn absurd. Het is in het belang van alle wegbeheerders om uniforme regels te hebben, zodat het verkeer soepel en zonder problemen kan verlopen. Elke eigenzinnige eigenaar die zou aandringen op links rijden of groen voor 'stop' in plaats van 'ga' zou al snel geconfronteerd worden met talloze ongelukken en een afname van klanten. De privéspoorwegen in het negentiende-eeuwse Amerika hadden vergelijkbare problemen en losten deze harmonieus op. Ze lieten elkaars wagons toe op hun sporen, maakten onderlinge verbindingen voor wederzijds voordeel, stemden de spoorbreedtes op elkaar af en stelden uniforme regionale goederenclassificaties op voor 6.000 artikelen. Bovendien waren het de spoorwegen en niet de overheid die het initiatief namen om de chaotische lappendeken van tijdzones te consolideren. Voor een nauwkeurige dienstregeling en tijdschema's moesten ze samenwerken, en in 1883 stemden ze ermee in om de 54 bestaande tijdzones in het hele land samen te voegen tot de vier die we nu hebben. De financiële krant van New York, de *Commercial and Financial Chronicle*, constateerde dat 'de wetten van de handel en het instinct voor zelfbehoud hervormingen en verbeteringen teweegbrengen die alle wetgevende instanties samen niet konden verwezenlijken'.

## ### TARIFERING VAN STRATEN EN WEGEN

In een vrije samenleving stellen eigenaren van onroerend goed regels op voor het gebruik van hun eigendom of de toegang ertoe. Hoe strikter de regels, hoe minder mensen ervan gebruik zullen maken. De eigenaar moet dan afwegen of de stringente toelatingseisen opwegen tegen het verlies aan inkomsten. Een verhuurder kan bijvoorbeeld 'discrimineren' door te eisen --- zoals George Pullman deed in zijn 'company town' in Illinois aan het einde van de negentiende eeuw --- dat al zijn huurders altijd in jasje en das verschijnen. Hij kan dit doen, maar het is de vraag of veel huurders bereid zouden zijn om in zo'n gebouw te wonen. In dat geval zou de verhuurder ernstige verliezen lijden. Het principe dat eigendom door de eigenaren wordt beheerd, vormt ook een weerlegging van een veelvoorkomend argument voor overheidsinterventie in de economie. Sommigen stellen: 'De overheid stelt tenslotte verkeersregels op --- zoals rood en groen licht, rechtsrijden en maximumsnelheid. Iedereen kan zich voorstellen dat het verkeer in chaos zou ontaarden zonder zulke regels. Waarom zou de overheid dan niet ingrijpen in de rest van de economie?' De denkfout hier is niet dat verkeer gereguleerd moet worden; zulke regels zijn zeker nodig. Maar het cruciale punt is dat deze regels altijd worden vastgesteld door degenen die eigenaar zijn van de wegen en deze beheren. De overheid heeft verkeersregels ingevoerd omdat zij de eigenaar van de straten en wegen is en deze daardoor moet beheren. In een libertarische samenleving met privé-eigendom zouden de privé-eigenaren de regels voor het gebruik van hun wegen zelf opstellen. Maar zouden de verkeersregels niet 'chaotisch' zijn in een puur vrije maatschappij? Zou de ene wegbeheerder niet rood voor 'stop' aanwijzen, terwijl een andere groen of blauw kiest? En zouden sommige wegen niet rechts worden bereden terwijl andere links worden gebruikt? Zulke vragen zijn absurd. Het is in het belang van alle wegbeheerders om uniforme regels te hebben, zodat het verkeer soepel en zonder problemen kan verlopen. Elke eigenzinnige eigenaar die zou aandringen op links rijden of groen voor 'stop' in plaats van 'ga,' zou al snel te maken krijgen met talloze ongelukken en een afname van gebruikers. De privéspoorwegen in het negentiende-eeuwse Amerika hadden vergelijkbare problemen en losten deze probleemloos op. Ze lieten elkaars wagons toe op hun sporen, maakten onderlinge verbindingen voor wederzijds voordeel, stemden de spoorbreedtes op elkaar af, en ontwikkelden uniforme regionale goederenclassificaties voor 6.000 artikelen. Bovendien waren het de spoorwegen, en niet de overheid, die het initiatief namen om de chaotische lappendeken van tijdzones samen te voegen. Voor een nauwkeurige dienstregeling moesten ze samenwerken. In 1883 stemden ze ermee in om de 54 bestaande tijdzones in het hele land te consolideren tot de vier die we nu hebben. De financiële krant van New York, de *Commercial and Financial Chronicle*, merkte op dat 'de wetten van de handel en het instinct voor zelfbehoud hervormingen en verbeteringen teweegbrengen die alle wetgevende instanties samen niet kunnen verwezenlijken.'

Als we kijken naar de prestaties van de openbare wegen en snelwegen in Amerika, is het moeilijk te begrijpen hoe privé-eigendom een slechtere of inefficiëntere staat van dienst zou kunnen hebben. Het is tegenwoordig algemeen erkend dat federale en staatsregeringen, onder druk van lobbygroepen van auto-industrieën, oliemaatschappijen, bandenfabrikanten, aannemers en vakbonden, hebben gezorgd voor een enorme uitbreiding van snelwegen. Deze snelwegen bieden aanzienlijke subsidies aan gebruikers en hebben bijgedragen aan het ineenstorten van de spoorwegen als levensvatbare onderneming. Vrachtwagens rijden namelijk op wegen die zijn aangelegd en onderhouden door belastingbetalers, terwijl de spoorwegen zelf verantwoordelijk zijn voor de aanleg en het onderhoud van hun spoor. Bovendien hebben de gesubsidieerde snelwegen en wegenprogramma's geleid tot een ongecontroleerde groei van voorsteden waar veel autos rijden. Dit ging vaak gepaard met het gedwongen afbreken van talloze huizen en bedrijven en drukte de belasting op de centrale steden. De kosten voor belastingbetalers en de economie zijn enorm geweest.

Vooral de forens die in een autostad woont, profiteert van subsidies. Juist in de steden is het aantal verkeersopstoppingen toegenomen, samen met deze subsidie voor het overmatige verkeer. Professor William Vickrey van de Universiteit van Columbia heeft geschat dat stedelijke snelwegen zijn aangelegd tegen kosten van 6 tot 27 cent per voertuigkilometer. De gebruikers betalen echter maar zo'n 1 cent per voertuigkilometer aan benzine- en andere autobelastingen. Hierdoor betaalt de algemene belastingbetaler, in plaats van de automobilist, voor het onderhoud van de straten in de stad. Bovendien wordt de benzinebelasting per kilometer geheven, ongeacht welke straat of snelweg wordt gebruikt, en dat geldt ook voor het tijdstip van de rit. Wanneer snelwegen dus gefinancierd worden vanuit het algemene benzinebelastingfonds, zijn de gebruikers van de goedkopere landelijke snelwegen verplicht om de gebruikers van de veel duurdere stedelijke snelwegen te subsidiëren. Landelijke snelwegen kosten doorgaans slechts 2 cent per voertuigkilometer om aan te leggen en te onderhouden.

Bovendien is de benzinebelasting geen rationeel prijssysteem voor het gebruik van wegen. Geen enkel privébedrijf zou wegen ooit op deze manier prijzen. Privébedrijven bepalen hun tarieven om de 'markt vrij te maken'. Dit houdt in dat het aanbod aansluit op de vraag, zodat er geen tekorten of onverkochte goederen ontstaan. Het feit dat benzineaccijnzen per kilometer worden geheven, ongeacht welke weg je gebruikt, betekent dat de drukste straten en snelwegen in steden een prijs betalen die veel lager is dan de prijs in een vrije markt. Het gevolg hiervan zijn enorme verkeersopstoppingen op druk bereden wegen, vooral tijdens de spits, terwijl het plattelandswegennet vrijwel ongebruikt blijft. Een rationeel prijssysteem zou de winst voor de wegbeheerder maximaliseren en tegelijkertijd zorgen voor vrije straten zonder files. In het huidige systeem houdt de overheid de prijs voor gebruikers van overbelaste wegen extreem laag. Deze ligt ver onder de vrije marktprijs, wat resulteert in een chronisch tekort aan wegruimte dat zich manifesteert in verkeersopstoppingen. In plaats van dit groeiende probleem op te lossen door prijzen rationeel aan te passen, heeft de overheid geprobeerd het op te lossen door nog meer wegen aan te leggen. Dit brengt alleen maar extra kosten met zich mee voor de belastingbetalers, die nog meer subsidies moeten financieren voor automobilisten, waardoor het tekort alleen maar toeneemt. Het wanhopig vergroten van het aanbod terwijl de gebruiksprijs onder de marktprijs blijft, leidt simpelweg tot chronische en verergerende files. Het doet denken aan een hond die achter een mechanisch konijn aanziet. Zo heeft de *Washington Post* de impact van het federale snelwegprogramma in de hoofdstad van het land in kaart gebracht:

> De Capital Beltway in Washington was een van de eerste grote onderdelen van het systeem die voltooid werd. Toen het laatste stuk in de zomer van 1964 werd geopend, werd het geprezen als een van de mooiste snelwegen die ooit zijn aangelegd.
>
> Er werd verwacht dat het (a) de verkeersopstoppingen in het centrum van Washington zou verminderen door een rondweg te creëren voor noord-zuidverkeer en (b) de voorstedelijke gemeenten en steden rond de hoofdstad met elkaar zou verbinden.
>
> Wat de ringweg in werkelijkheid werd, was (a) een snelweg voor forensen en een rondweg voor lokaal verkeer en (b) de oorzaak van een enorme bouwboom die de vlucht van blanken en welgestelden uit de binnenstad versnelde.
>
> In plaats van de verkeersopstoppingen te verminderen, heeft de Beltway deze juist verergerd. Samen met I-95, I-70 en I-66 heeft het forenzen in staat gesteld zich steeds verder van hun werk in het centrum te verwijderen.
>
> Dit heeft er ook toe geleid dat overheidsinstanties en bedrijven in de detailhandel en dienstverlening van het centrum naar de buitenwijken zijn verhuisd. Hierdoor liggen de banen die deze bedrijven creëren vaak buiten het bereik van veel inwoners van de binnenstad.6

Hoe zou een rationeel prijssysteem, dat ingesteld wordt door particuliere wegbeheerders, eruitzien? In de eerste plaats zouden snelwegen tolkosten in rekening brengen, vooral bij belangrijke toegangspunten tot steden, zoals bruggen en tunnels, maar niet op de huidige manier. De toltarieven zouden bijvoorbeeld veel hoger zijn tijdens de spitsuren en andere drukke periodes (zoals zondagen in de zomer) dan daarbuiten. In een vrije markt zou de grotere vraag in de spits leiden tot hogere toltarieven, totdat de verkeersdrukte afneemt en de doorstroming verbetert. Maar wat als mensen dan toch naar hun werk moeten, vraagt de lezer zich misschien af? Natuurlijk hoeven ze niet met hun eigen auto te gaan. Sommige forenzen zullen helemaal overstappen en teruggaan naar de stad. Anderen zullen carpoolen, terwijl weer anderen gebruikmaken van snelbussen of treinen. Op deze manier wordt het gebruik van de wegen tijdens de spits beperkt tot degenen die bereid zijn om de marktconforme prijs te betalen voor hun rit. Bovendien zullen mensen proberen hun werktijden te verschuiven, zodat ze op andere momenten kunnen aankomen en vertrekken. Ook weekendreizigers zullen minder gaan rijden of hun reistijden spreiden. Tot slot zullen de hogere winsten die bijvoorbeeld gemaakt kunnen worden op bruggen en tunnels, particuliere bedrijven stimuleren om meer van dergelijke infrastructuur te bouwen. De aanleg van wegen zal niet langer afhangen van lobby's van actiegroepen en gebruikers die om subsidies vragen, maar van de efficiënte vraag- en kostenanalyses van de markt.

Terwijl veel mensen zich de werking van particuliere snelwegen kunnen voorstellen, raakt men in de war bij het idee van particuliere straten in de stad. Hoe zouden die geprijsd worden? Zouden er tolpoorten bij elke straat komen? Natuurlijk niet, want een dergelijk systeem zou duidelijk onrendabel en onbetaalbaar zijn, zowel voor de eigenaar als voor de bestuurder. Allereerst zullen de straateigenaren het parkeren veel doordachter prijzen dan nu het geval is. Ze zullen het parkeren in drukke straten in het stadscentrum fors duurder maken, als reactie op de grote vraag. In tegenstelling tot de huidige praktijken zullen ze juist veel meer, in plaats van minder, rekenen voor langer parkeren, de hele dag door. Kortom, de straateigenaren zullen zich inzetten voor een betere doorstroming in de drukke gebieden. Dit is begrijpelijk voor het parkeren, maar hoe zit het met autorijden op drukke straten in de stad? Hoe kan dit geprijsd worden? Er zijn verschillende mogelijke manieren. Ten eerste zouden de straateigenaren in de binnenstad kunnen eisen dat iedereen die hun straten gebruikt, een vergunning aanschaft, die op de auto kan worden aangebracht, zoals nu met stickers en vergunningen gebeurt. Bovendien zouden ze kunnen verlangen dat iedereen die tijdens piekuren rijdt, een extra, dure vergunning koopt en laat zien. Daarnaast zijn er andere mogelijkheden. Moderne technologie kan ervoor zorgen dat auto's worden uitgerust met een meter die niet alleen per kilometer meetelt, maar ook sneller registreert op drukke straten en wegen tijdens piekuren. Hierdoor zou de auto-eigenaar aan het eind van de maand een rekening kunnen ontvangen. Een soortgelijk plan werd tien jaar geleden voorgesteld door professor A.A. Walters:

> De specifieke administratieve instrumenten die gebruikt kunnen worden, omvatten speciale kilometertellers, vergelijkbaar met die van taxi's. Deze kilometertellers zouden het aantal gereden kilometers registreren wanneer de 'vlag' omhoog is; over deze kilometers zou een heffing worden toegepast. Dit systeem zou goed werken in grote stedelijke gebieden zoals New York, Londen en Chicago. Straten met een 'vlag omhoog' zouden voor bepaalde uren van de dag kunnen worden aangegeven. Voertuigen zouden op deze straten mogen rijden zonder speciale kilometertellers, mits zij een dagelijkse 'sticker' kopen en zichtbaar tonen. Voor incidenteel verkeer met een 'sticker' zou een hoger bedrag gelden dan het maximumbedrag voor voertuigen met een kilometerteller. Het toezicht op deze regeling zou relatief eenvoudig zijn. Camera's zouden kunnen worden geïnstalleerd om auto's zonder sticker of vlag te registreren. Bij overtredingen kan een passende boete worden opgelegd.7

Professor Vickrey heeft ook voorgesteld om verkeerscamera's te plaatsen op de kruispunten van de drukste straten. Deze camera's zouden de kentekens van alle auto's registreren. Automobilisten zouden dan elke maand een rekening ontvangen voor alle keren dat ze het kruispunt oversteken. Als alternatief stelde hij voor dat iedere auto uitgerust zou kunnen worden met het elektronische meetapparaat van Oxford. Elke auto zou dan een uniek signaal uitzenden, dat door het apparaat op het betreffende kruispunt wordt opgevangen.8

Hoe dan ook, het probleem van een eerlijke prijsstelling voor straten en snelwegen kan eenvoudig worden opgelost door particuliere bedrijven en moderne technologie. Ondernemers op de vrije markt hebben al veel moeilijkere vraagstukken aangepakt. Het enige wat nodig is, is hen de ruimte geven om hun werk te doen.

Als al het transport volledig vrij zou zijn en de wegen, luchtvaartmaatschappijen, spoorwegen en waterwegen bevrijd zouden zijn van hun ingewikkelde netwerken van subsidies, controles en voorschriften binnen een puur privaat systeem, hoe zouden consumenten hun transportbudget dan verdelen? Zouden we bijvoorbeeld weer de trein nemen? De beste schattingen van de kosten en de vraag naar vervoer geven aan dat de spoorwegen het belangrijkste vervoermiddel zouden worden voor vrachtvervoer over lange afstanden. Luchtvaartmaatschappijen zouden de voorkeur genieten voor passagiersvervoer op lange afstanden, vrachtwagens voor vrachtvervoer over korte afstanden en bussen voor openbaar woon-werkverkeer. In feite zouden de spoorwegen een heropleving doormaken voor langeafstandsgoederenvervoer, maar ze zouden niet opnieuw opbloeien voor veel passagiersvervoer. In de afgelopen jaren hebben verschillende liberalen, die teleurgesteld zijn over de overbelasting van snelwegen, gepleit voor het massaal ontmoedigen van snelweggebruik. Ze pleiten voor grootschalige subsidies en bouwprojecten voor metro's en pendeltreinen voor stedelijk verkeer. Maar deze ambitieuze plannen negeren de hoge kosten en verspilling die dit met zich meebrengt. Hoewel veel snelwegen misschien niet gebouwd hadden moeten worden, zijn ze er wel en het zou onzinnig zijn om er geen gebruik van te maken. Enkele slimme transporteconomen hebben in de afgelopen jaren hun kritiek laten horen op de enorme verspilling die gepaard gaat met de aanleg van nieuwe snelwegen, zoals in de regio van de San Francisco Bay. Ze hebben in plaats daarvan voorgesteld om de bestaande snelwegen beter te benutten door snelbussen voor woon-werkverkeer in te zetten.9

Het is niet moeilijk om je een netwerk voor te stellen van particuliere, ongesubsidieerde en ongereguleerde spoorwegen en luchtvaartmaatschappijen. Maar kan er ook een systeem van particuliere wegen bestaan? Is zo'n systeem überhaupt haalbaar? Eén antwoord is dat privéwegen in het verleden goed hebben gefunctioneerd. In Engeland voor de achttiende eeuw bijvoorbeeld waren de wegen, die doorgaans eigendom waren van en beheerd werden door lokale overheden, slecht aangelegd en nog slechter onderhouden. Deze openbare wegen konden nooit de krachtige industriële revolutie van de achttiende eeuw ondersteunen, de 'revolutie' die de moderne tijd inluidde. De cruciale taak om de bijna onbegaanbare Engelse wegen te verbeteren, werd uitgevoerd door particuliere tolwegmaatschappijen. Deze maatschappijen, die vanaf 1706 actief waren, organiseerden en legden een uitgebreid netwerk aan dat Engeland tot de afgunst van de wereld maakte. De eigenaren van deze particuliere tolwegmaatschappijen waren meestal landeigenaren, kooplieden en industriëlen uit de regio die door de weg bediend werd. Ze vergoedden hun kosten door tol te heffen bij geselecteerde tolpoorten. Vaak werd het innen van de tol voor een jaar of langer verhuurd aan individuen die via een veiling geselecteerd waren. Het waren deze privéwegen die een interne markt in Engeland ontwikkelden en de transportkosten van kolen en ander volumineus materiaal aanzienlijk verlaagden. Doordat ze er wederzijds voordeel uit haalden, sloten de tolwegmaatschappijen zich aan bij elkaar om een onderling verbonden wegennet door het hele land te vormen. Dit alles was het resultaat van particulier ondernemerschap in actie.10

Zoals in Engeland, zo ook in de Verenigde Staten, zij het iets later. Geconfronteerd met vrijwel onbegaanbare wegen die door lokale overheden waren aangelegd, bouwden en financierden particuliere maatschappijen tussen 1800 en 1830 een uitgebreid netwerk van tolwegen door de noordoostelijke staten. Ook hier bleek particuliere ondernemingen superieur aan de achterhaalde activiteiten van de overheid als het gaat om wegenbouw en -beheer. De wegen werden aangelegd en geëxploiteerd door particuliere tolwegbedrijven, en de gebruikers moesten tol betalen. Net als in Engeland werden deze tolwegmaatschappijen grotendeels gefinancierd door kooplieden en landeigenaren langs de routes. Zij sloten zich vrijwillig aan bij een onderling verbonden netwerk van wegen. Deze tolwegen vormden de eerste echt goede wegen in de Verenigde Staten.11
