
# De publieke sector, III: Politie, rechtspraak en rechtbanken

## **POLITIEBESCHERMING**

De markt en privaat ondernemerschap zijn aanwezig, waardoor de meeste mensen zich gemakkelijk een vrije markt voor de meeste goederen en diensten kunnen voorstellen. Maar het lastigste onderdeel is waarschijnlijk de afschaffing van overheidsactiviteiten die bescherming bieden: politie, rechtbanken, enzovoort. Dit betreft de verdediging van personen en eigendommen tegen aanvallen of inbreuken. Hoe kunnen particuliere ondernemingen en de vrije markt zo'n dienst verlenen? Hoe kunnen politie, rechtssystemen, gerechtelijke diensten en wetshandhaving bestaan in een vrije markt? We hebben al gezien dat een groot deel van de politiebescherming mogelijk geleverd kan worden door verschillende eigenaren van straten en landerijen. Nu moeten we echter dit geheel systematisch onder de loep nemen.

In de eerste plaats bestaat er een veel voorkomende misvatting, die zelfs door de meeste voorstanders van laissez-faire wordt gedeeld: dat de overheid 'politiebescherming' moet bieden, alsof dit een enkele, vaste dienst is die voor iedereen beschikbaar is. In werkelijkheid is er geen absoluut goed dat 'politiebescherming' heet, net zoals er geen absoluut goed is dat 'voedsel' of 'onderdak' wordt genoemd. Iedereen betaalt belasting voor een ogenschijnlijk vaste hoeveelheid bescherming, maar dat is een mythe. Er zijn namelijk bijna ontelbare vormen van bescherming beschikbaar. Voor een bepaalde persoon of een bedrijf kan de politie variëren van een agent die één keer per nacht patrouilleert tot twee agenten die continu in een wijk aanwezig zijn. Dit kan zelfs verder gaan naar rondrijdende patrouillewagens of één of meerdere persoonlijke lijfwachten die 24 uur per dag beschikbaar zijn. Daarnaast zijn er nog tal van beslissingen die de politie moet nemen. De complexiteit hiervan wordt duidelijk als we de mythe van de absolute 'bescherming' nader bekijken. Hoe zal de politie haar middelen toewijzen? Die zijn namelijk altijd beperkt, net zoals de middelen van andere personen, organisaties en instanties. Hoeveel moet de politie investeren in elektronische apparatuur? In apparatuur voor het nemen van vingerafdrukken? In detectives tegenover geüniformeerde agenten? In patrouillewagens versus voetpatrouilles, en ga zo maar door?

Het probleem is dat de overheid geen rationele manier heeft om middelen toe te wijzen. Ze weet alleen dat ze een beperkt budget heeft. De toewijzing van middelen is daardoor afhankelijk van politieke spelletjes, gierigheid en bureaucratische inefficiëntie. Dit gebeurt zonder enige garantie dat het politiedepartement de behoeften van de burgers op een efficiënte manier vervult. De situatie zou anders zijn als politiediensten op een vrije, concurrerende markt zouden worden aangeboden. In dat geval zouden consumenten betalen voor de bescherming die zij wensen. Degenen die af en toe een politieagent willen zien, zouden minder betalen dan degenen die voortdurend patrouilles willen. En mensen die 24 uur per dag lijfwachten wensen, zouden nog meer moeten betalen. Op de vrije markt zou bescherming geleverd worden naar rato van wat consumenten bereid zijn te betalen. De verplichting om winst te maken en verliezen te vermijden zou ervoor zorgen dat efficiëntie gewaarborgd is, wat resulteert in lage kosten en een hoge kwaliteit die aan de wensen van de consumenten voldoet. Politiebedrijven die onverantwoord omgaan met middelen zouden snel failliet gaan en verdwijnen.

Een groot probleem waar een overheids-politiemacht altijd mee te maken heeft, is de vraag welke wetten echt gehandhaafd moeten worden. Politieafdelingen krijgen de opdracht om 'alle wetten te handhaven', maar in de praktijk dwingt een beperkt budget hen om hun personeel en middelen te richten op de meest dringende misdaden. Dit absolute dictaat belemmert een rationele toewijzing van middelen. Op de vrije markt zou de handhaving afgedwongen worden door wat klanten bereid zijn ervoor te betalen. Stel je voor dat meneer Jones een kostbaar juweel bezit waarvan hij vreest dat het binnenkort gestolen zal worden. Hij kan dan 24-uurs politiebescherming aanvragen en betalen tegen een tarief dat hij met het politiebedrijf afspreekt. Aan de andere kant heeft hij misschien ook een privéweg op zijn landgoed waar hij niet wil dat er veel mensen op rijden. In dat geval zal het hem waarschijnlijk weinig interesseren dat er mensen op die weg komen. Hij zal dan geen politie inschakelen om de weg te beschermen. Net als in de algemene markt is het aan de consument. Aangezien wij allemaal consumenten zijn, betekent dit dat iedereen individueel beslist hoeveel en wat voor soort bescherming hij wil en kan kopen.

Alles wat we hebben gezegd over de politie van landeigenaren geldt ook voor particuliere politie in het algemeen. De politie op de vrije markt zou niet alleen efficiënt zijn, maar zou ook een sterke prikkel hebben om hoffelijk te zijn en zich te onthouden van brutaliteit tegenover hun klanten, of de vrienden en klanten van deze klanten. Een privé Central Park zou efficiënt worden beveiligd om het park maximaal te laten renderen, in plaats van dat onschuldige betalende klanten een avondklok opgelegd krijgen. Op een vrije politiemarkt zouden efficiënte en hoffelijke politiediensten beloond worden, terwijl elke afwijking van deze norm bestraft zou worden. Er zou niet langer een scheiding bestaan tussen dienstverlening en betaling zoals die nu bij overheidsoperaties gebruikelijk is. Deze scheiding betekent dat de politie, net als andere overheidsinstellingen, haar inkomsten niet op vrijwillige en concurrerende basis van consumenten verwerft, maar onder dwang van de belastingbetalers.

Omdat de overheidspolitie steeds inefficiënter wordt, wenden consumenten zich steeds vaker tot particuliere vormen van bescherming. We hebben het al gehad over buurt- of blokbeveiliging. Daarnaast zijn er privébewakers, verzekeringsmaatschappijen, privédetectives en geavanceerdere apparatuur zoals kluizen, sloten, beveiligingscamera's en inbraakalarmen. De President's Commission on Law Enforcement and the Administration of Justice schatte in 1969 dat de overheids politie het Amerikaanse publiek $2,8 miljard per jaar kostte. Tegelijkertijd gaven consumenten $1,35 miljard uit aan privébeschermingsdiensten en nog eens $200 miljoen aan apparatuur. Dit betekent dat de uitgaven voor privébescherming meer dan de helft van die voor overheidspolitie uitmaakten. Deze cijfers zouden zelfs de meest sceptische mensen aan het denken moeten zetten, vooral degenen die geloven dat politiebescherming op de een of andere mysterieuze manier, door een of ander recht of macht, noodzakelijkerwijs en voor altijd een kenmerk van staatssoevereiniteit is.

Elke lezer van detectivefictie weet dat privédetectives van verzekeringsmaatschappijen veel efficienter zijn dan de politie in het terugvinden van gestolen goederen. De verzekeringsmaatschappij heeft immers een economische prikkel om de consument te helpen en probeert zo uitkeringen te vermijden. De focus van de verzekeringsmaatschappij verschilt bovendien wezenlijk van die van de politie. De politie, die namens een abstracte 'maatschappij' opereert, richt zich voornamelijk op het vangen en straffen van criminelen. Het teruggeven van de gestolen buit aan het slachtoffer is daarbij van secundair belang. Voor de verzekeringsmaatschappij en haar rechercheurs daarentegen is het terugkrijgen van de buit de hoogste prioriteit. De arrestatie en bestraffing van de dader komen pas op de tweede plaats, want het hoofddoel is om het slachtoffer van het misdrijf te helpen. Hier zien we opnieuw het verschil tussen een particuliere onderneming die gedwongen is de klant-slachtoffer van een misdrijf te bedienen, en de openbare politie, die niet onder een dergelijke economische druk staat.

We kunnen geen blauwdruk maken voor een markt die momenteel slechts in hypothesen bestaat. Toch is het redelijk te veronderstellen dat in een libertarische samenleving politiediensten geleverd zouden worden door landeigenaren of verzekeringsmaatschappijen. Aangezien verzekeringsmaatschappijen uitkeringen uitkeren aan slachtoffers van criminaliteit, is het zeer waarschijnlijk dat zij ook politiediensten zouden aanbieden om criminaliteit te bestrijden en zo hun uitkeringen te beperken. In elk geval lijkt het waarschijnlijk dat de politiediensten zouden worden gefinancierd door regelmatige maandelijkse premies. De dienst kan dan, of het nu een verzekeringsmaatschappij betreft of niet, worden ingeschakeld wanneer dat nodig is.

Dit biedt een eenvoudig antwoord op de typische nachtmerrievraag van mensen die voor het eerst over het idee van een volledig particuliere politie horen: 'Maar betekent dat dan dat je, als je aangevallen of beroofd wordt, naar een politieagent moet rennen en moet kibbelen over de kosten van je verdediging?' Een moment van nadenken laat zien dat geen enkele dienst op deze manier op de vrije markt wordt aangeboden. Het is duidelijk dat iemand die bescherming wil van Agentschap A of Verzekeringsmaatschappij B reguliere premies zal betalen, in plaats van te wachten tot hij wordt aangevallen voordat hij bescherming aanschaft. 'Maar stel dat er een noodgeval is en een politieagent van maatschappij A ziet iemand overvallen; zal hij dan stoppen om te vragen of het slachtoffer een verzekering heeft bij maatschappij A?' Ten eerste wordt dit soort straatcriminaliteit, zoals eerder vermeld, afgehandeld door de politie die ingehuurd is door de eigenaar van de straat. Wat gebeurt er in het onwaarschijnlijke geval dat een buurt geen straatpolitie heeft en een agent van bedrijf A toevallig ziet dat iemand wordt aangevallen? Zal hij het slachtoffer te hulp schieten? Dat hangt natuurlijk af van bedrijf A, maar het lijkt onwaarschijnlijk dat particuliere politiebedrijven geen goodwill zouden opbouwen door beleid te voeren dat hen aanmoedigt om gratis hulp te verlenen aan slachtoffers in nood. Misschien vragen ze het geredde slachtoffer achteraf om een vrijwillige donatie. Als een huiseigenaar wordt beroofd of aangevallen, zal hij uiteraard het politiebedrijf inschakelen dat hij heeft gekozen. Hij zal politiebedrijf A bellen in plaats van 'de politie' waar hij nu op terugvalt.

Concurrentie leidt tot efficiëntie, lage prijzen en hoge kwaliteit. Er is daarom geen reden om aan te nemen dat het hebben van slechts één politieagentschap in een bepaald gebied iets goddelijks is, wat veel mensen wel denken. Economen hebben vaak betoogd dat de productie van bepaalde goederen of diensten een 'natuurlijk monopolie' is. Dit zou betekenen dat meer dan één politiebureau in een bepaald gebied niet zou kunnen overleven. Misschien, maar alleen een volledig vrije markt kan hierover definitief beslissen. De markt kan bepalen welke bedrijven, in welke hoeveelheid, grootte en kwaliteit kunnen concurreren en overleven. Er is echter geen reden om van tevoren aan te nemen dat politiebescherming een 'natuurlijk monopolie' is. Verzekeringsmaatschappijen zijn dat immers ook niet. Als we bedrijven zoals Metropolitan, Equitable en Prudential naast elkaar kunnen laten bestaan, waarom zouden we dan geen Metropolitan, Equitable en Prudential als politiebeschermingsmaatschappijen kunnen hebben? Gustave de Molinari, een negentiende-eeuwse Franse vrijmarkteconoom, was de eerste die het idee van een vrije markt voor politiebescherming overwoog en bepleitte. Molinari schatte dat er uiteindelijk verschillende particuliere politiebureaus in steden zouden komen en één particulier bureau in elk landelijk gebied. Dat lijkt mogelijk, vooral nu moderne technologie het makkelijker maakt voor grote stedelijke bedrijven om ook in afgelegen plattelandsgebieden actief te zijn. Iemand die in een klein dorp in Wyoming woont, kan kiezen voor de diensten van een lokaal beschermingsbedrijf of gebruikmaken van een nabijgelegen filiaal van de Metropolitan Protection Company.

'Maar hoe kan een arm persoon zich privébescherming veroorloven, waarvoor hij zou moeten betalen, in plaats van gratis bescherming te ontvangen, zoals nu het geval is?' Dit is een veelgehoorde kritiek op het idee van volledig particuliere politiebescherming. Een van de antwoorden is dat dit probleem geldt voor elk goed of dienst in een libertarische samenleving, en niet alleen voor de politie. Is bescherming niet noodzakelijk? Misschien, maar dat geldt ook voor voedsel, kleding, onderdak, en dergelijke. Deze zijn zeker minstens zo belangrijk, zo niet belangrijker, dan politiebescherming. Toch zegt bijna niemand dat de overheid voedsel, kleding, en onderdak moet nationaliseren en gratis moet aanbieden als verplicht monopolie. Zeer arme mensen zouden meestal worden ondersteund door particuliere liefdadigheid, zoals we zagen in het hoofdstuk over welzijn. Bovendien zijn er ongetwijfeld manieren om gratis politiebescherming aan de bevolking te bieden. Dit kan bijvoorbeeld door de politiebedrijven zelf, uit welwillendheid, zoals ziekenhuizen en artsen dat nu doen. Ook zouden er speciale 'politiehulp'-verenigingen kunnen ontstaan die vergelijkbaar werk verrichten als de huidige 'rechtshulp'-verenigingen. Deze organisaties bieden vrijwillig gratis juridisch advies aan mensen in nood die problemen hebben met de autoriteiten.

Er zijn belangrijke aanvullende overwegingen. Zoals we hebben gezien, zijn politiediensten niet 'gratis'; ze worden gefinancierd door de belastingbetaler, en vaak is die belastingbetaler de arme persoon zelf. Het is goed mogelijk dat hij nu meer belasting betaalt voor de politie dan hij zou betalen aan particuliere, en veel efficiëntere, politiebedrijven. Bovendien zouden deze bedrijven een massamarkt aanspreken. Door de schaalvoordelen van zo'n ruime markt zou politiebescherming ongetwijfeld veel goedkoper worden. Geen enkel politiebedrijf kan het zich leisten om een groot deel van zijn klantenbasis te verliezen, en de kosten van bescherming zouden niet veel hoger zijn dan de huidige verzekeringspremies. (Sterker nog, het zou veel goedkoper zijn dan de huidige verzekering, aangezien de verzekeringssector momenteel sterk wordt gereguleerd door de overheid, wat goedkope concurrentie uitsluit).

Er is nog een laatste nachtmerrie die veel mensen hebben als ze nadenken over particuliere beveiligingsbedrijven. Ze beschouwen dit als een doorslaggevende reden om het idee af te wijzen. Zouden die bureaus niet voortdurend met elkaar in conflict komen? Zou er geen 'anarchie' ontstaan, met voortdurende ruzies tussen politiekorpsen wanneer de ene persoon 'zijn' politie inschakelt en de ander 'de zijne'?

Er zijn verschillende niveaus van antwoorden op deze belangrijke vraag. Ten eerste, omdat er geen overkoepelende staat zou zijn, geen centrale of enkele lokale regering, zouden we in ieder geval gevrijwaard blijven van de ellende van oorlogen tussen staten, met hun enorme, destructieve en inmiddels nucleaire wapens. Wanneer we terugkijken in de geschiedenis, is het dan niet overduidelijk dat het aantal mensen dat omkomt bij geïsoleerde buurtconflicten vergeleken kan worden met de totale massavernietiging die voortkomt uit interstatelijke oorlogen? Daar zijn goede redenen voor. Laten we om emotionele discussies te vermijden, twee hypothetische landen bekijken: 'Ruritanië' en 'Walldavië'. Als beide landen zouden worden opgedeeld in een libertarische samenleving, zonder regering en met talloze particuliere burgers, bedrijven en politiebureaus, zouden de enige conflicten lokaal zijn. Bovendien zou de omvang en destructiviteit van wapens noodzakelijkerwijs sterk beperkt zijn. Stel je voor dat in een stad in Ruritanië twee politiebureaus met elkaar in botsing komen en beginnen te schieten. In het slechtste geval zouden zij geen massabombardementen of nucleaire vernichtung of bacteriële oorlogsvoering kunnen inzetten, omdat ze anders zichzelf in de lucht zouden blazen. Het zijn juist de territoriale gebieden die zijn onderverdeeld in enkele regeringsmonopolies die leiden tot massavernietiging. Wanneer de enkelvoudige monopolistische regering van Walldavië haar oude rivaal, de regering van Ruritanië, confronteert, kunnen beide regeringen massavernietigingswapens en zelfs nucleaire wapens gebruiken, omdat het altijd de 'andere man' en het 'andere land' zijn die ze schade toebrengen. Bovendien wordt elke persoon, als onderdaan van een monopolistische regering, in de ogen van andere regeringen onherroepelijk geïdentificeerd met 'zijn' regering. De burger van Frankrijk wordt bijvoorbeeld gezien als een vertegenwoordiger van 'zijn' regering. Daarom zal, als een andere regering Frankrijk aanvalt, zowel de burgerij als de regering van Frankrijk onder vuur komen te liggen. Maar wanneer bedrijf A het conflict aangaat met bedrijf B, kunnen alleen de klanten van deze bedrijven in het conflict worden meegesleurd, en niemand anders. Het zou dus duidelijk moeten zijn dat zelfs als het ergste zou gebeuren en een libertarische wereld inderdaad een wereld van 'anarchie' werd, we nog steeds veel beter af zouden zijn dan nu. We zouden niet overgeleverd zijn aan de genade van ongebreidelde, 'anarchistische' natiestaten, die elk een angstaanjagend monopolie op massavernietigingswapens bezitten. We moeten nooit vergeten dat we allemaal leven, en altijd hebben geleefd, in een wereld van 'inter-nationale anarchie'. Dit is een wereld van dwingende natiestaten zonder controle van een algemene wereldregering, en er is geen vooruitzicht dat deze situatie zal veranderen.

Een libertarische wereld zou, ook al is het anarchistisch, nog steeds niet lijden onder de brute oorlogen, de massavernietiging en de A-bombardementen die onze door de staat geteisterde wereld al eeuwenlang teisteren. Zelfs als de lokale politie voortdurend met elkaar in conflict komt, zouden er geen tragedies meer plaatsvinden zoals in Dresden en Hiroshima.

Maar er is nog veel meer te zeggen. We moeten nooit aannemen dat deze lokale 'anarchie' waarschijnlijk zal optreden. Laten we het probleem van politieconflicten opsplitsen in twee delen: eerlijke meningsverschillen en de pogingen van een of meerdere politiekorpsen om 'bandiet' te worden, fondsen te werven of hun heerschappij met dwang op te leggen. Laten we er even van uitgaan dat de politiekorpsen eerlijk zijn en gedreven worden door echte meningsverschillen. We laten de kwestie van de bandietenpolitie voorlopig buiten beschouwing. Een van de belangrijkste aspecten van de bescherming die de politie hun klanten biedt, is stille bescherming. Elke consument of koper van politiebescherming wil vooral efficiënte en stille bescherming, zonder conflicten of verstoringen. Elke politieorganisatie is zich ten volle bewust van dit essentiële feit. De veronderstelling dat de politie voortdurend met elkaar zou botsen en strijden, is absurd. Dit negeert het verwoestende effect dat zo'n chaotische 'anarchie' zou hebben op de activiteiten van alle politiebedrijven. Eenvoudig gezegd: zulke oorlogen en conflicten zouden extreem schadelijk zijn voor de zaken. Op de vrije markt zouden de politiebedrijven er daarom alles aan doen om conflicten te voorkomen en zouden alle meningsverschillen in privérechtbanken worden opgelost, beslist door privérechters of arbiters.

Om specifieker te zijn: in de eerste plaats zouden botsingen, zoals we al zeiden, minimaal zijn. De eigenaar van een straat zou zijn eigen bewakers hebben, de winkelier de zijne, en de huisbaas en huiseigenaar ook hun eigen politiebedrijf. Realistisch gezien zou er in het dagelijks leven weinig ruimte zijn voor directe conflicten tussen politiediensten. Maar stel je voor dat, zoals soms gebeurt, twee naburige huiseigenaren ruzie krijgen. De een beschuldigt de ander van geweldpleging en schakelt zijn eigen politiebedrijf in, terwijl ze toevallig bij verschillende bedrijven zijn aangesloten. Wat dan? Het zou zinloos en zowel economisch als fysiek zelfvernietigend zijn voor de twee politiebedrijven om op elkaar te schieten. In plaats daarvan zou elk politiebedrijf, om te kunnen blijven functioneren, als essentieel onderdeel van zijn dienstverlening het gebruik van particuliere rechtbanken of arbiters aankondigen. Zo zouden zij kunnen beslissen wie er fout zit.

## De rechtbanken

Stel je voor dat de rechter of arbiter oordeelt dat Smith in een geschil fout zat en Jones heeft aangevallen. Als Smith dit vonnis accepteert, dan zijn er, ongeacht de schadevergoeding of straf die wordt opgelegd, geen problemen voor de theorie van de libertarische bescherming. Maar wat als hij het vonnis niet accepteert? Laten we een ander voorbeeld bekijken: Jones wordt beroofd. Hij schakelt zijn politiebedrijf in om de dader op te sporen. Het bedrijf komt tot de conclusie dat een zekere Brown de crimineel is. Wat gebeurt er dan? Als Brown zijn schuld erkent, is er opnieuw geen probleem en volgt er een gerechtelijke straf, waarbij de focus ligt op het dwingen van de crimineel om het slachtoffer schadeloos te stellen. Maar wat als Brown zijn schuld ontkent?

Deze kwesties brengen ons buiten het domein van politiebescherming en naar een ander essentieel gebied van bescherming: juridische dienstverlening. Dit houdt in dat er, volgens algemeen aanvaarde procedures, een methode wordt aangeboden om vast te stellen wie de misdadiger is of wie de contractbreuk pleegt, ongeacht het soort misdrijf of geschil. Veel mensen, zelfs degenen die erkennen dat er op een vrije markt een particuliere en concurrerende politiedienst kan bestaan, verzetten zich tegen het idee van volledig particuliere rechtbanken. Hoe zouden rechtbanken überhaupt privé kunnen zijn? Hoe zouden ze geweld kunnen toepassen in een wereld zonder regering? Zouden er dan niet eindeloze conflicten en 'anarchie' ontstaan?

Ten eerste ondervinden de monopolistische overheidsrechtbanken dezelfde ernstige problemen als andere overheidsoperaties, zoals inefficiëntie en minachting voor de consument. We weten allemaal dat rechters niet gekozen worden op basis van hun wijsheid, eerlijkheid of klantgerichtheid, maar dat ze vaak politieke maquettes zijn die via het politieke proces zijn benoemd. Bovendien zijn rechtbanken monopolies. Als de rechtbanken in een stad corrupt, verraderlijk, onderdrukkend of inefficiënt worden, heeft de burger momenteel geen andere optie. De benadeelde inwoner van Deep Falls, Wyoming, is gedwongen zich te voegen naar de lokale rechtbank in Wyoming of helemaal niets te doen. In een libertarische samenleving zouden er meerdere rechtbanken en rechters beschikbaar zijn waar hij terecht kan. Er is bovendien geen reden om aan te nemen dat er zoiets als een 'natuurlijk monopolie' van rechterlijke wijsheid bestaat. De inwoner van Deep Falls zou bijvoorbeeld kunnen kiezen voor de plaatselijke afdeling van de Prudential Judicial Company.

Hoe zouden rechtbanken gefinancierd worden in een vrije samenleving? Er zijn verschillende mogelijkheden. Zo zou ieder individu zich kunnen abonneren op een juridische dienst, waarbij hij maandelijks een premie betaalt en de rechtbank inschakelt als dat nodig is. Aangezien rechtbanken waarschijnlijk veel minder vaak nodig zijn dan politieagenten, kan men ook kiezen om per gebruik te betalen wanneer de rechtbank ingeschakeld wordt. In dat geval vergoedt de crimineel of de overtreder uiteindelijk het slachtoffer of de eiser. Een derde mogelijkheid is dat rechtbanken door politiebureaus worden gebruikt om geschillen op te lossen. Er zouden zelfs 'verticaal geïntegreerde' bedrijven kunnen ontstaan die zowel politie- als justitiediensten aanbieden. De Prudential Judicial Company zou bijvoorbeeld zowel een politie- als een justitiële afdeling kunnen hebben. Uiteindelijk kan alleen de markt bepalen welke van deze methoden het meest effectief is.

We zouden beter op de hoogte moeten zijn van het toenemende gebruik van particuliere arbitrage in onze maatschappij. De overheidsrechtbanken zijn zo druk, inefficiënt en kostbaar geworden dat steeds meer partijen zich tot particuliere arbiters wenden. Dit biedt een goedkopere en minder tijdrovende manier om geschillen op te lossen. De afgelopen jaren is private arbitrage uitgegroeid tot een bloeiende en succesvolle sector. Omdat arbitrage vrijwillig is, kunnen de regels snel door de betrokken partijen zelf worden vastgesteld. Dit gebeurt zonder de complicaties van een lastig, ingewikkeld wettelijk kader dat voor iedereen geldt. Hierdoor kunnen uitspraken gedaan worden door mensen die deskundig zijn in het betreffende vakgebied of beroep. Momenteel heeft de American Arbitration Association, met het motto 'The pen is mightier than the sword', 25 regionale kantoren door het hele land. Ze beschikt over zo'n 23.000 arbiters. In 1969 voerde de vereniging meer dan 22.000 arbitrages uit. Daarnaast regelen verzekeringsmaatschappijen meer dan 50.000 claims per jaar via vrijwillige arbitrage. Steeds vaker worden privé-arbiters ook succesvol ingeschakeld bij schadeclaims door auto-ongelukken.

Men zou kunnen aanvoeren dat de beslissingen van particuliere arbiters, terwijl ze steeds meer gerechtelijke taken op zich nemen, nog altijd door rechtbanken moeten worden afgedwongen. Dit betekent dat zodra de betrokken partijen het eens zijn over een arbiter, zijn uitspraak wettelijk bindend wordt. Dit klopt, maar vóór 1920 was dit nog niet het geval. Tussen 1900 en 1920 groeide de arbitrage juist net zo snel. De moderne arbitragebeweging begon in Engeland tijdens de Amerikaanse Burgeroorlog op stoom te komen. Handelaars maakten steeds vaker gebruik van de 'privérechtbanken' die door vrijwillige arbiters waren opgericht, ook al waren de uitspraken toen nog niet wettelijk bindend. Tegen 1900 kreeg vrijwillige arbitrage ook in de Verenigde Staten steeds meer voet aan de grond. In middeleeuws Engeland ontstond de hele structuur van het koopmansrecht, dat door de overheidsrechtbanken vaak onhandig en inefficiënt werd afgehandeld, binnen particuliere koopmansrechtbanken. Deze bankiers waren puur vrijwillige arbiters en hun uitspraken waren niet wettelijk bindend. Hoe konden ze dan toch succesvol zijn?

Het antwoord is dat de kooplieden in de Middeleeuwen en tot 1920 uitsluitend vertrouwden op uitsluiting en boycot door andere kooplieden in de regio. Met andere woorden, als een koopman weigerde zich aan arbitrage te onderwerpen of een beslissing negeerde, maakten de andere kooplieden dit openbaar in de handel. Vervolgens weigerden ze zaken te doen met de recalcitrante koopman, waardoor deze snel in de problemen kwam. Wooldridge geeft een middeleeuws voorbeeld:

> Kooplieden zorgden ervoor dat hun rechtbanken functioneerden door simpelweg akkoord te gaan met de uitspraken. Een koopman die de afspraken overtrad, werd niet naar de gevangenis gestuurd, maar het was wel het einde van zijn carrière als handelaar. De naleving die zijn collega's van hem eisten en hun invloed op zijn goederen waren effectiever dan fysieke dwang. Neem bijvoorbeeld John van Homing, die zijn inkomens verdiende met de verkoop van grote hoeveelheden vis. Toen John een partij haring verkocht met de claim dat deze voldeed aan een monster van drie vaten, maar die in werkelijkheid vermengd was met stekelbaarsjes en rotte haring, werd hij gedwongen om het tekort te herstellen, anders zou hij economisch uitgesloten worden.

In moderne tijden werd uitsluiting nog effectiever. Het inzicht dat iemand die een arbitrale uitspraak negeerde, nooit meer gebruik kon maken van de diensten van een arbiter, speelde hierbij een grote rol. De industrieel Owen D. Young, hoofd van General Electric, concludeerde dat de morele afkeuring van andere zakenlieden een veel effectievere straf was dan juridische handhaving. Tegenwoordig zouden moderne technologie, computers en kredietbeoordelingen zo'n landelijke afkeuring nog effectiever maken dan ooit tevoren.

Maar zelfs als vrijwillige arbitrage voldoende is voor commerciële geschillen, hoe zit het dan met criminele activiteiten zoals overvallen, verkrachtingen en bankovervallen? In deze gevallen moeten we erkennen dat uitsluiting waarschijnlijk niet voldoende zou zijn. Het is bovendien belangrijk om te beseffen dat particuliere straateigenaren dergelijke criminelen niet in hun gebied willen toelaten. Voor criminele zaken zijn rechtbanken en wetshandhaving noodzakelijk.

Hoe zouden de rechtbanken functioneren in een libertarische samenleving? En vooral, hoe zouden ze hun beslissingen kunnen afdwingen? Bij al hun handelingen moeten ze bovendien rekening houden met de essentiële libertarische regel: er mag geen fysiek geweld worden gebruikt tegen iemand die niet als crimineel is veroordeeld. Anders zouden de gebruikers van dergelijk geweld --- of het nu de politie of de rechtbanken zijn --- zelf als daders kunnen worden gezien, mocht later blijken dat de persoon tegen wie zij geweld gebruikten onschuldig was. In tegenstelling tot statistische systemen kan geen enkele politieagent of rechter speciale immuniteit krijgen om meer dwang uit te oefenen dan ieder ander in de samenleving zou kunnen doen.

Laten we het voorbeeld nemen dat we eerder hebben besproken. Meneer Jones wordt beroofd, en zijn ingehuurde detectivebureau is van mening dat Brown de dader is. Brown weigert echter zijn schuld te erkennen. Wat nu? Ten eerste moeten we beseffen dat er op dit moment geen wereldwijd gerechtshof of een wereldregering is die haar decreten kan afdwingen. Desondanks hebben we, terwijl we in een staat van 'internationale anarchie' leven, weinig of geen problemen met geschillen tussen burgers van verschillende landen. Stel bijvoorbeeld dat een inwoner van Uruguay beweert opgelicht te zijn door een inwoner van Argentinië. Naar welke rechtbank trekt hij dan? Hij gaat naar zijn eigen rechtbank, die van het slachtoffer of die van de eiser. De zaak wordt voor de Uruguayaanse rechtbank gebracht, en de Argentijnse rechtbank erkent de uitspraak. Ditzelfde geldt als een Amerikaan meent opgelicht te zijn door een Canadees, en ga zo maar door. In het Europa na het Romeinse Rijk, waar verschillende Duitse stammen samenleefden, kon een Visigoot, als hij zich benadeeld voelde door een Frank, naar zijn eigen rechtbank stappen. De beslissing werd doorgaans door de Franken geaccepteerd. Naar de rechtbank van de eiser gaan is ook de logische libertarische manier, omdat het slachtoffer of de eiser degene is die benadeeld is en dus vanzelfsprekend zijn zaak bij zijn eigen rechtbank indient. In het geval van Jones zou hij naar de Prudential Court Company moeten gaan om Brown aan te klagen wegens diefstal.

Het is natuurlijk mogelijk dat Brown ook cliënt is van de Prudential Court. In dat geval is er geen probleem. De beslissing van de Prudential is bindend voor beide partijen. Een belangrijke regel is echter dat er geen dwingende dagvaarding tegen Brown kan worden gebruikt, omdat hij als onschuldig moet worden beschouwd totdat hij is veroordeeld. Brown zou met een vrijwillige dagvaarding worden opgeroepen. Dit is een bericht waarin staat dat hij voor de rechter moet verschijnen in verband met bepaalde aanklachten, en waarin hij of zijn wettelijke vertegenwoordiger uitgenodigd wordt om aanwezig te zijn. Als hij niet verschijnt, wordt hij bij verstek berecht. Dit is uiteraard minder gunstig voor Brown, omdat zijn kant van het verhaal dan niet in de rechtszaal naar voren zal komen. Als Brown schuldig wordt bevonden, zullen de rechtbank en haar agenten geweld gebruiken om hem te arresteren en de opgelegde straf af te dwingen. Deze straf zal in eerste instantie gericht zijn op het vergoeden van het slachtoffer.

Maar wat als Brown de Prudential Court niet erkent? Wat als hij klant is bij de Metropolitan Court Company? Dan wordt de situatie ingewikkelder. Wat gebeurt er in dat geval? Eerst doet slachtoffer Jones zijn zaak voor de Prudential Court. Als Brown onschuldig wordt bevonden, is de kwestie opgelost. Maar stel dat beklaagde Brown schuldig wordt verklaard. Doet hij niks, dan zit hij met het vonnis tegen hem. Stel nu dat Brown de zaak voorlegt aan de Metropolitan Court Company en beweert dat er sprake is van inefficiëntie of valsheid in geschrifte bij de Prudential. In dat geval behandelt Metropolitan de zaak. Als Metropolitan ook tot de conclusie komt dat Brown schuldig is, is de controverse voorbij en zal Prudential snel stappen ondernemen tegen Brown. Maar wat als Metropolitan Brown onschuldig acht aan de aanklacht? Wat gebeurt er dan? Zullen de twee rechtbanken en hun gewapende agenten de confrontatie op straat aangaan?

Nogmaals, dit zou van de rechtbanken duidelijk irrationeel en zelfdestructief gedrag zijn. Een essentieel onderdeel van hun juridische dienstverlening is het leveren van rechtvaardige, objectieve en vreedzaam functionerende beslissingen. Dit is de beste manier om achter de waarheid te komen over wie de misdaad heeft gepleegd. Als ze een beslissing nemen en vervolgens een chaotisch vuurgevecht toestaan, zou dat door hun klanten nauwelijks als waardevolle juridische dienstverlening worden gezien. Een belangrijk aspect van de dienstverlening van elke rechtbank aan haar klanten zou daarom een beroepsprocedure moeten zijn. Kortom, elke rechtbank zou ermee instemmen zich te houden aan een beroepsprocedure, vastgesteld door een vrijwillige arbiter waartoe Metropolitan en Prudential zich nu zouden wenden. De beroepsrechter zou zijn beslissing nemen en het resultaat van dit derde proces zou bindend zijn voor de schuldige. De Prudential-rechtbank zou dan overgaan tot handhaving.

Een hof van beroep! Maar is dit niet opnieuw het creëren van een verplichte monopolistische overheid? Nee, want het systeem vereist niet dat één persoon of rechtbank als hof van beroep fungeert. In de Verenigde Staten is momenteel het Hooggerechtshof het hof van beroep. De rechters van het Hooggerechtshof zijn daarmee de ultieme arbiters, ongeacht wat de eiser of de gedaagde willen. In een libertarische samenleving kunnen verschillende concurrerende privérechtbanken hun beroep doen op elke beroepsrechter die zij eerlijk, deskundig en objectief vinden. Geen enkele beroepsrechter of groep rechters zou onder dwang aan de samenleving opgelegd worden.

Hoe worden de beroepsrechters gefinancierd? Er zijn verschillende mogelijkheden, maar de meest voor de hand liggende is dat ze worden betaald door de oorspronkelijke rechtbanken. Deze rechtbanken zouden hun klanten kunnen laten bijdragen in hun premies of vergoedingen voor de diensten in hoger beroep.

Maar stel je voor dat Brown blijft aandringen op nog een rechter in hoger beroep, en dan nog een? Kan hij dan niet aan zijn vonnis ontsnappen door maar door te procederen? Het is duidelijk dat juridische procedures in elke maatschappij niet eindeloos kunnen doorgaan; er moet een eindpunt zijn. In de huidige statistische samenleving, waar de overheid de rechterlijke macht monopoliseert, is het Hooggerechtshof willekeurig aangewezen als dat eindpunt. In een libertarische samenleving moet er ook een afgesproken scheidslijn zijn. Aangezien er bij een misdaad of geschil slechts twee partijen betrokken zijn - de eiser en de gedaagde - lijkt het logisch om in de regelgeving vast te leggen dat een beslissing van twee willekeurige rechtbanken bindend is. Dit dekt zowel de situatie waarin de rechtbank van de eiser als die van de gedaagde tot dezelfde beslissing komen, als het geval waarin een hof van beroep oordeelt over een meningsverschil tussen de twee oorspronkelijke rechtbanken.

## ## DE WET EN DE RECHTBANKEN

Een hof van beroep! Maar betekent dit niet opnieuw dat we een verplichte, monopolistische overheid creëren? Nee, want het systeem verplicht ons niet om één persoon of rechtbank als hof van beroep aan te wijzen. Momenteel fungeert in de Verenigde Staten het Hooggerechtshof als dat hof, waardoor de rechters van het Hooggerechtshof de uiteindelijke beslissingen nemen, ongeacht wat de eiser of de gedaagde willen. In een libertarische samenleving hebben verschillende concurrerende privérechtbanken de vrijheid om een beroepsrechter te kiezen die zij eerlijk, deskundig en objectief vinden. Geen enkele beroepsrechter of groep rechters zou aan de samenleving opgelegd worden. Hoe worden de beroepsrechters gefinancierd? Er zijn verschillende mogelijkheden, maar de meest voor de hand liggende is dat zij betaald worden door de oorspronkelijke rechtbanken. Deze rechtbanken zouden hun klanten kunnen laten bijdragen aan de premies of vergoedingen voor de diensten in hoger beroep. Maar stel je voor dat Brown blijft aandringen op meer rechters in hoger beroep. Kan hij dan niet blijven procederen en zo aan zijn vonnis ontsnappen? Het is duidelijk dat juridische procedures in elke maatschappij niet eindeloos kunnen doorgaan; er moet een eindpunt zijn. In de huidige samenleving, waar de overheid de rechterlijke macht monopoliseert, is het Hooggerechtshof gekozen als dat eindpunt. Ook in een libertarische samenleving moet er een gezamenlijke grens zijn. Aangezien bij een misdaad of geschil maar twee partijen betrokken zijn -- de eiser en de gedaagde -- lijkt het logisch om vast te leggen in de regelgeving dat een beslissing van twee willekeurige rechtbanken bindend is. Dit dekt zowel de situatie waarin de rechtbank van de eiser als die van de gedaagde tot dezelfde beslissing komen, als het geval waarin een hof van beroep oordeelt over een meningsverschil tussen de twee oorspronkelijke rechtbanken.

Het is nu duidelijk dat er een rechtscode moet komen in de libertarische samenleving. Maar hoe? Hoe kan er een wetboek zijn en een rechtssysteem zonder een regering die het uitgeeft, een aangewezen groep rechters, of een wetgevende macht die over wetten stemt? Om te beginnen, is een wet wel in overeenstemming met de libertarische principes?

Om eerst de laatste vraag te beantwoorden: het is duidelijk dat een wetboek nodig is om precieze richtlijnen vast te leggen voor de privérechtbanken. Als rechtbank A bijvoorbeeld beslist dat alle roodharigen van nature slecht zijn en gestraft moeten worden, dan is het evident dat zulke uitspraken in strijd zijn met de libertarische principes. Een dergelijke wet zou een inbreuk vormen op de rechten van roodharigen en daarom onwettig zijn volgens het libertarische beginsel. De rest van de samenleving zou hier ook niet achter kunnen staan. Daarom is het noodzakelijk om een wettelijke code te hebben die algemeen geaccepteerd wordt en waar de rechtbanken zich aan houden. De wet zou nadrukkelijk het libertarische principes van geen agressie tegen personen of eigendom moeten benadrukken, eigendomsrechten definiëren conform deze principes, bewijsregels opstellen (zoals die nu bestaan) om te bepalen wie de verantwoordelijke partij is in een geschil, en een code opstellen met maximale straffen voor specifieke misdrijven. Binnen zo'n framework zouden de rechtbanken met elkaar concurreren op het gebied van de meest efficiënte procedures. De markt zou dan bepalen of rechters, jury's, en andere juridische structuren de meest efficiënte methoden zijn om juridische diensten te verlenen.

Zijn zulke stabiele en consistente wetboeken mogelijk, met alleen concurrerende rechters om ze te ontwikkelen en toe te passen, en zonder regering of wetgevende macht? Ja, ze zijn niet alleen mogelijk, maar de beste en meest succesvolle onderdelen van ons rechtssysteem zijn door de jaren heen juist op deze manier ontstaan. Wetgevende machten en koningen zijn vaak grillig, invasief en inconsequent geweest. Ze hebben juist anomalieën en despotisme in het rechtssysteem geïntroduceerd. In feite is de regering net zo min gekwalificeerd om wetten te ontwikkelen en toe te passen als om andere diensten te verlenen. Net zoals religie van de staat is gescheiden en de economie van de staat dat kan zijn, kunnen ook andere staatsfuncties zoals politie, rechtbanken en de wet zelf ditzelfde pad volgen.

Zoals eerder aangegeven, werd het hele koopmansrecht niet door de staat of in staatsrechtbanken ontwikkeld, maar door particuliere koopmansrechtbanken. Pas veel later nam de overheid het koopvaardijrecht over van de ontwikkeling die had plaatsgevonden in de koopmansrechtbanken. Het zelfde gebeurde met het admiraliteitsrecht en de hele structuur van het zeerecht, waaronder scheepvaart, berging, enzovoort. Ook hier was de staat niet geïnteresseerd en had hij geen jurisdictie op volle zee. Daarom namen de schippers zelf de verantwoordelijkheid om het zeerecht niet alleen toe te passen, maar ook verder uit te werken in hun eigen privérechtbanken. Pas later eigende de overheid zich het admiraliteitsrecht toe voor haar eigen rechtbanken.

Tot slot werd het belangrijkste Angelsaksische recht, het gerechtvaardigd geachte gewoonterecht (common law), door de eeuwen heen ontwikkeld door concurrerende rechters die oude principes toepasten in plaats van de veranderende decreten van de staat. Deze principes werden niet willekeurig vastgesteld door een koning of wetgever; ze groeiden door de eeuwen heen door rationele en vaak libertarische principes toe te passen op de zaken die aan hen werden voorgelegd. Het idee om precedenten te volgen kwam voort uit de wetenschap dat rechters uit het verleden hun beslissingen hadden genomen door de algemeen aanvaarde common law-principes toe te passen op specifieke gevallen en problemen. Er was algemeen consensus dat de rechter geen wetten maakte (zoals vaak het geval is in de huidige tijd); de verantwoordelijkheid van de rechter, zijn expertise, lag in het vinden van de wet binnen de geaccepteerde common law-principes en het toepassen van die wet op specifieke gevallen of op nieuwe technologische of institutionele omstandigheden. De roem van de eeuwenlange ontwikkeling van de common law getuigt van hun succes.

De rechters van het common law leken bovendien veel op particuliere arbiters, die als experts in de wet fungeerden. Partijen gingen naar hen toe met hun geschillen. Er was geen opgelegd 'hooggerechtshof' wiens beslissing bindend was, en precedent, hoewel gerespecteerd, werd niet automatisch als bindend beschouwd. Zo schreef de libertarische Italiaanse jurist Bruno Leoni:

> De rechtbanken in Engeland konden niet zomaar arbitraire regels uitvaardigen. Ze bevonden zich nooit in de positie om dit rechtstreeks te doen, zoals wetgevers dat gewoonlijk deden, op een plotselinge, wijdverspreide en dwingende manier. Bovendien waren er zoveel rechtbanken in Engeland, en waren ze zo jaloers op elkaar, dat zelfs het beroemde principe van het bindende precedent pas in relatief recente tijden openlijk door hen werd erkend. Daarnaast konden ze alleen beslissingen nemen over zaken die eerder door privépersonen aan hen waren voorgelegd. Tot slot waren er relatief weinig mensen die naar de rechtbanken gingen om hen te vragen naar de regels die op hun situaties van toepassing waren.
>
> En over de afwezigheid van 'hooggerechtshoven':
>
> Het kan niet worden ontkend dat de wet op de advocatuur of de rechterlijke macht de neiging heeft om wetgevende kenmerken te vertonen. Dit omvat ook ongewenste aspecten, vooral wanneer juristen of rechters in laatste instantie over een zaak moeten beslissen. In onze tijd leidt het systeem van de rechterlijke macht, in landen met 'hooggerechtshoven', er soms toe dat de persoonlijke standpunten van de leden van deze hoven, of van een meerderheid daarvan, worden opgelegd aan alle andere betrokkenen. Dit gebeurt vaak als er veel onenigheid bestaat tussen hun mening en de overtuigingen van anderen. Deze mogelijkheid is echter, verre van een onvermijdelijk kenmerk van het juristenrecht of het gerechtelijk recht, eerder een afwijking ervan.^5

Afgezien van dergelijke afwijkingen waren de persoonlijke opvattingen van de rechters tot een minimum beperkt. Dit kwam doordat: (a) rechters alleen beslissingen konden nemen wanneer particuliere burgers zaken bij hen indienen; (b) de beslissingen van elke rechter alleen betrekking hadden op het specifieke geval; en (c) de rechters en advocaten altijd de juridische geschiedenis in overweging namen. Bovendien merkt Leoni op dat rechters, in tegenstelling tot wetgevende of uitvoerende instanties waar dominante meerderheden vaak minderheden negeren, door hun rol verplicht zijn de argumenten van beide partijen te horen en te wegen. 'Partijen staan gelijk ten opzichte van de rechter, omdat ze vrij zijn om argumenten en bewijzen in te dienen. Ze vormen geen groep waarin afwijkende minderheden het afleggen tegen zegevierende meerderheden.' Leoni wijst ook op de overeenkomst met een vrije markteconomie: 'Argumenten kunnen inderdaad sterker of zwakker zijn, maar het feit dat elke partij deze kan aandragen, is vergelijkbaar met het idee dat iedereen individueel met iedereen kan concurreren op de markt om te kopen en verkopen.'^6

Professor Leoni ontdekte dat de oude Romeinse rechters in het privaatrecht op dezelfde manier te werk gingen als de rechtbanken van de Engelse common law:

> De Romeinse jurist was in wezen een wetenschapper. Hij bestudeerde oplossingen voor zaken die burgers hem voorlegden, vergelijkbaar met hoe industriëlen tegenwoordig een natuurkundige of ingenieur om hulp vragen bij technische problemen in hun fabrieken of productieprocessen. Het Romeinse privaatrecht was dus iets dat beschreven of ontdekt moest worden, niet iets dat simpelweg werd uitgevaardigd. Het vormde een wereld van bestaande zaken, deel van het gemeenschappelijke erfgoed van alle Romeinse burgers. Niemand vaardigde dit recht uit en niemand kon het veranderen door een persoonlijke wil. Dit is het lange-termijnconcept, of het Romeinse concept, van de zekerheid van de wet.^7

Tot slot kon professor Leoni zijn kennis van het oude recht en het gewoonterecht inzetten om de belangrijke vraag te beantwoorden: In een libertarische samenleving, 'wie zal de rechters benoemen?'

...om hen de taak te laten uitvoeren om de wet te definiëren?' Zijn antwoord was: de mensen zelf. Mensen die naar de rechters zouden gaan met de beste reputatie op het gebied van deskundigheid en wijsheid in het kennen en toepassen van de fundamentele juridische principes die in de samenleving gelden.

> In feite is het niet van groot belang wie de rechters benoemt, omdat in zekere zin iedereen dat zou kunnen doen. Dit gebeurt al tot op zekere hoogte wanneer mensen particuliere bemiddelaars inschakelen om hun geschillen te beslechten. Het aanstellen van rechters is immers geen bijzonder probleem, zoals het 'aanstellen' van natuurkundigen, artsen of andere deskundigen. Het ontstaan van goede professionals in een samenleving lijkt alleen te danken aan officiële benoemingen, als die er al zijn. In werkelijkheid berust het op de brede instemming van klanten, collega's en het grote publiek. Zonder deze instemming is geen enkele benoeming echt effectief. Natuurlijk kunnen mensen zich vergissen in de waarde die ze aan iemand toekennen, maar deze moeilijkheden zijn onvermijdelijk bij elke vorm van keuze. ^8

Natuurlijk zou in een toekomstige libertarische samenleving de basiswetgeving niet zomaar gebaseerd zijn op gewoonten, zeker niet als veel daarvan antilibertarisch van aard is. Het wetboek zou moeten worden opgesteld op basis van erkende libertarische principes, zoals het beginsel van non-agressie tegen de persoon of het eigendom van anderen. Kortom, het zou moeten steunen op de rede in plaats van op traditie, hoe goed die ook moge zijn. Aangezien we echter beschikken over een corpus van common law-principes om uit te putten, zou het corrigeren en aanpassen van de common law een stuk eenvoudiger zijn dan het vanuit het niets ontwikkelen van een nieuw geheel aan systematische juridische principes.

Het meest opmerkelijke historische voorbeeld van een samenleving met libertarische wetten en rechtbanken is echter tot voor kort door historici verwaarloosd. Deze samenleving had niet alleen libertaire rechtbanken en wetten, maar opereerde ook volledig zonder een staat. We hebben het hier over het oude Ierland -- een Ierland dat ongeveer duizend jaar lang dit libertarische pad volgde, tot de brutale verovering door Engeland in de zeventiende eeuw. In tegenstelling tot veel primitieve stammen die op een vergelijkbare manier functioneerden, zoals de Ibo's in West-Afrika en verschillende Europese stammen, was het Ierland van vóór de verovering in geen enkel opzicht 'primitief'. Het was juist een zeer complexe samenleving die eeuwenlang de meest geavanceerde, meest geleerde en meest beschaafde van heel West-Europa was.

Duizend jaar lang kende het oude Keltische Ierland geen staat of iets dat daarop leek. Zoals de belangrijkste autoriteit op het gebied van het oude Ierse recht eens opmerkte: 'Er was geen wetgevende macht, geen deurwaarders, geen politie, geen openbare handhaving van het recht... Er was geen spoor van door de staat bestuurde rechtspraak.'^9

Hoe werd rechtvaardigheid dan gewaarborgd? De politieke basiseenheid van het oude Ierland was de tuath. Alle 'vrije mensen' die grond bezaten, evenals beroepsbeoefenaars en ambachtslieden, hadden het recht om lid te worden van een tuath. De leden van elke tuath kwamen jaarlijks bijeen om gezamenlijk besluiten te nemen over gemeenschappelijk beleid, oorlog of vrede te verklaren tegen andere tuatha en hun 'koningen' te kiezen of af te zetten. Een belangrijk punt is dat, in tegenstelling tot primitieve stammen, niemand vastzat of gebonden was aan een specifieke tuath, noch door verwantschap, noch door geografische ligging. Individuele leden waren vrij om zich af te scheiden van een tuath en zich aan te sluiten bij een concurrerende tuath, iets dat regelmatig gebeurde. Het kwam zelfs voor dat twee of meer tuatha besloten om samen te smelten tot een enkele, efficiëntere eenheid. Zoals professor Peden opmerkt: 'De tuath is dus een lichaam van personen die vrijwillig verenigd zijn voor sociaal nuttige doeleinden, en de som van de landeigendommen van haar leden vormde haar territoriale dimensie.'^10 Kortom, ze beschikten niet over een moderne staat met een aanspraak op soevereiniteit over een specifiek (meestal uitbreidend) grondgebied, dat gescheiden was van de landeigendomsrechten van zijn onderdanen. Tuatha waren daarentegen vrijwillige verenigingen die alleen de eigendommen van hun vrijwillige leden omvatten. In Ierland bestonden er op elk moment ongeveer 80 tot 100 tuatha naast elkaar.

Maar hoe zit het met de gekozen 'koning'? Was hij een soort staatsheerser? De koning fungeerde vooral als een religieuze hogepriester, die de erediensten van de tuath leidde. Deze tuath was een vrijwillige religieuze, sociale en politieke organisatie. Net als in heidense, voorchristelijke priesterrijken was de koningsfunctie erfelijk. De koning werd gekozen door de tuath uit een koninklijke verwantengroep, de derbfine, die deze erfelijke priestelijke rol vervulde. Politiek gezien waren de functies van de koning echter strikt beperkt. Hij was de militaire leider van de tuath en voorzat de vergaderingen. Oorlog voeren of vredesonderhandelingen kon hij alleen als vertegenwoordiger van de vergadering. Hij was op geen enkele manier soeverein en had geen rechten om recht te spreken over de leden van de tuath. Daarnaast mocht hij zelf geen recht spreken; als hij partij was in een rechtszaak, moest hij zijn zaak voorleggen aan een onafhankelijke rechter.

Nogmaals, hoe werd het recht dan ontwikkeld en gehandhaafd? In de eerste plaats was de wet gebaseerd op eeuwenoude gebruiken die mondeling werden doorgegeven en later schriftelijk zijn vastgelegd door een groep professionele juristen, de brehons. De brehons waren geen openbare of overheidsfunctionarissen; ze werden simpelweg geselecteerd door de partijen in een geschil, op basis van hun reputatie op het gebied van wijsheid, kennis van het gewoonterecht en de integriteit van hun beslissingen. Zoals professor Peden opmerkt:

> De professionele juristen werden door partijen in geschillen geraadpleegd voor advies over de inhoud van de wet in specifieke gevallen. Deze juristen traden vaak ook op als scheidsrechters tussen rechtzoekenden. Ze bleven te allen tijde privépersonen en waren geen ambtenaren. Hun functioneren hing af van hun kennis van de wet en de integriteit van hun juridische reputatie. ^11

Bovendien hadden de brehons geen enkele connectie met de individuele tuatha of hun koningen. Ze waren volledig onafhankelijk en nationaal georiënteerd, en werden ingeschakeld door geschilpunten in heel Ierland. Een belangrijk punt is dat de brehon, in tegenstelling tot het systeem van Romeinse privéadvocaten, de enige was die er was; er waren geen andere rechters, geen 'openbare' rechters van welke aard dan ook in het oude Ierland.

Het waren de brehons die geschoold waren in de wet en die glans en toepassing aan de wet gaven, aangepast aan veranderende omstandigheden. Daarnaast was er geen monopolie van de brehon-juristen; er waren verschillende concurrerende scholen van jurisprudentie die streden om de gewoonten van het Ierse volk.

Hoe werden de beslissingen van de brehons afgedwongen? Dit gebeurde via een uitgebreid, vrijwillig ontwikkeld systeem van 'borgstelling'. Mensen waren met elkaar verbonden door verschillende borgstellerrelaties, waarmee ze elkaar garanties boden voor het rechtzetten van misstanden en de handhaving van gerechtigheid, evenals de beslissingen van de brehons. Kort samengevat waren de brehons zelf niet betrokken bij de uitvoering van hun beslissingen; die verantwoordelijkheid lag bij privépersonen die door borgstelling met elkaar verbonden waren. Er bestonden verschillende soorten borgstellers. Een borgsteller stond bijvoorbeeld met zijn eigen bezittingen garant voor de betaling van een schuld. In dat geval voegde hij zich bij de eiser om een vonnis uit te voeren wanneer de schuldenaar weigerde te betalen. In zo'n situatie moest de schuldenaar een dubbele schadevergoeding betalen: een aan de oorspronkelijke schuldeiser en een aan zijn borgsteller. Dit systeem gold voor alle overtredingen, agressies en aanrandingen, maar ook voor commerciële overeenkomsten. Kortom, het was van toepassing op alle gevallen die wij 'burgerlijk' en 'strafrecht' zouden noemen. Alle criminelen werden gezien als 'schuldenaars' die restitutie en compensatie verschuldigd waren aan hun slachtoffers, die daarmee hun 'schuldeisers' werden. Het slachtoffer verzamelden zijn borgstellers om zich heen en ging verder met het aanhouden van de misdadiger of het publiekelijk aankondigen van zijn beschuldigingen. Hij eiste dat de gedaagde zich overgaf aan de berechting van hun geschil bij de brehons. De misdadiger kon zijn eigen borgstellers sturen om te onderhandelen over een schikking, of instemmen om het geschil voor te leggen aan de brehons. Weigerde hij dit, dan werd hij door de hele gemeenschap als 'vogelvrij' beschouwd; hij kon dan geen enkele eigen vordering meer afdwingen in de rechtbanken en werd door de gemeenschap met afkeuring bejegend. ^12

Er waren zeker af en toe 'oorlogen' in de duizend jaar dat Keltisch Ierland bestond, maar deze bestonden vaak uit kleine gevechten die verwaarloosbaar waren in vergelijking met de verwoestende oorlogen die de rest van Europa teisterden. Zoals professor Peden opmerkt,

> Zonder het dwangapparaat van de staat, die via belastingen en dienstplicht grote hoeveelheden wapens en mankracht kan mobiliseren, waren de Ieren niet in staat om een grootschalig leger langdurig in het veld te houden. Ierse oorlogen waren, vergeleken met Europese maatstaven, armzalige vechtpartijen en veediefstallen.

Hierboven hebben we aangegeven dat het theoretisch en historisch heel goed mogelijk is om een efficiënte en hoffelijke politie, competente en goed opgeleide rechters en een systematische en sociaal geaccepteerde wetgeving te hebben, zonder dat een dwingende overheid hierbij betrokken is. De overheid, die een verplicht monopolie op bescherming over een geografisch gebied opeist en haar inkomsten met geweld verwerft, kan worden gescheiden van het hele spectrum van bescherming. De overheid is net zo min noodzakelijk voor het leveren van vitale beschermingsdiensten als voor andere taken. Bovendien hebben we nog niet benadrukt dat er een cruciaal feit is over de overheid: haar verplichte monopolie op de wapens van dwang heeft door de eeuwen heen geleid tot ontelbare slachtpartijen en veel grotere tirannie en onderdrukking dan enige gedecentraliseerde, particuliere instantie ooit zou kunnen bewerkstelligen. Als we kijken naar het zwarte record van massamoord, uitbuiting en tirannie dat overheden door de eeuwen heen op de samenleving hebben uitgeoefend, hoeven we niet terughoudend te zijn in onze beslissing om de Leviathaanse staat te verlaten en te streven naar vrijheid.

## Criminele beschermers

Er waren ongetwijfeld af en toe 'oorlogen' in de duizend jaar dat Keltisch Ierland bestond, maar deze bestonden vaak uit kleine gevechten die te verwaarlozen waren in vergelijking met de verwoestende oorlogen die de rest van Europa teisteren. Zoals professor Peden opmerkt: zonder het dwangapparaat van de staat, dat via belastingen en dienstplicht grote hoeveelheden wapens en mankracht kan mobiliseren, waren de Ieren niet in staat om een grootschalig leger langdurig in het veld te houden. Ierse oorlogen waren, gemeten naar Europese maatstaven, armzalige gevechten en veediefstallen. We hebben hierboven aangegeven dat het zowel theoretisch als historisch heel goed mogelijk is om een efficiënte en hoffelijke politie, competente en goed opgeleide rechters, en een systematische en sociaal geaccepteerde wetgeving te hebben, zonder tussenkomst van een dwingende overheid. De overheid, die een verplicht monopolie op bescherming over een bepaald geografisch gebied opeist en haar inkomsten met geweld verwerft, kan eigenlijk gescheiden worden van het hele domein van bescherming. De overheid is niet meer nodig voor het leveren van essentiële beschermingsdiensten dan voor andere taken. Bovendien willen we nog benadrukken dat er een cruciaal feit is over de overheid: haar verplichte monopolie op dwang heeft door de eeuwen heen geleid tot ontelbare slachtpartijen en veel grotere tirannie en onderdrukking dan welke gedecentraliseerde particuliere instantie dan ook ooit zou kunnen veroorzaken. Als we kijken naar het treurige verleden van massamoord, uitbuiting en tirannie dat overheden door de geschiedenis heen op de samenleving hebben uitgeoefend, hoeven we niet terughoudend te zijn in onze keuze om de Leviathaanse staat achter ons te laten en te streven naar vrijheid.

We hebben het moeilijkste probleem voor het laatst bewaard: wat als de politie, rechters en rechtbanken oneerlijk en partijdig zijn? Wat als ze hun beslissingen bijvoorbeeld bevoordelen op basis van financiële invloed van rijke cliënten? We hebben aangetoond hoe een libertarisch juridisch en gerechtelijk systeem zou kunnen functioneren binnen een pure vrije markt, waarin eerlijke meningsverschillen centraal staan. Maar wat als één of meerdere politieagenten of rechtbanken in de praktijk vogelvrij worden? Wat nu?

Libertariërs deinzen niet terug voor deze vragen. In tegenstelling tot utopisten zoals marxisten of linkse anarchisten (anarchocommunisten of anarcho-syndicalisten) gaan zij er niet van uit dat de komst van de ideale vrije maatschappij automatisch een nieuwe, magisch getransformeerde libertarische mens met zich meebrengt. Ze verwachten niet dat de leeuw vredig naast het lam zal liggen of dat niemand kwaadwillende of frauduleuze bedoelingen zal hebben ten opzichte van zijn buurman. Natuurlijk geldt: hoe 'beter' de mensen zijn, hoe beter elk sociaal systeem zal functioneren. Dat betekent ook dat de politie en de rechtbanken minder werk te doen zullen hebben. Maar libertariërs nemen deze aanname niet als vanzelfsprekend aan. Wat wij beweren, is dat, ongeacht de mate van 'goedheid' of 'slechtheid' onder de mensen, een puur libertarische samenleving tegelijkertijd de meest morele, efficiënte, minst criminele en veiligste is voor zowel de persoon als zijn eigendom.

Laten we eerst kijken naar het probleem van de oneerlijke of corrupte rechter of rechtbank. Wat als een rechtbank haar eigen rijke klant bevoordeelt? In de eerste plaats is zo'n bevoordeling uiterst onwaarschijnlijk, vanwege de voordelen en beloningen van de vrije markteconomie. Het bestaan van de rechtbank en het inkomen van een rechter hangen af van zijn reputatie op het gebied van integriteit, eerlijkheid, objectiviteit en het zoeken naar de waarheid in elke zaak. Dit is zijn 'merknaam'. Als er ook maar iets uitlekt over oneerlijkheid, verliest hij direct klanten. De rechtbanken zullen dan ook geen klanten meer hebben, want zelfs cliënten die zelf crimineel zijn, zullen nauwelijks een rechtbank sponsoren die niet serieus genomen wordt door de rest van de samenleving. Ook als zij zelf in de gevangenis zitten vanwege oneerlijke en frauduleuze handelingen, zullen zij niet investeren in een rechtbank met een gebrek aan geloofwaardigheid. Neem bijvoorbeeld Joe Zilch, die beschuldigd wordt van een misdaad of contractbreuk en naar een 'rechtbank' gaat onder leiding van zijn zwager. Niemand, zeker andere eerlijke rechtbanken niet, zal de beslissing van deze 'rechtbank' serieus nemen. In de ogen van iedereen behalve Joe Zilch en zijn familie zal het niet meer als een 'rechtbank' worden beschouwd.

Vergelijk dit ingebouwde correctiemechanisme eens met de huidige overheidsrechtbanken. Rechters worden voor lange termijnen benoemd of gekozen, soms zelfs levenslang. Ze hebben het monopolie op de besluitvorming in hun specifieke gebied. Het is bijna onmogelijk om iets te doen aan de oneerlijke beslissingen van rechters, behalve in gevallen van grove corruptie. Jaar na jaar blijft hun macht om beslissingen te nemen en uit te voeren ongecontroleerd. Hun salarissen worden betaald, onder dwang van de ongelukkige belastingbetaler. In een volledig vrije maatschappij zorgt echter elke verdenking van een rechter of rechtbank ervoor dat hun klanten verdwijnen en dat hun 'beslissingen' niet meer serieus worden genomen. Dit systeem is veel efficiënter om rechters eerlijk te houden dan het huidige mechanisme van de overheid.

Bovendien zou de verleiding tot oneerlijkheid en partijdigheid om een andere reden veel kleiner zijn: bedrijven in de vrije markt verdienen hun geld niet door rijke klanten te bedienen, maar door een massamarkt van consumenten. Macy's haalt haar omzet uit de brede bevolking, niet uit een handvol rijke klanten. Dit geldt vandaag de dag ook voor Metropolitan Levensverzekeringen, en hetzelfde zou morgen gelden voor ieder 'Metropolitan'-rechtssysteem. Het zou namelijk onzinnig zijn voor rechtbanken om het verlies van de steun van de meerderheid van hun klanten te riskeren voor de gunsten van enkele rijke klanten. Dit staat in schril contrast met het huidige systeem, waar rechters, net als andere politici, afhankelijk kunnen zijn van rijke donateurs die de campagnes van hun politieke partijen financieren.

Er bestaat een mythe dat het 'Amerikaanse systeem' een uitstekende reeks 'checks and balances' biedt. Daarbij zouden de uitvoerende macht, de wetgevende macht en de rechtbanken elkaar in evenwicht houden en controleren, zodat de macht zich niet onnodig verzamelt in handen van enkelen. Maar in werkelijkheid is het Amerikaanse systeem van 'checks and balances' grotendeels bedrog. Elke instelling vormt namelijk een dwangmonopolie binnen zijn eigen domein, en ze maken allemaal deel uit van één overheid, die op elk moment wordt geleid door één politieke partij.

Bovendien zijn er in het beste geval maar twee partijen die dicht bij elkaar staan in ideologie en personeel. Ze werken vaak samen, en de dagelijkse gang van zaken van de overheid wordt geleid door een ambtenarenbureaucratie die niet door de kiezers kan worden veranderd. Stel je deze mythische checks and balances tegenover de echte checks and balances van de vrije markteconomie! Wat zorgt ervoor dat A&P eerlijk blijft, is de werkelijke en potentiële concurrentie van Safeway, Pioneer en talloze andere kruidenierswinkels. Hun eerlijkheid komt voort uit de mogelijkheid voor consumenten om hun klantenkring te verlaten. Wat rechters en rechtbanken in de vrije markt eerlijk zou houden, is de optie om naar een andere rechter of rechtbank te gaan als er twijfels zijn over een bepaalde rechters of rechtbank. De aanzienlijke kans dat klanten hun diensten intrekken, zou hen ook eerlijk houden. Dit zijn de echte, actieve checks and balances van de vrije markteconomie en de vrije samenleving.

Dezelfde analyse geldt voor de mogelijkheid dat een particuliere politiemacht crimineel wordt, haar dwangmiddelen gebruikt om betalingen af te dwingen of zelfs een afpersingstruc opzet om slachtoffers uit te schakelen. Natuurlijk is dat niet uitgesloten. Maar in tegenstelling tot de huidige maatschappij zouden er meteen controles en tegenwichten aanwezig zijn. Er zouden andere politiekorpsen zijn die hun wapens kunnen gebruiken om samen te werken en de agressors tegen hun klanten aan te pakken. Als de Metropolitan Police Force inderdaad gangsters zou worden en een afpersing zou eisen, dan zou de rest van de samenleving zich kunnen wenden tot de politie van Prudential of Equitable. Zij zouden zich kunnen verenigen om deze gangsters te bestrijden. Dit staat in schril contrast met de situatie waarin de staat zich bevindt. Wanneer een groep gangsters het staatsapparaat overneemt, dat beschikt over het monopolie op geweld, is er op dat moment niets dat hen kan tegenhouden, behalve het uiterst complexe proces van een revolutie. In een libertarische samenleving zou er geen massale revolutie nodig zijn om de plunderingen van gangsterstaten te stoppen. In plaats daarvan zou er snel een beroep gedaan kunnen worden op eerlijke politiediensten om de criminele macht te controleren en te verwerpen.

En inderdaad, wat is de staat eigenlijk anders dan georganiseerde misdaad? Wat is belastingheffing anders dan diefstal op enorme, ongecontroleerde schaal? Wat is oorlog anders dan massamoord op een schaal die een particuliere politiemacht nooit zou kunnen bereiken? Wat is dienstplicht anders dan dwangmatige onderwerping? Kan iemand zich voorstellen dat een particuliere politiemacht wegkomt met een fractie van wat staten doen, en dat ook nog eens jaar na jaar, eeuw na eeuw?

Er is nog een andere belangrijke overweging die het voor een criminele politiemacht bijna onmogelijk zou maken om zich te gedragen zoals moderne regeringen. Een van de cruciale factoren die regeringen in staat stelt om de vreselijke dingen te doen die ze vaak doen, is het gevoel van legitimiteit bij het publiek. De gemiddelde burger hoeft de beleidsmaatregelen van zijn regering misschien niet leuk te vinden of zelfs tegen te zijn, maar hij is doordrenkt van het idee - zorgvuldig ingeprent door eeuwen van regeringspropaganda - dat de regering de legitieme soeverein is. Het zou slecht of zelfs stapelgek zijn om haar dictaten te negeren. Dit gevoel van legitimiteit is door de eeuwen heen gekoesterd door de intellectuelen van de staat, ondersteund door allerlei middelen om legitimiteit te creëren: vlaggen, rituelen, ceremonies, onderscheidingen, grondwetten, enzovoort. Een bende van criminelen - zelfs als alle politiekorpsen zich zouden verenigen in één grote bende - zou nooit een dergelijke legitimiteit kunnen afdwingen. Het publiek zou hen simpelweg als bandieten beschouwen. Hun afpersingen en 'eerbetuigingen' zouden niet als legitieme belasting worden gezien die je automatisch moet betalen. Het publiek zou zich snel verzetten tegen deze onrechtmatige eisen en de bandieten zouden worden tegengehouden en omvergeworpen. Zodra het publiek de geneugten, welvaart, vrijheid en efficiëntie van een libertarische, staatloze samenleving heeft ervaren, wordt het bijna onmogelijk voor een staat om het publiek nog aan zich te binden. Als je eenmaal volledig van de vrijheid hebt genoten, is het geen gemakkelijke opgave om mensen te dwingen dit op te geven.

Maar stel je eens voor dat, ondanks al deze handigheidjes en obstakels, ondanks de liefde voor hun pas ontdekte vrijheid en de inherente checks and balances van de vrije markt, de staat er toch in slaagt om zichzelf te herstellen. Wat dan? Het enige wat dan zou gebeuren, is dat we weer een staat zouden hebben. We zouden er niet slechter voor staan dan nu met onze huidige staat. En zoals een libertaire filosoof het verwoordde: 'De wereld zal tenminste een glorieuze vakantie hebben gehad.' De klinkende belofte van Karl Marx geldt veel meer voor een libertarische samenleving dan voor het communisme: door vrijheid te omarmen en de staat af te schaffen, hebben we niets te verliezen en alles te winnen.

## # Nationale Defensie

De staat wordt vaak gezien als de hoeder van de nationale defensie. Maar wat betekent dat eigenlijk? Voor velen lijkt het erop dat nationale defensie voornamelijk draait om militaire macht en wapengekletter. Maar is het niet veel meer dan dat? Is de rol van de staat in de nationale defensie niet eerder een poging om controle uit te oefenen over haar burgers? Wanneer we kijken naar de geschiedenis, zien we dat de meeste conflicten niet zozeer voortkwamen uit een oprechte noodzaak om het volk te beschermen, maar eerder uit politieke ambities en machtsstrategieën. De meeste oorlogen zijn gevoerd om territorium te veroveren of economische voordelen te behalen. Als we de staat beschouwen als een georganiseerde entiteit die voortdurend zijn invloed wil uitbreiden, kunnen we hieruit de conclusie trekken dat de nationale defensie vaak een dekmantel is voor andere belangen. Bovendien zijn er veel alternatieven voor de traditionele staatgerichte aanpak van defensie. In een libertarische samenleving zouden gemeenschappen zelf verantwoordelijk zijn voor hun bescherming. Dit betekent dat burgers actief betrokken zijn en samen beslissen hoe ze hun veiligheid willen waarborgen. Daarbij komt ook de vraag van efficiëntie en effectiviteit. Is een grote, bureaucratische defensiemacht wel de beste oplossing voor de moderne dreigingen waar we mee te maken hebben? Veel experts zijn ervan overtuigd dat kleinere, flexibele eenheden effectiever zijn dan een massale militaire aanwezigheid. Uiteindelijk komt het erop neer dat nationale defensie niet zomaar een kwestie is van troepen en wapens. Het heeft te maken met de verantwoordelijkheden van de staat en de rol die deze speelt in onze levens. Het is tijd om deze rol kritisch te bekijken en te overwegen of er niet betere manieren zijn om onszelf en onze waarden te verdedigen.

We komen nu bij wat vaak het laatste argument tegen het libertarische standpunt is. Iedere libertariër heeft wel eens een sympathieke maar kritische luisteraar horen zeggen: 'Oké, ik zie hoe dit systeem succesvol kan worden toegepast op lokale politie en rechtbanken. Maar hoe zou een libertarische samenleving ons kunnen beschermen tegen de Russen?'

Een dergelijke vraag is natuurlijk gebaseerd op een aantal betwiste veronderstellingen. Er wordt bijvoorbeeld aangenomen dat de Russen uit zijn op een militaire invasie van de Verenigde Staten, wat op zijn best twijfelachtig is. Daarnaast is er de veronderstelling dat zo'n verlangen zou voortpersisten nadat de Verenigde Staten een puur libertaire samenleving is geworden. Dit idee negeert de les die de geschiedenis ons leert: oorlogen ontstaan uit conflicten tussen natiestaten, die allemaal zwaar bewapend zijn en elkaar wantrouwen. Echter, een libertair Amerika zou voor niemand een bedreiging vormen. Niet omdat het geen wapens zou hebben, maar omdat het geen agressie tegen anderen of tegen welk land dan ook zou koesteren. Aangezien het niet langer een natiestaat is, die inherent bedreigend is, zou de kans klein zijn dat een land ons aanvalt. Een van de grote nadelen van de natiestaat is dat elke staat zijn onderdanen als eigen mensen beschouwt. Hierdoor lijden onschuldige burgers, de onderdanen van elk land, vaak onder de agressie van de vijandelijke staat tijdens interstatelijke oorlogen. In een libertarische samenleving zou er geen dergelijke identificatie zijn en dus ook geen verwoestende oorlog. Neem als voorbeeld onze criminele Metropolitan Police. Stel dat deze niet alleen agressie heeft gepleegd tegen Amerikanen, maar ook tegen Mexicanen. Als Mexico een regering had, zou deze goed weten dat de Amerikanen als geheel niet betrokken waren bij de misdaden van de Metropolitan en er geen enkele band mee hadden. Als de Mexicaanse autoriteiten een strafexpeditie zouden opzetten om de Metropolitan te straffen, zouden ze niet in oorlog zijn met de Amerikanen in het algemeen, zoals nu het geval zou zijn. Het is zelfs zeer waarschijnlijk dat andere Amerikaanse troepen zich bij de Mexicanen zouden voegen om de agressor te verslaan. Daarom lijkt het idee van een oorlog tussen staten tegen een libertair land of gebied hoogstwaarschijnlijk uit te doven.

Bovendien zit er een ernstige filosofische fout in het stellen van vragen over de Russen. Als we een nieuw systeem overwegen, wat het ook moge zijn, moeten we eerst beslissen of we dat willen. Of het nu libertarisme, communisme, links anarchisme, of een theocratie is, we moeten aannemen dat het al bestaat. Daarna kunnen we ons afvragen of het systeem zou kunnen functioneren, of het levensvatbaar is en hoe efficiënt het zou zijn. Ik denk dat we hebben aangetoond dat een libertarisch systeem, eenmaal geïmplementeerd, kan werken. Het kan levensvatbaar zijn en tegelijkertijd veel efficiënter, welvarender, moreler en vrijer dan welk ander sociaal systeem dan ook. Maar we hebben nog niets gezegd over hoe we van het huidige systeem naar het ideaal kunnen komen. Dit zijn immers twee totaal verschillende vragen: wat ons ideale doel is en de strategie om van het huidige systeem naar dat doel te komen. De kwestie rond Rusland vermengt deze twee niveaus van discussie. Het idee gaat niet uit van een libertarisme dat overal ter wereld is gevestigd, maar van een systeem dat om de een of andere reden alleen in Amerika bestaat en nergens anders. Maar waarom zouden we dat aannemen? Waarom niet eerst veronderstellen dat het overal gevestigd is en dan kijken of het werkt? De libertarische filosofie is immers een tijdloze filosofie, niet gebonden aan tijd of plaats. Wij pleiten voor vrijheid voor iedereen, overal, niet alleen in de Verenigde Staten. Als iemand het ermee eens is dat een libertarische wereldgemeenschap, eenmaal gevestigd, het beste is dat hij zich kan voorstellen---werkbaar, efficiënt en moreel---laat hem dan libertariër worden. Laat hem samen met ons vrijheid omarmen als ons ideale doel en samen met ons werken aan de uitdaging---natuurlijk een moeilijke taak---om uit te vinden hoe we dit ideaal kunnen bereiken.

Als we het toch over strategie hebben, dan is het duidelijk dat de overlevingskansen groter zijn naarmate de vrijheid over een groter gebied wordt gevestigd. Als vrijheid wereldwijd onmiddellijk wordt uitgeroepen, zijn er natuurlijk geen problemen met 'nationale verdediging'. Alle problemen zouden dan lokale kwesties van politie zijn. Maar als alleen Deep Falls, Wyoming, libertair wordt en de rest van Amerika en de wereld hetzelfde blijft, dan zijn de overlevingskansen zeer klein. Als Deep Falls zich afscheidt van de Verenigde Staten en een vrije samenleving opricht, is de kans groot dat de VS, gezien hun historische vijandigheid tegenover afscheidingsbewegingen, deze nieuwe vrije samenleving snel zullen aanvallen en onderdrukken. Tussen deze twee uitersten ligt een oneindig continuüm van gradaties. Het is duidelijk dat hoe groter het gebied van vrijheid, hoe beter het bestand is tegen externe bedreigingen. De 'Russische kwestie' is daarom eerder een strategische kwestie dan een keuze over basisprincipes. Het gaat om het doel waar we onze inspanningen op willen richten.

Laten we, na alles wat we hebben besproken, toch de kwestie van de Russen aankaarten. Stel je voor dat de Sovjet-Unie echt vastbesloten is om een libertarische bevolking binnen de huidige grenzen van de Verenigde Staten aan te vallen (waarbij er duidelijk geen Amerikaanse regering meer zou zijn om als natiestaat op te treden). In de eerste plaats zouden de Amerikaanse consumenten zelf bepalen hoe ze hun defensie-uitgaven willen vormgeven en hoeveel ze daarin willen investeren. Amerikanen die voorstanders zijn van Polaris-onderzeeërs en bang zijn voor een Sovjetdreiging, zouden geld beschikbaar stellen voor de financiering van dergelijke schepen. Degenen die de voorkeur geven aan een ABM-systeem, zouden investeren in verdediging met raketten. Aan de andere kant zouden degenen die om zo'n dreiging lachen of die toegewijde pacifisten zijn, helemaal geen bijdrage leveren aan een 'nationale' verdediging. Verschillende verdedigingstheorieën zouden worden toegepast, afhankelijk van degenen die deze ondersteunen en erachter staan. Gezien de enorme verspilling in alle oorlogen en defensievoorbereidingen door de geschiedenis heen, is het zeker niet onredelijk om te stellen dat vrijwillige defensie-inspanningen veel efficiënter zouden zijn dan overheidsbudgetten. Bovendien zouden deze inspanningen ongetwijfeld een stuk moreler zijn.

Maar laten we van het ergste uitgaan. Stel je voor dat de Sovjet-Unie Amerika binnenvalt en het land veroverd. Wat dan? We moeten ons realiseren dat de moeilijkheden voor de Sovjet-Unie dan pas echt beginnen. De belangrijkste reden waarom een veroverend land over een verslagen land kan heersen, is dat dit laatste een bestaand staatsapparaat heeft om de bevelen van de overwinnaar over te brengen aan een ondergeschikte bevolking. Groot-Brittannië, dat veel kleiner was in oppervlakte en bevolking, kon eeuwenlang over India heersen. Dit kwam doordat de Britten hun bevelen konden doorgeven aan de heersende Indiase prinsen, die ze op hun beurt oplegden aan de onderdanen. In de gevallen in de geschiedenis waar de veroverden geen regering hadden, vonden de veroveraars het extreem moeilijk om over hen te heersen. Zo hadden de Britten bij de verovering van West-Afrika grote moeite om over de Ibo-stam (de latere basis voor Biafra) te heersen. Deze stam was in wezen libertair en had geen heersende regering met stamhoofden om bevelen aan de inboorlingen door te geven. Een andere belangrijke reden waarom het eeuwen duurde voordat de Engelsen het oude Ierland veroverden, is dat de Ieren geen staat hadden, waardoor er geen regerende structuur bestond om verdragen te sluiten of bevelen door te geven. Om deze reden noemden de Engelsen de 'wilde' en 'onbeschaafde' Ieren 'ongelovig,' omdat ze zich niet aan de verdragen met de Engelse veroveraars hielden. De Engelsen konden nooit begrijpen dat, zonder enige vorm van staat, de Ierse krijgers die verdragen sloten met de Engelsen, enkel voor zichzelf spraken. Ze konden nooit een andere groep binnen de Ierse bevolking binden.

Bovendien zou het leven voor de Russische bezetters nog moeilijker worden door de onvermijdelijke uitbraak van guerrillaoorlog door de Amerikaanse bevolking. De twintigste eeuw heeft ons immers geleerd - een les die voor het eerst duidelijk werd toen de succesvolle Amerikaanse revolutionairen het krachtige Britse Rijk bestreden - dat geen enkele bezettingsmacht een vastberaden inheemse bevolking lang kan onderdrukken. Als de enorme Verenigde Staten, met zijn grotere productiviteit en vuurkracht, niet kon overwinnen tegen een kleine, relatief ongewapende Vietnamese bevolking, hoe zou de Sovjetunie dan ooit in staat zijn om het Amerikaanse volk te bedwingen? Geen enkele Russische bezettingssoldaat zou veilig zijn voor de woede van een verzet biedend Amerikaans volk. Guerrillaoorlogvoering heeft bewezen een onweerstaanbare kracht te zijn. Dit komt omdat het voortkomt uit het volk zelf, dat vecht voor zijn vrijheid en onafhankelijkheid tegen een buitenlandse overheerser. De gedachte aan deze enorme problemen en de onvermijdelijke kosten en verliezen die hieruit voort zouden vloeien, zou zelfs een hypothetische Sovjetregering die uit was op militaire verovering, vanuit het begin al tegenhouden.
