
# Een strategie voor vrijheid

## EDUCATIE: THEORIE EN BEWEGING

En zo hebben we het: een kern van waarheid die goed is in theorie en toepasbaar op onze politieke problemen -- het nieuwe libertarisme. Maar hoe behalen we, nu we de waarheid kennen, de overwinning? We staan voor een groot strategisch probleem dat alle 'radicale' overtuigingen door de geschiedenis heen heeft gekenmerkt: hoe brengen we de overgang tot stand van onze huidige, door de staat gecontroleerde wereld naar het uiteindelijke doel van vrijheid?

Er bestaat geen toverformule voor strategie. Elke strategie voor sociale verandering, die gebaseerd is op overtuiging en bekering, blijft een kunst en is geen exacte wetenschap. Dit gezegd hebbende, zijn we nog steeds niet zonder wijsheid in onze zoektocht naar de juiste doelen. Er kan een vruchtbare theorie zijn, of tenminste een vruchtbare discussie, over de effectieve strategie voor verandering.

Over één punt kunnen we het nauwelijks oneens zijn: een eerste en noodzakelijke voorwaarde voor het succes van het libertarisme -- en voor elke sociale beweging, of het nu het boeddhisme of vegetariërisme is -- is educatie. Dit houdt in dat we grote aantallen mensen moeten overtuigen en aanspreken. Onderwijs heeft twee essentiële aspecten: het vestigen van aandacht op het bestaan van een bepaald systeem en het aanzetten van mensen om het libertarische systeem te omarmen. Als onze beweging alleen zou bestaan uit slogans, publiciteit en andere middelen om aandacht te trekken, dan zouden we misschien veel mensen bereiken. Maar het zou al snel blijken dat we niets substantieels te zeggen hebben, waardoor ons publiek vluchtig en onbetrouwbaar zou zijn. Libertariërs moeten daarom grondig nadenken en onderzoek doen. Ze moeten theoretische en systematische boeken, artikelen en tijdschriften publiceren en deelnemen aan conferenties en seminars. Aan de andere kant zal een louter theoretische benadering weinig opleveren als niemand ooit van deze boeken en artikelen heeft gehoord. Daarom is publiciteit nodig: slogans, studentenactivisme, lezingen, radio- en tv-spots, enzovoort. Echt onderwijs kan niet zonder theorie en activisme, zonder ideologie en mensen die die ideologie uitdragen.

Dus, net zoals de theorie onder de aandacht van het publiek moet komen, heeft deze ook mensen nodig die het vaandel dragen, discussies aangaan, actie ondernemen en de boodschap uitdragen. Nogmaals, zowel de theorie als de beweging zijn nutteloos en steriel zonder elkaar. De theorie zal verwelken als er geen zelfbewuste beweging is die zich inzet om deze te verspreiden. Aan de andere kant wordt de beweging zinloos als ze de ideologie en het doel uit het oog verliest. Sommige libertarische theoretici vinden het onrein of ongepast dat er een actieve beweging met handelende individuen bestaat. Maar hoe kan vrijheid worden bereikt zonder libertariërs die de zaak bevorderen? Aan de andere kant verwerpen sommige militante activisten, in hun haast om actie te ondernemen -- welke actie dan ook -- de vermeende discussies over theorieën. Toch wordt hun actie zinloos en verspilde energie als ze maar een vaag idee hebben van waar ze voor strijden.

Verder hoor je libertariërs (en ook leden van andere sociale bewegingen) vaak klagen dat ze 'alleen maar tegen zichzelf praten' met hun boeken, tijdschriften en conferenties, en dat er maar weinig mensen van de 'buitenwereld' luisteren. Deze veelgehoorde klacht miskent echter het veelzijdige doel van 'educatie' in de breedste zin. Het is niet alleen belangrijk om anderen te onderwijzen; ook voortdurende zelfeducatie is cruciaal. Het corps van libertariërs moet altijd proberen anderen te werven voor hun gelederen -- dat is zeker. Maar ze moeten ook hun eigen groep levendig en gezond houden. Zelfeducatie heeft twee belangrijke doelen. Ten eerste helpt het bij het verfijnen en bevorderen van de libertarische 'theorie' -- het doel van onze hele onderneming. Libertarisme, hoe relevant en waar ook, kan niet alleen in stenen tabletten worden gegrift. Het moet een levende theorie zijn, die zich ontwikkelt door middel van schrijven en discussiëren, en door fouten te weerleggen en te bestrijden wanneer die zich voordoen. De libertarische beweging heeft tientallen kleine nieuwsbrieven en tijdschriften, variërend van gestencilde bladen tot verzorgde publicaties, die voortdurend opkomen en weer verdwijnen. Dit is een teken van een gezonde, groeiende beweging, bestaande uit ontelbare individuen die nadenken, argumenteren en bijdragen leveren.

Er is nog een andere belangrijke reden om 'tegen onszelf te praten', zelfs als dat het enige gesprek is dat plaatsvindt. Dat is de versterking: de psychologisch noodzakelijke wetenschap dat er anderen zijn die hetzelfde denken. Mensen met wie je kunt praten, discussiëren en in het algemeen kunt communiceren en omgaan. Op dit moment is het libertarische credo nog steeds dat van een relatief kleine minderheid, en bovendien bepleit het radicale veranderingen in de status quo. Daarom voelt het als een eenzaam geloof. De herbevestiging van het bestaan van een beweging, van 'met onszelf praten', kan dat isolement doorbreken en overwinnen. De hedendaagse beweging is inmiddels oud genoeg om een aanzienlijk aantal overlopers te hebben gekend. Analyse van deze overlopers toont aan dat in bijna alle gevallen de libertariër geïsoleerd was, afgesneden van gemeenschap en interactie met zijn lotgenoten. Een bloeiende beweging met een sterk gevoel van gemeenschap en saamhorigheid is de beste remedie tegen het opgeven van vrijheid als een hopeloze of 'onpraktische' zaak.

## **ZIJN WIJ 'UTOPISTEN'?** 

Er zijn verschillende opvattingen over de term 'utopisten'. Sommige mensen gebruiken het als een scheldwoord, een manier om idealisten te ridiculiseren. Andere zien het als een uitnodiging tot dromen en het verkennen van nieuwe mogelijkheden. Hoe je ook kijkt naar de term, het is belangrijk om te begrijpen dat idealisme en praktische realiteit hand in hand kunnen gaan. Veel mensen denken dat utopische ideeën alleen maar fantasieën zijn, ontsproten aan de geest van dromers. Maar deze ideeën kunnen ook dienen als inspiratiebron voor sociale verandering. Ze kunnen ons aanmoedigen om buiten de gebaande paden te denken en ons te storten op het creëren van een betere wereld. Bijvoorbeeld, de libertarische beweging is vaak afgeschilderd als een groep die zich richt op onrealistische idealen. Maar als we de kern van deze ideeën onderzoeken, zien we dat ze zijn geworteld in de waarden van vrijheid en zelfbeschikking. Deze waarden zijn niet alleen theoretisch; ze zijn essentieel voor een samenleving waarin individuen de ruimte krijgen om te bloeien. Een ander punt van kritiek is dat utopisten de moeilijkheden van het leven niet volledig onder ogen zien. Maar het omarmen van een utopisch idee betekent niet dat we de realiteit negeren. Integendeel, het kan ons helpen om constructieve oplossingen te vinden voor de uitdagingen waarmee we worden geconfronteerd. Door te dromen van wat mogelijk is, kunnen we actie ondernemen en verandering teweegbrengen. In deze discussie over utopisme en realisme is het cruciaal om te erkennen dat hoop en idealisme ons in staat stellen om vooruit te kijken. Ze geven ons de motivatie om te vechten voor wat we geloven en om te streven naar een wereld die rechtvaardiger en vrijer is voor iedereen. Dus, zijn we utopisten? Misschien, maar dat hoeft niet negatief te zijn. Het kan juist een kracht zijn die ons aanspoort tot actie en verandering.

Goed, we moeten onderwijs hebben via zowel theorie als een beweging. Maar wat moet de inhoud van dat onderwijs zijn? Elk 'radicaal' credo wordt ervan beschuldigd 'utopisch' te zijn en de libertarische beweging is daarop geen uitzondering. Sommige libertariërs beweren zelfs dat we mensen niet moeten afschrikken door 'te radicaal' te zijn. Daarom zouden we de volledige libertarische ideologie en het complete libertarische programma buiten het zicht moeten houden. Deze mensen pleiten voor een 'Fabiaans' programma van geleidelijkheid, dat zich alleen richt op het stap voor stap afbouwen van de staatsmacht. Een voorbeeld hiervan is belastingheffing. In plaats van de 'radicale' maatregel om alle belastingen af te schaffen, of zelfs de inkomstenbelasting te laten vallen, zouden we ons moeten beperken tot een oproep voor kleine verbeteringen. Laten we zeggen: een verlaging van de inkomstenbelasting met twee procent.

Op het gebied van strategisch denken kunnen libertariërs veel leren van de marxisten. Deze groep denkt al langer na over strategieën voor radicale sociale veranderingen dan wie dan ook. Marxisten wijzen twee cruciale strategische denkfouten aan die 'afwijken' van het juiste pad. De eerste noemen ze 'links sektarisme'. De tweede, een tegengestelde afwijking, is 'rechts opportunisme'. Critici van libertarische 'extremistische' principes zijn vaak te vergelijken met de marxistische 'rechtse opportunisten'. Het grote probleem met deze opportunisten is dat ze zich te veel richten op geleidelijke en 'praktische' programma's, die een goede kans maken om snel aangenomen te worden. Hierdoor lopen ze het risico het uiteindelijke doel, namelijk de libertarische idealen, volledig uit het oog te verliezen. Wie zich beperkt tot het voorstellen van een belastingverlaging van twee procent, draagt bij aan het in de vergetelheid raken van het uiteindelijke doel: de volledige afschaffing van belastingen. Door de focus te leggen op onmiddellijke middelen, zorgt hij ervoor dat het uiteindelijke doel wordt weggevaagd, en daarmee de reden waarom je libertariër bent. Als libertariërs weigeren het vaandel van pure principes en het uiteindelijke doel hoog te houden, wie zal dat dan doen? Het antwoord is: niemand. Daarom is een belangrijke bron van afvalligheid binnen de beweging in de afgelopen jaren het verkeerde pad van opportunisme geweest.

Een opvallend voorbeeld van afvalligheid door opportunisme is iemand die we 'Robert' zullen noemen. Robert werd begin jaren vijftig een toegewijd en militant libertariër. Al snel richtte hij zich op activisme en directe resultaten. Hij kwam tot de conclusie dat het strategisch gezien verstandig was om alle gesprekken over het libertarische doel te minimaliseren. Dit gold in het bijzonder voor de libertarische vijandigheid tegenover de overheid. Zijn focus lag op het benadrukken van het 'positieve' en de prestaties die mensen konden bereiken door middel van vrijwillige actie. Naarmate zijn carrière vorderde, begon Robert compromisloze libertariërs als een last te beschouwen. Daarom besloot hij systematisch iedereen in zijn organisatie te ontslaan die 'negatief' over de overheid was. Het duurde niet lang voordat Robert openlijk afstand deed van zijn libertarische ideologie. Hij pleitte voor een 'partnerschap' tussen overheid en particuliere ondernemingen -- tussen dwang en vrijwilligheid. Kortom, hij nam openlijk plaats binnen het establishment. Toch zal Robert in zijn momenten van reflectie zelfs naar zichzelf verwijzen als een 'anarchist', maar dan alleen in een abstracte, onrealistische context die weinig te maken heeft met de echte wereld.

De vrijemarkteconoom F.A. Hayek, die zelf op geen enkel gebied als een 'extremist' beschouwd kan worden, heeft overtuigend geschreven over het cruciale belang van het hooghouden van de pure en 'extreme' ideologie voor het succes van de vrijheid. Hij stelt dat een van de belangrijkste aantrekkingskrachten van het socialisme altijd de voortdurende nadruk op het 'ideale' doel is geweest. Dit ideaal doordringt, informeert en leidt de acties van iedereen die ernaar streeft. Hayek voegt daar aan toe:

> We moeten de opbouw van een vrije samenleving opnieuw beschouwen als een intellectueel avontuur, een daad van moed. Wat we missen is een liberaal utopia; een programma dat niet alleen een verdediging is van de bestaande situatie, noch een afgezwakte vorm van socialisme. We hebben een echt liberaal radicalisme nodig dat de zwakheden van de machtigen, waaronder de vakbond, zonder angst aanspreekt. Het moet ook niet te praktisch zijn en zich niet alleen richten op wat momenteel politiek haalbaar lijkt. We hebben intellectuele leiders nodig die de verleidingen van macht en invloed kunnen weerstaan, en die bereid zijn voor een ideaal te strijden, hoe klein de kans op vroege verwezenlijking ook mag zijn. Het moeten mensen zijn die vasthouden aan hun principes en vechten voor hun volledige realisatie, hoe ver weg dat ook lijkt. Vrije handel en kansen zijn idealen die nog steeds veel mensen kunnen inspireren. Maar een simpele 'redelijke vrijheid van handel' of 'versoepeling van controles' is intellectueel niet respectabel en zal waarschijnlijk weinig enthousiasme opwekken. De belangrijkste les die de echte liberaal kan leren van het succes van socialisten is dat hun moed om utopisch te zijn hen de steun van intellectuelen heeft opgeleverd. Dit heeft hun invloed op de publieke opinie versterkt en mogelijk gemaakt wat eerder volkomen onhaalbaar leek. Degenen die zich enkel richtten op wat uitvoerbaar leek binnen de huidige opinie, hebben gemerkt dat zelfs dat snel politiek onmogelijk werd door veranderingen in de publieke opinie die zij niet hebben kunnen beïnvloeden. Tenzij we de filosofische basis van een vrije samenleving opnieuw tot een levendige intellectuele kwestie kunnen maken, en de uitvoering ervan tot een uitdaging voor de slimste en meest creatieve geesten onder ons, zijn de vooruitzichten voor vrijheid inderdaad somber. Maar als we het geloof in de kracht van ideeën kunnen herwinnen, dat ooit zo kenmerkend was voor het liberalisme, dan is de strijd nog niet verloren.

Hayek wijst hier een belangrijke waarheid aan en geeft een goede reden om het uiteindelijke doel te benadrukken: de opwinding en het enthousiasme die een logisch samenhangend systeem kan oproepen. Wie zou er daarentegen de barricades opgaan voor een belastingverlaging van twee procent?

Er is nog een andere belangrijke reden om vast te houden aan zuivere principes. Hoewel dagelijkse sociale en politieke gebeurtenissen vaak het resultaat zijn van veel druk en het vaak onbevredigende resultaat van het geduw en getrek van tegenstrijdige ideologieën en belangen, is het juist daarom des te belangrijker voor de libertariër om de lat hoog te leggen. De roep om een belastingverlaging van twee procent leidt doorgaans slechts tot een lichte matiging van een geplande belastingverhoging. De vraag om een aanzienlijke belastingverlaging kan echter resulteren in een substantiële vermindering. Door de jaren heen is het de strategische rol van de 'extremist' geweest om de dagelijkse agenda steeds verder in zijn richting te duwen. Socialisten zijn hier bijzonder bedreven in. Als we kijken naar het socialistische programma van 60 of zelfs 30 jaar geleden, zien we dat maatregelen die destijds als gevaarlijk socialistisch werden beschouwd, inmiddels onmisbaar zijn binnen de 'mainstream' van het Amerikaanse erfgoed. Op deze wijze worden de dagelijkse compromissen van zogenaamde 'praktische' politiek onverbiddelijk in de collectivistische richting getrokken. Er is geen reden dat de libertariër niet hetzelfde zou kunnen bereiken. Een van de redenen dat de conservatieve oppositie tegen collectivisme zo zwak is, is dat het conservatisme van nature geen consistente politieke filosofie biedt. Het is vooral een 'praktische' verdediging van de bestaande status quo, vaak neergezet als de belichaming van de Amerikaanse 'traditie'. Maar naarmate het statisme groeit en zich uitbreidt, raakt het per definitie steeds meer verankerd en dus 'traditioneel'. Hierdoor kan het conservatisme geen intellectuele wapens vinden om deze omverwerping tegen te gaan.

Vasthouden aan principes betekent meer dan alleen het hooghouden van het ultieme libertarische ideaal en het niet tegenspreken ervan. Het houdt ook in dat je ernaar streeft dat doel zo snel mogelijk te bereiken, voor zover dat fysiek haalbaar is. Kortom, de libertariër mag nooit een geleidelijke benadering van zijn doelen verkiezen boven een onmiddellijke en snelle aanpak. Want daarmee ondermijnt hij het cruciale belang van zijn eigen doelen en principes. Als hij zelf al zo weinig waarde hecht aan zijn idealen, hoe hoog zullen anderen ze dan waarderen?

Kortom, om de vrijheid echt na te streven, moet de libertariër ernaar verlangen dat deze op de meest effectieve en snelste manier wordt bereikt. Vanuit deze mentaliteit verklaarde de klassieke liberaal Leonard E. Read, die na de Tweede Wereldoorlog pleitte voor de onmiddellijke en totale afschaffing van prijs- en looncontroles, in een toespraak: 'Als er hier op dit podium een knop zou zijn die, zodra je erop drukt, alle loon- en prijscontroles onmiddellijk zou opheffen, dan zou ik hem meteen indrukken!'

De libertariër zou dus iemand moeten zijn die op de knop zou drukken voor de onmiddellijke afschaffing van alle inbreuken op de vrijheid, als die knop zou bestaan. Natuurlijk is hij zich ervan bewust dat zo'n magische knop niet echt bestaat, maar zijn fundamentele voorkeur beïnvloedt en vormt zijn hele strategische visie.

Een 'abolitionistisch' perspectief betekent niet dat de libertariër de snelheid waarmee zijn doel feitelijk bereikt kan worden, onrealistisch inschat. William Lloyd Garrison, de libertarische abolitionist van de slavernij, was ook niet 'onrealistisch' toen hij in de jaren 1830 de glorieuze standaard van onmiddellijke emancipatie vooropstelde. Zijn doel was moreel juist en zijn strategisch realisme kwam voort uit het besef dat hij niet verwachtte zijn doel snel te bereiken. In hoofdstuk 1 zagen we dat Garrison zelf het volgende onderscheid maakte: 'We dringen aan op onmiddellijke afschaffing, hoe serieus we dat ook doen, maar uiteindelijk zal het helaas een geleidelijke afschaffing zijn. We hebben nooit gezegd dat slavernij in één klap omvergeworpen zou worden; dat het zo zou moeten zijn, blijven we altijd beweren.' Anders, zoals Garrison scherp waarschuwde: 'Geleidelijkheid in theorie is eeuwigheid in de praktijk.'

Geleidelijkheid ondermijnt in theorie het doel zelf. Het houdt in dat het doel ondergeschikt wordt gemaakt aan andere niet- of antiliberale overwegingen. Een voorkeur voor gradualisme impliceert dat deze andere overwegingen belangrijker zijn dan vrijheid. Stel je voor dat een voorstander van de afschaffing van slavernij zou zeggen: 'Ik ben voor het beëindigen van de slavernij, maar pas over tien jaar.' Dit zou impliceren dat afschaffing over acht of negen jaar, of zelfs onmiddellijk, verkeerd zou zijn. Het zou betekenen dat het beter is slavernij nog een tijdje voort te zetten. Dit wijst erop dat overwegingen van rechtvaardigheid zijn losgelaten en dat het doel voor de abolitionist of libertariër niet langer prioriteit heeft. In feite zou dit voor zowel de abolitionist als de libertariër betekenen dat ze pleiten voor het voortzetten van misdaad en onrecht.

Hoewel het belangrijk is voor de libertariër om zijn ultieme en 'extreme' ideaal hoog te houden, maakt dit hem, in tegenstelling tot Hayek, nog geen 'utopist'. De echte utopist is iemand die een systeem voorstaat dat in strijd is met de natuurlijke wetten van mensen en de echte wereld. Een utopisch systeem kan niet functioneren, zelfs niet als iedereen wordt overgehaald om het in praktijk te brengen. Dit systeem zou zichzelf niet kunnen handhaven. Het utopische doel van links, namelijk communisme --- de afschaffing van specialisatie en de acceptatie van eenheid --- kan niet slagen, zelfs niet als iedereen bereid zou zijn het onmiddellijk te omarmen. Het zou niet kunnen functioneren omdat het inbreuk doet op de menselijke natuur en de werkelijkheid, vooral op de uniciteit en individualiteit van elk persoon, op hun capaciteiten en interesses. Bovendien zou het leiden tot een drastische afname van de productie van rijkdom, zodat het merendeel van de mensheid gedoemd zou zijn snel te verhongeren en uit te sterven.

Kortom, de term 'utopisch' verwart in de volksmond twee soorten obstakels die zich voordoen bij een programma dat radicaal afwijkt van de status quo. Het eerste obstakel is dat zo'n programma in strijd is met de menselijke natuur en de werkelijkheid, waardoor het niet zou kunnen functioneren als het eenmaal is geïmplementeerd. Dit betreft het utopisme van het communisme. Het tweede obstakel is de uitdaging om voldoende mensen te overtuigen van de noodzaak van het programma. Het eerste obstakel is een gebrekkige theorie, omdat het de natuur van de mens negeert; het tweede is een kwestie van menselijke wil, namelijk het overtuigen van genoeg mensen van de juistheid van de doctrine. In zijn gebruikelijke negatieve betekenis is 'utopisch' alleen van toepassing op het eerste obstakel. In wezen is de libertarische doctrine dus niet utopisch, maar juist realistisch, omdat het de enige theorie is die daadwerkelijk consistent is met de menselijke natuur en de wereld. De libertariër ontkent de diversiteit van de mens niet; hij viert deze en streeft ernaar om die diversiteit volledig tot uiting te laten komen in een wereld van volledige vrijheid. Door dit te doen, bevordert hij ook een enorme toename in productiviteit en de levensstandaard van iedereen. Dit is een uiterst 'praktisch' resultaat dat doorgaans door echte utopisten als kwaadaardig 'materialisme' wordt afgewezen.

De libertariër is bij uitstek realistisch omdat hij de aard van de staat en zijn streven naar macht volledig begrijpt. Daarentegen is de schijnbaar veel realistischere conservatief, die gelooft in een 'beperkte overheid', de echte onpraktische utopist. Deze conservatief blijft maar herhalen dat de centrale overheid sterk beperkt moet worden door een grondwet. Maar terwijl hij zich verzet tegen de corruptie van de oorspronkelijke grondwet en tegen de uitbreiding van de federale macht sinds 1789, slaagt hij er niet in de juiste les uit deze degeneratie te trekken. Het idee van een strikt beperkte constitutionele staat was een nobel experiment, maar het mislukte zelfs onder de meest gunstige omstandigheden. Als het toen al mislukte, waarom zou een soortgelijk experiment het nu beter doen? Nee, de ware onpraktische utopist is de conservatieve laissez-fairist, de man die alle wapens en beslissingsbevoegdheid in handen van de centrale regering legt en vervolgens zegt: 'Beperk jezelf.'

Er is nog een andere belangrijke reden waarom libertariërs het bredere utopisme van links verachten. Linkse utopisten postuleren steeds opnieuw een drastische verandering in de menselijke aard; voor hen heeft de mens eigenlijk geen vaste aard. Het individu wordt gezien als oneindig kneedbaar door de maatschappelijke instellingen. Daarom wordt aangenomen dat het communistische ideaal --- of het socialistische overgangssysteem --- de Nieuwe Communistische Mens zal creëren. De libertariër gelooft echter dat elk individu uiteindelijk een vrije wil heeft en zichzelf vormt. Het is daarom naïef om te hopen op een uniforme en radicale verandering van mensen door de beoogde Nieuwe Orde. Natuurlijk hoopt de libertariër wel op een morele verbetering bij iedereen, al vallen zijn morele doelen nauwelijks samen met die van socialisten. Zo zou hij dolgelukkig zijn als alle verlangen naar agressie tussen mensen zou verdwijnen. Maar hij is veel te realistisch om zijn vertrouwen te stellen in dit soort veranderingen. In plaats daarvan vertrouwt het libertarische systeem op het idee dat het op zichzelf al veel moreler zal zijn en beter zal functioneren dan welk ander systeem dan ook, gelet op de bestaande menselijke waarden en houdingen. Hoe meer het verlangen naar agressie verdwijnt, des te beter zal elk sociaal systeem werken, inclusief het libertarische. Hoe minder behoefte er bijvoorbeeld zal zijn aan politie of rechtssystemen. Maar het libertarische systeem is niet afhankelijk van dergelijke veranderingen.

Als de libertariër moet pleiten voor het direct bereiken van vrijheid en het afschaffen van statisme, en als gradualisme in theorie in strijd is met dit allesomvattende doel, welke strategische houding kan de libertariër dan nog aannemen in de huidige wereld? Moet hij zich beperken tot het pleiten voor onmiddellijke afschaffing? Zijn 'overgangseisen' --- stappen richting praktische vrijheid --- per definitie onwettig? Nee, dat zou hem in een andere zelfvernietigende strategische val doen trappen, namelijk die van 'links sektarisme'. Libertariërs zijn vaak opportunisten geweest die hun uiteindelijke doel uit het oog hebben verloren of onderschatten. Maar sommigen maken de tegenovergestelde fout: zij vrezen en veroordelen elke vooruitgang naar het doel, omdat ze denken dat dit noodzakelijkerwijs het doel zelf ondermijnt. De tragedie is dat deze sektaristen, door elke vooruitgang die het uiteindelijke doel voorbijschiet te veroordelen, het gekoesterde doel zelf ijdel en nutteloos maken. Natuurlijk zouden we allemaal dolgelukkig zijn als we in één klap totale vrijheid zouden bereiken, maar de realistische vooruitzichten voor zo'n grote sprong zijn beperkt. Sociale verandering gebeurt meestal niet in één sprongetje, ook al is deze niet altijd klein en geleidelijk. Door elke overgangsbenadering naar het doel af te wijzen, maken deze sektarische libertariërs het onmogelijk om het doel zelf ooit te bereiken. Zo kunnen ze net zo volledig 'liquidationistisch' zijn ten opzichte van het pure doel als de opportunisten zelf.

Soms, vreemd genoeg, ondergaat een individu veranderingen van de ene tegenovergestelde dwaling naar de andere, terwijl het het juiste strategische pad minacht. Zo kan een linkse sektariër, wanhopig na jaren van vruchteloze herhalingen van zijn zuiverheid zonder echte vooruitgang, zich in het onstuimige struikgewas van rechtse opportunisten storten. Hij is op zoek naar enige vooruitgang op korte termijn, zelfs als dat ten koste gaat van zijn uiteindelijke doel. Aan de andere kant kan een rechtse opportunist, die zich ongemakkelijk begint te voelen bij het compromitteren van zijn eigen of de intellectuele integriteit van zijn collega's en hun uiteindelijke doelen, zich aansluiten bij het linkse sektarisme. Hij keurt dan elke strategische prioriteitstelling af die hen dichter bij die doelen kan brengen. Op deze manier voeden en versterken de twee tegengestelde afwijkingen elkaar, wat destructief is voor de belangrijke taak om het libertarische doel effectief te bereiken.

Hoe kunnen we dan bepalen of een halve maatregel of overgangseis moet worden toegejuicht als een stap vooruit, of moet worden afgekeurd als opportunistisch verraad? Er zijn twee belangrijke criteria om deze vraag te beantwoorden: (1) het uiteindelijke doel van vrijheid moet altijd hoog in het vaandel staan als het gewenste doel, ongeacht de overgangseisen; en (2) geen enkele stap of middel mag ooit expliciet of impliciet in tegenspraak zijn met dit uiteindelijke doel. Een eis op de korte termijn gaat misschien niet zover als we zouden willen, maar moet altijd in lijn zijn met het uiteindelijke doel. Als dat niet het geval is, zal het kortetermijndoel tegen het langetermijndoel inwerken, en dan is de opportunistische liquidatie van het libertarische principe een feit.

Een voorbeeld van een contraproductieve en opportunistische strategie is het belastingstelsel. De libertariër streeft naar de uiteindelijke afschaffing van belastingen. Het is dan ook volkomen legitiem om als strategische maatregel in die richting aan te dringen op een drastische verlaging of zelfs afschaffing van de inkomstenbelasting. Echter, de libertariër mag nooit een nieuwe belasting of belastingverhoging steunen. Hij zou bijvoorbeeld niet moeten pleiten voor een grote verlaging van de inkomstenbelasting en tegelijk voorstellen dat deze vervangen wordt door een omzetbelasting of een andere vorm van belasting. Het verlagen of, beter nog, afschaffen van een belasting betekent altijd een legitime en niet-contradictore vermindering van de staatsmacht, en vormt een belangrijke stap richting vrijheid. Maar het vervangen van een belasting door een nieuwe of verhoogde belasting op een ander terrein doet precies het tegenovergestelde. Dit betekent immers een nieuwe en extra belastingdruk van de staat op een ander front. Het opleggen van een nieuwe of hogere belasting staat volledig op gespannen voet met het libertarische doel en ondermijnt dit zelfs.

In dit tijdperk van voortdurende federale tekorten worden we vaak geconfronteerd met de vraag: moeten we instemmen met een belastingverlaging, ook al kan dit leiden tot een groter overheidstekort? Conservatieven, die de voorkeur geven aan een evenwichtige begroting boven belastingverlaging, verzetten zich steevast tegen elke belastingverlaging die niet meteen vergezeld gaat van een gelijkwaardige of grotere verlaging van de overheidsuitgaven. Echter, aangezien belastingheffing een onwettige daad van agressie is, ondermijnt het algehele gebrek aan enthousiasme voor belastingverlagingen -- welke vorm dan ook -- het libertarische doel. Het is belangrijk om je tegen overheidsuitgaven te verzetten wanneer de begroting wordt besproken of in stemming wordt gebracht. In dat geval zou de libertariër ook moeten pleiten voor drastische bezuinigingen. Kortom, overheidsactiviteiten moeten zoveel mogelijk worden teruggedrongen. Elke vorm van verzet tegen een specifieke verlaging van belastingen of uitgaven is ontoelaatbaar, omdat dit in strijd is met de libertarische principes en het libertarische doel.

Een bijzonder gevaarlijke verleiding voor opportunisme is de neiging van sommige libertariërs, vooral binnen de Libertarische Partij, om 'verantwoordelijk' en 'realistisch' over te komen door een soort 'vierjarenplan' voor destatisering voor te stellen. Het belangrijkste punt hierbij is niet het aantal jaren dat het plan beslaat, maar het concept van een volledig en gepland programma voor de overgang naar totale vrijheid. Bijvoorbeeld: in jaar 1 zou wet A moeten worden ingetrokken, wet B gewijzigd, en belasting C met 10 procent verlaagd. In jaar 2 zou wet D dan moeten worden ingetrokken en belasting C nogmaals met 10 procent verlaagd, enzovoort. Het grote probleem met zo'n plan, en de ernstige contradictie met het libertarische principe, is dat het sterk impliceert dat wet D pas in het tweede jaar van het geplande programma zou moeten worden ingetrokken. De valkuil van gradualisme in theorie zou zo op grote schaal worden toegepast. De zogenaamde libertarische planners zouden in een positie komen waarin het lijkt alsof ze zich verzetten tegen een sneller tempo naar vrijheid dan hun plan voorschrijft. En er is inderdaad geen legitieme reden om voor een langzamer tempo te kiezen; het tegenovergestelde is zelfs waar.

Er is nog een andere ernstige tekortkoming aan het idee van een alomvattend gepland programma voor vrijheid. De zorgvuldigheid en het doordachte tempo, evenals de uitgebreide opzet van het programma, suggereren dat de staat niet echt de vijand van de mensheid is. Daarmee lijkt het mogelijk en zelfs wenselijk om de staat te gebruiken voor een gecontroleerd pad naar vrijheid. Het inzicht dat de staat de grootste vijand van de mensheid is, leidt echter tot een heel andere strategische benadering. Libertariërs zouden elke vermindering van de macht of activiteiten van de staat op elk vlak met enthousiasme moeten aanmoedigen en accepteren. Zo'n vermindering zou op elk moment een welkome afname van misdaad en agressie met zich meebrengen. Daarom zou de zorg van de libertariër niet moeten zijn om de staat te gebruiken voor een weloverwogen destabilisatie, maar om alle uitingen van statisme waar en wanneer mogelijk weg te halen.

In lijn met deze analyse nam het Nationaal Comité van de Libertarische Partij in oktober 1977 een strategieverklaring aan, die het volgende inhield:

We moeten de vaandel van puur principe hooghouden en ons doel nooit in gevaar brengen. De morele imperatief van het libertarische principe eist dat tirannie, onrecht, de afwezigheid van volledige vrijheid en schending van rechten niet langer geaccepteerd kunnen worden.

Elke intermediaire eis moet worden behandeld, zoals in het platform van de Libertarische Partij, en moet worden gezien als een tussenstap naar ons ultieme doel, dat als superieur wordt beschouwd. Daarom dient elke eis gepresenteerd te worden als een stap richting ons einddoel, en niet als een doel op zich.

Onze principes hooghouden betekent dat we het moeras van zelfopgelegd, verplicht geleidelijkheid volledig moeten vermijden. We moeten voorkomen dat we, uit naam van eerlijkheid, het verminderen van lijden of het voldoen aan verwachtingen, uitstelgedrag vertonen op de weg naar vrijheid. Het bereiken van vrijheid moet ons allesomvattende doel zijn.

We mogen ons niet vastleggen op een specifieke volgorde van destatisering, omdat dit kan worden opgevat als het goedkeuren van het voortzetten van statisme en schending van rechten. Omdat we nooit in de positie willen zijn dat we de voortzetting van tirannie steunen, moeten we alle destatiseringsmaatregelen accepteren, waar en wanneer dat mogelijk is.

De libertariër mag zich dus nooit laten verleiden tot voorstellen voor 'positieve' overheidsmaatregelen. Vanuit zijn perspectief zou de rol van de overheid alleen moeten zijn om zich zo snel mogelijk uit alle maatschappelijke domeinen terug te trekken, zodra ze daaronder wordt gebracht.

Er mogen geen tegenstrijdigheden in de retoriek zijn. Een libertariër moet geen argumenten of beleidsaanbevelingen formuleren die in strijd zijn met het uiteindelijke doel. Stel je voor dat een libertariër om zijn mening over een specifieke belastingverlaging wordt gevraagd. Zelfs als hij denkt dat hij op dit moment niet krachtig kan pleiten voor belastingafschaffing, moet hij absoluut vermijden om aan zijn steun voor de belastingverlaging onoprechte opmerkingen toe te voegen, zoals: 'Natuurlijk is enige belasting essentieel.' Dergelijke retorische trucs kunnen het publiek in verwarring brengen en de principes ondermijnen. Dit kan uiteindelijk alleen maar schadelijk zijn voor het doel dat we nastreven.

## IS ONDERWIJS GENOEG?

Alle libertariërs, ongeacht hun factie of overtuiging, hechten veel waarde aan onderwijs. Ze willen steeds meer mensen overtuigen om libertariër te worden, bij voorkeur met een sterke toewijding. Het probleem is echter dat de meeste libertariërs een erg simplistische kijk hebben op de rol en de reikwijdte van dat onderwijs. Ze doen, kortom, niet eens een poging om de vraag te beantwoorden: en daarna? Wat gebeurt er nadat een bepaald aantal mensen overtuigd is? En hoeveel mensen moeten er overtuigd zijn om naar de volgende fase over te gaan? Iedereen? Een meerderheid? Veel mensen?

De impliciete opvatting van veel libertariërs lijkt te zijn dat alleen onderwijs voldoende is, omdat iedereen een gelijkwaardige kans heeft om overtuigd te worden. Op zich klopt dat, maar sociologisch gezien is het een zwakke strategie. Juist libertariërs zouden moeten erkennen dat de staat een parasitaire vijand van de samenleving is. De staat creëert een elite die de rest van ons onderdrukt en hun inkomen door dwang verwerft. Het overtuigen van de heersende groepen van hun onrechtvaardigheid is, hoewel theoretisch mogelijk (en misschien in één of twee gevallen haalbaar), in de praktijk vrijwel onwerkelijk. Hoe groot is bijvoorbeeld de kans dat we de leidinggevenden van General Dynamics of Lockheed ervan kunnen overtuigen geen overheidssubsidies aan te nemen? En hoe waarschijnlijk is het dat de president van de Verenigde Staten dit boek of een ander stuk libertarische literatuur leest en dan zegt: 'Ze hebben gelijk. Ik heb ongelijk. Ik neem ontslag.'? Het is duidelijk dat de kans om diegenen te overtuigen die profiteren van de uitbuiting door de staat, op zijn minst verwaarloosbaar is. Onze hoop ligt bij het overtuigen van de massa mensen die lijden onder de staatsmacht, niet bij degenen die er beter van worden.

Maar als we dit stellen, erkennen we ook dat het probleem niet alleen ligt bij het onderwijs, maar ook bij de macht. Nadat een aanzienlijk aantal mensen zich bekeerd heeft, is er een belangrijke bijkomende taak: manieren en middelen vinden om de macht van de staat uit onze samenleving te verwijderen. De staat zal zich immers niet vrijwillig terugtrekken uit de macht. Daarom moeten wij, naast onderwijs, ook andere middelen inzetten. Welk middel of welke combinatie van middelen we gebruiken --- of dat nu stemmen, alternatieve instellingen die niet door de staat worden aangetast, of het massaal weigeren om met de staat samen te werken is --- hangt af van de omstandigheden van dat moment en wat wel of niet effectief blijkt te zijn. In tegenstelling tot theoretische vraagstukken zijn de specifieke tactieken die we moeten toepassen, zolang ze in lijn zijn met de principes en het uiteindelijke doel van een echt vrije samenleving, een kwestie van pragmatisme, beoordelingsvermogen en de soms onnauwkeurige 'kunst' van de tacticus.

## WELKE GROEPEN?

Maar onderwijs vormt het huidige strategische probleem voor de nabije en onbepaalde toekomst. Een belangrijke vraag is: wie zijn de meest waarschijnlijke kandidaten voor bekering als we er niet op kunnen rekenen onze heersers in grote aantallen te overtuigen? Welke sociale, beroepsmatige, economische of etnische klassen komen hiervoor in aanmerking?

Conservatieven hebben vaak hun hoop gevestigd op grote zakenmensen. Deze opvatting over grote bedrijven kwam het meest tot uiting in Ayn Rand's uitspraak: 'Big Business is Amerika's meest vervolgde minderheid.' Vervolgd? Met enkele eervolle uitzonderingen daargelaten, staan grote bedrijven gretig in de rij voor staatssteun. Voelt Lockheed, General Dynamics, AT&T of Nelson Rockefeller zich echt vervolgd?

De steun van grote bedrijven voor de welzijns- en oorlogsstaat is zo overduidelijk en ingrijpend, van lokaal tot federaal niveau, dat zelfs veel conservatieven het nu moeten erkennen, al is het maar tot op zekere hoogte. Hoe is het mogelijk dat ze zo'n fervente steun geven aan 'Amerika's meest vervolgde minderheid'? Voor conservatieven rest dan alleen de optie om aan te nemen dat (a) deze zakenmensen dom zijn en geen inzicht hebben in hun eigen economische belangen, en/of (b) dat ze gehersenspoeld zijn door links-liberale intellectuelen, die hen hebben vervuld met schuldgevoelens en misplaatst altruïsme. Toch zullen beide verklaringen niet opgaan, zoals slechts een blik op AT&T of Lockheed zal aantonen. Grote zakenmensen zijn vaak bewonderaars van het statisme, 'bedrijfsliberalen', niet omdat hun ziel vergiftigd is door intellectuelen, maar omdat ze er persoonlijk voordeel uit halen. Sinds de opkomst van het statisme aan het begin van de twintigste eeuw hebben zij de grote macht van staatscontracten, subsidies en kartelvorming aangegrepen om privileges te verwerven ten koste van de rest van de samenleving. Het is niet vergezocht om aan te nemen dat Nelson Rockefeller veel meer door eigenbelang wordt gedreven dan door nobel altruïsme. Zelfs liberalen erkennen dat het enorme netwerk van regelgevende overheidsinstanties ervoor zorgt dat elke industrie ten gunste van grote bedrijven wordt gekarteliseerd, ten koste van het publiek. Maar om hun New Deal-wereldbeeld te redden, troosten liberalen zichzelf met de gedachte dat deze agentschappen en andere 'hervormingen', die in de tijd van de Progressieve, Wilson- of Rooseveltiaanse periodes zijn ingevoerd, met de beste bedoelingen zijn gelanceerd, met het 'publieke welzijn' voor ogen. Ze geloven dat het idee en de ontstaansgeschiedenis van deze agentschappen oprecht waren; alleen in de praktijk zijn ze afgedwaald naar zonde en onderdanigheid aan particuliere, zakelijke belangen. Echter, wat Kolko, Weinstein, Domhoff en andere revisionistische historici duidelijk hebben aangetoond, is dat dit deel uitmaakt van een liberale mythe. In werkelijkheid zijn al deze hervormingen, zowel op nationaal als lokaal niveau, bedacht, geschreven en gelobbyd door de zeer bevoorrechte groepen zelf. Het werk van deze historici onthult onomstotelijk dat er geen Gouden Eeuw van Hervorming was voordat de zonde toesloeg; de zonde was er vanaf het begin, vanaf het moment van conceptie. De liberale hervormingen van de Progressieve-New Deal-Welzijnsstaat waren ontworpen om te creëren wat ze ook daadwerkelijk hebben gecreëerd: een wereld van gecentraliseerd statisme, van 'partnerschap' tussen overheid en industrie, een wereld die bestaat uit subsidies en monopolie-privileges voor bedrijven en andere bevoorrechte groepen.

Verwachten dat de Rockefellers of een legioen andere bevoordeelde zakenlieden zich zullen bekeren tot een libertarische of zelfs laissez-faire visie is ijdel. Dit betekent echter niet dat alle grote ondernemers of zakenlieden moeten worden afgeschreven. In tegenstelling tot de marxisten vormen niet alle zakenlieden, en zelfs niet alle grote zakenlieden, een homogene economische klasse met identieke belangen. Wanneer de CAB monopolieprivileges verleent aan enkele grote luchtvaartmaatschappijen of wanneer de FCC een monopolie toekent aan AT&T, zijn er talloze andere bedrijven en ondernemers, groot en klein, die hierdoor benadeeld worden. Het toekennen van een communicatiemonopolie aan AT&T door de FCC heeft er bijvoorbeeld lange tijd voor gezorgd dat de snelgroeiende datacommunicatie-industrie in de kinderschoenen bleef staan. Pas toen de FCC besloot om concurrentie toe te staan, kon de industrie met sprongen vooruitgaan. Privilegies impliceren uitsluiting, en daardoor zullen er altijd veel bedrijven en zakenlieden zijn, groot en klein, die een sterk economisch belang hebben bij het beëindigen van staatscontrole over hun sector. Er zijn dus veel ondernemers, vooral degene die ver verwijderd zijn van de bevoorrechte 'Oosterse gevestigde orde', die potentieel ontvankelijk zijn voor vrijemarkt- en libertarische ideeën.

Van welke groepen kunnen we dan verwachten dat ze bijzonder ontvankelijk zijn voor libertarische ideeën? Waar, zoals de marxisten zouden zeggen, is ons voorgestelde 'agentschap voor sociale verandering'? Dit is een belangrijke strategische vraag voor libertariërs, omdat het ons inzicht geeft in waar we onze educatieve inspanningen op moeten richten.

Campusjongeren spelen een belangrijke rol in de opkomende libertarische beweging. Dit is niet verrassend. De universiteit is een periode waarin mensen openstaan voor reflectie en het overdenken van fundamentele vragen over onze samenleving. Deze jongeren verlangen naar consistentie en eerlijke waarheden. Als studenten, die zijn opgegroeid in een wereld van wetenschap en abstracte ideeën, en die nog niet belast zijn met de verantwoordelijkheden en soms beperkte perspectieven van volwassenheid, vormen zij een vruchtbare basis voor libertarische overtuigingen. In de toekomst kunnen we een aanzienlijke groei van het libertarisme op nationale campussen verwachten. Deze groei gaat gepaard met de toenemende steun van een groeiend aantal jonge geleerden, professoren en afgestudeerde studenten.

Jongeren zouden zich ook aangetrokken moeten voelen tot het libertarische standpunt over onderwerpen die vaak het meest aansluiten bij hun zorgen. Dit betreft in het bijzonder onze oproep tot volledige afschaffing van de dienstplicht, terugtrekking uit de Koude Oorlog, burgerlijke vrijheden voor iedereen en de legalisering van drugs en andere slachtoffervrije overtredingen.

Ook de media zijn een rijke bron gebleken van positieve aandacht voor het nieuwe libertarische credo. Dit is niet alleen te danken aan de publiciteitswaarde, maar ook aan de consistentie van het libertarisme. Dit trekt een groep mensen aan die scherp is op nieuwe sociale en politieke trends. Hoewel zij van oorsprong liberaal zijn, merken ze steeds meer de mislukkingen en ineenstortingen van het gevestigde liberalisme op. Mediamensen voelen zich over het algemeen niet aangetrokken tot een vijandige conservatieve beweging die hen automatisch afschrijft als links en onwelkom is tegenover hun standpunten over buitenlands beleid en burgerlijke vrijheden. Maar dezezelfde mediamensen kunnen wel openstaan voor een libertarische beweging. Deze beweging sluit aan bij hun instincten voor vrede en persoonlijke vrijheid en koppelt hun verzet tegen de grote overheid aan de overheidsbemoeienis met de economie en eigendomsrechten. Een groeiend aantal mensen in de media legt deze nieuwe en verhelderende verbanden. Hun invloed is natuurlijk uiterst belangrijk en heeft een krachtige hefboomwerking op de rest van het publiek.

Hoe staat het met 'Midden-Amerika'? Dit is de enorme middenklasse en arbeidersklasse die het grootste deel van de Amerikaanse bevolking uitmaakt en vaak lijnrecht tegenover de campusjeugd staat. Hebben we enige aantrekkingskracht op hen? Logischerwijs zou onze aantrekkingskracht op Midden-Amerika nog groter moeten zijn. We richten ons namelijk vol op de groeiende en aanhoudende ontevredenheid die de massa van het Amerikaanse volk teistert: stijgende belastingen, inflatie, fileproblemen, criminaliteit en welvaartsschandalen. Alleen libertariërs beschikken over concrete en consistente oplossingen voor deze dringende kwesties. Onze oplossingen richten zich op het verminderen van de rol van de overheid in al deze gebieden door deze verantwoordelijkheden over te dragen aan particuliere en vrijwillige initiatieven. We kunnen aantonen dat de overheid en het statisme verantwoordelijk zijn voor deze problemen, en dat het wegnemen van dwingende overheidsmaatregelen de nodige oplossingen biedt.

Kleine ondernemers kunnen we een echte vrije ondernemingswereld beloven, vrij van monopolieprivileges, kartels en staatsubsidies van de gevestigde orde. Ook aan de grote zakenmensen buiten de monopolistische gevestigde orde kunnen we een wereld beloven waarin hun individuele talenten en inzet eindelijk volop de ruimte krijgen om te groeien. Dit zal leiden tot verbeterde technologie en hogere productiviteit, voor henzelf en voor ons allemaal. Daarnaast kunnen we verschillende etnische en minderheidsgroepen laten zien dat alleen onder vrijheid elke groep in staat is om zijn eigen belangen te cultiveren en eigen instellingen te runnen, zonder hinder van meerderheidsoverheersing en zonder dwang.

Kortom, de aantrekkingskracht van het libertarisme spreekt verschillende klassen aan. Het is een aantrekkingskracht die de grenzen van ras, beroep, economische klasse en generaties overschrijdt. Alle mensen die niet tot de heersende elite behoren, zijn mogelijk ontvankelijk voor onze boodschap. Iedereen of elke groep die waarde hecht aan vrijheid of welvaart kan een potentiële aanhanger van het libertarische credo zijn.

Vrijheid heeft de potentie om alle groepen in het publieke spectrum aan te spreken. Toch geldt dat wanneer alles goed gaat, de meeste mensen weinig interesse tonen in publieke zaken. Voor radicale sociale verandering - een verschuiving naar een ander sociaal systeem - is er vaak een zogenaamde 'crisissituatie' nodig. Dit betekent dat er een breuk in het bestaande systeem moet zijn die een algemene zoektocht naar alternatieve oplossingen oproept. Wanneer zo'n zoektocht naar sociale alternatieven op gang komt, moeten activisten van een andersdenkende beweging klaarstaan om dat radicale alternatief te bieden. Ze moeten de crisis in verband brengen met de inherente tekortkomingen van het systeem zelf en laten zien hoe het alternatieve systeem de bestaande crisis kan oplossen, en toekomstige ineenstortingen kan voorkomen. Hopelijk hebben de andersdenkenden ook een staat van dienst waarin ze de huidige crisis hebben voorspeld en ervoor hebben gewaarschuwd.

Bovendien is een kenmerk van crisissituaties dat zelfs de heersende elites hun steun voor het systeem beginnen te verzwakken. Door de crisis verliest zelfs een deel van de staat zijn motivatie en enthousiasme om te regeren. Kortom, belangrijke segmenten binnen de staat falen. In situaties van ineenstorting kunnen zelfs leden van de heersende elite zich zonder meer openstellen voor een alternatief systeem, of op zijn minst hun enthousiasme voor het bestaande systeem verliezen.

Zo benadrukt historicus Lawrence Stone dat een verval in de wil van de heersende elite een vereiste is voor radicale verandering. 'De elite kan haar manipulatieve vaardigheden verliezen, of haar militaire superioriteit, of haar zelfvertrouwen of cohesie. Ze kan vervreemd raken van de niet-elite of overweldigd worden door een financiële crisis. Ook kan ze incompetent, zwak of wreed zijn.'5

## **WAAROM VRIJHEID ZAL WINNEN** 

Vrijheid heeft de potentie om alle groepen in het publieke spectrum aan te spreken. Toch blijkt dat wanneer alles goed gaat, de meeste mensen weinig interesse tonen in publieke zaken. Voor radicale sociale verandering -- een verschuiving naar een ander sociaal systeem -- is vaak een zogenaamde 'crisissituatie' nodig. Dit betekent dat er een breuk in het bestaande systeem moet zijn, die een algemene zoektocht naar alternatieve oplossingen oproept. Wanneer zo'n zoektocht naar sociale alternatieven op gang komt, moeten activisten van een andersdenkende beweging klaarstaan om dat radicale alternatief te bieden. Ze moeten de crisis koppelen aan de inherente tekortkomingen van het systeem zelf. Daarnaast moeten ze laten zien hoe het alternatieve systeem niet alleen de huidige crisis kan oplossen, maar ook soortgelijke ineenstortingen in de toekomst kan voorkomen. Hopelijk hebben deze andersdenkenden ook een staat van dienst waarin ze de huidige crisis hebben voorspeld en ervoor hebben gewaarschuwd. Een belangrijk kenmerk van crisissituaties is dat zelfs de heersende elites hun steun voor het systeem beginnen te verzwakken. Door de crisis verliest zelfs een deel van de staat zijn motivatie en enthousiasme om te regeren. Kortom, belangrijke segmenten binnen de staat falen. In situaties van ineenstorting kunnen zelfs leden van de heersende elite zich openstellen voor een alternatief systeem, of op zijn minst hun enthousiasme voor het bestaande systeem verliezen. Historicicus Lawrence Stone benadrukt dat een verval in de wil van de heersende elite cruciaal is voor radicale verandering. 'De elite kan haar manipulatieve vaardigheden verliezen, of haar militaire superioriteit, of haar zelfvertrouwen en cohesie. Ze kan vervreemd raken van de niet-elite, overweldigd worden door een financiële crisis, of incompetent, zwak of wreed zijn.'5

Na het uiteenzetten van het libertarische credo en de toepassing ervan op belangrijke hedendaagse problemen, evenals het schetsen van welke groepen in de samenleving zich naar verwachting tot dit credo zullen aangetrokken voelen en op welke momenten, is het tijd om de toekomstperspectieven voor vrijheid te beoordelen. We moeten in het bijzonder de sterke en groeiende overtuiging van de auteur bespreken. Niet alleen dat het libertarisme uiteindelijk op de lange termijn zal zegevieren, maar ook dat het binnen een opmerkelijk korte tijd als winnaar uit de bus zal komen. Ik ben ervan overtuigd dat de donkere nacht van tirannie ten einde loopt en dat een nieuwe dageraad van vrijheid voor de deur staat.

Veel libertariërs zijn pessimistisch over de vooruitzichten voor vrijheid. Als we kijken naar de groei van het statisme in de twintigste eeuw en het verval van het klassieke liberalisme, zoals we in het inleidende hoofdstuk hebben beschreven, is het begrijpelijk om een pessimistische kijk te hebben. Dit pessimisme kan verergeren als we terugblikken op de mensheid en de donkere geschiedenis van despotisme, tirannie en uitbuiting in verschillende beschavingen zien. We zouden onszelf kunnen verontschuldigen als we dachten dat de klassiek-liberale opleving van de zeventiende tot en met de negentiende eeuw in het Westen slechts een atypische uitbarsting van glorie was in de lugubere kronieken van de geschiedenis, zowel het verleden als de toekomst. Echter, dit zou getuigen van een misvatting die door marxisten 'impressionisme' wordt genoemd: een oppervlakkige focus op historische gebeurtenissen zonder een diepere analyse van de causale wetten en trends die daarachter werken.

Het pleidooi voor libertarisch optimisme kan worden gepresenteerd in wat je concentrische cirkels zou kunnen noemen. We beginnen met de breedste en langste-termijn overwegingen en gaan vervolgens naar de scherpere focus op kortetermijntrends. In de breedste zin en op de lange termijn zal het libertarisme uiteindelijk zegevieren. Dit komt omdat alleen het libertarisme verenigbaar is met de aard van de mens en de wereld. Alleen vrijheid kan leiden tot welvaart, vervulling en geluk voor de mens. Kortom, het libertarisme zal winnen omdat het waar is. Het biedt het juiste beleid voor de mensheid, en uiteindelijk zal de waarheid altijd overwinnen.

Maar zulke lange-termijnoverwegingen kunnen inderdaad erg uitgebreid zijn. Vele eeuwen wachten tot de waarheid zegeviert, en dat kan een schrale troost zijn voor degenen die op een bepaald moment in de geschiedenis leven. Gelukkig zijn er redenen voor hoop op kortere termijn. In het bijzonder is er een reden die ons in staat stelt om het sombere beeld van de geschiedenis vóór de achttiende eeuw als niet langer relevant voor de toekomstige vooruitzichten van vrijheid te beschouwen.

Onze stelling is dat de geschiedenis een grote sprong heeft gemaakt, een keerpunt, toen de klassiek-liberale revoluties ons naar de industriële revolutie van de achttiende en negentiende eeuw leidden. In de pre-industriële wereld, de wereld van de Oude Orde en de boereneconomie, was er geen reden waarom het despotisme niet eindeloos zou kunnen voortduren, zelfs gedurende vele eeuwen. De boeren produceerden het voedsel, terwijl koningen, edelen en feodale landheren het overschot van de boeren inzamelden, boven wat nodig was om hen in leven en aan het werk te houden. Hoe wreed en uitbuitend het agrarisch despotisme ook was, het kon voortbestaan om twee belangrijke redenen: (1) de economie kon zelfs op een ondermaats niveau makkelijk in stand worden gehouden; en (2) de massa's wisten niet beter, hadden nooit een beter systeem meegemaakt en konden daardoor worden overgehaald om als lastdieren voor hun heren te blijven werken.

Maar de Industriële Revolutie was een beslissende sprong in de geschiedenis. Ze bracht omstandigheden en verwachtingen met zich mee die onomkeerbaar waren. Voor het eerst in de wereldgeschiedenis leidde de Industriële Revolutie tot een maatschappij waarin de levensstandaard van de massa's steeg van het bestaansminimum naar ongekende hoogten. De bevolking in het Westen, die eerder stagneerde, begon nu te groeien en te profiteren van de sterk toegenomen kansen op werk en een beter leven.

De klok kan niet worden teruggedraaid naar een pre-industriële tijdperk. Niet alleen zouden de massa's zo'n ingrijpende verandering in hun verwachtingen van een stijgende levensstandaard niet accepteren, maar een terugkeer naar een agrarische wereld zou ook leiden tot hongerdood en de dood van het grootste deel van de huidige bevolking. We zijn gevangen in het industriële tijdperk, of we dat nu leuk vinden of niet.

Maar als dat zo is, dan is de zaak van de vrijheid veiliggesteld. De economische wetenschap heeft aangetoond, zoals we in dit boek gedeeltelijk hebben laten zien, dat alleen vrijheid en een vrije markt in staat zijn om een industriële economie te laten draaien. Kortom, terwijl een vrije economie en een vrije maatschappij wenselijk en rechtvaardig zouden zijn in een pre-industriële wereld, zijn ze in een industriële wereld ook van essentieel belang. Zoals Ludwig von Mises en andere economen hebben aangetoond, werkt statisme simpelweg niet in een industriële economie. Daarom zal het, met een universele toewijding aan een industriële wereld, uiteindelijk - en veel sneller dan alleen door de opkomst van de waarheid - duidelijk worden dat de wereld vrijheid en de vrije markt moet omarmen als voorwaarden voor het overleven en bloeien van de industrie. Dit inzicht werd door Herbert Spencer en andere negentiende-eeuwse libertariërs erkend in hun onderscheid tussen de 'militaire' en de 'industriële' samenleving, tussen een samenleving van 'status' en een samenleving van 'contract'. In de twintigste eeuw toonde Mises aan dat (a) alle staatsinterventie de markt verstoort en verlamt, en als dit niet wordt teruggedraaid, leidt het tot socialisme; en (b) dat socialisme een rampspoed is omdat het geen industriële economie kan plannen zonder winst- en verliesprikkels, en zonder een echt prijssysteem of eigendomsrechten op kapitaal, land en andere productiemiddelen. Kortom, zoals Mises voorzag, kunnen noch socialisme, noch de verschillende tussenvormen van statisme en interventionisme functioneren. Daarom moeten, gezien de algemene verschuiving naar een industriële economie, deze vormen van statisme worden afgewezen en vervangen door vrijheid en vrije markten.

Dit was een veel kortere aanloop dan simpelweg wachten op de waarheid. Toch leek het voor de klassieke liberalen rond de eeuwwisseling van de twintigste eeuw - de Sumners, Spencers en Paretos - een ondraaglijk lange weg. Dat is hen niet kwalijk te nemen, want zij zagen het verval van het klassieke liberalisme en de opkomst van nieuwe, despotische vormen waartegen ze zich zo krachtig en vasthoudend verzetten. Helaas waren zij getuige van deze ontwikkeling. De wereld zou moeten wachten, zo niet eeuwen, dan toch minstens decennia, voordat socialisme en corporatief statisme ontmaskerd zouden worden als volslagen mislukkingen.

Maar de lange termijn is nu aangebroken. We hoeven de verwoestende effecten van het statisme niet langer te voorspellen; ze zijn al zichtbaar. Lord Keynes lachte ooit de kritiek van vrijemarkteconomen weg dat zijn inflatoire beleid op de lange termijn desastreus zou zijn. In zijn bekende antwoord gniffelde hij dat 'we op de lange termijn allemaal dood zijn'. Maar nu is Keynes dood, en leven wij in zijn lange termijn. De statistische kippen zijn thuisgekomen om te scharrelen.

Aan het begin van de twintigste eeuw, en decennia daarna, waren de zaken lang niet zo duidelijk. Statistische interventie, in al zijn vormen, probeerde een centraal geleide economie in stand te houden en zelfs uit te breiden. Dit gebeurde echter ten koste van de voorwaarden voor een vrij leven en een vrije markt, die op de lange termijn essentieel zijn voor overleving. Gedurende een halve eeuw kon statistisch ingrijpen zijn ondermijnende acties uitvoeren door middel van planning, controles, hoge en verlammende belastingen, en inflatie van papiergeld, zonder dat dit direct leidde tot duidelijke crises of ontwrichtingen. De industrialisatie van de vrije markt in de negentiende eeuw had een grote buffer van 'vet' in de economie opgebouwd, die deze verstoringen kon opvangen. De overheid kon het systeem belastingen, beperkingen en inflatie opleggen zonder daar snel of duidelijk negatieve gevolgen van te ondervinden.

Maar nu is het statisme zo ver gevorderd en is het al zo lang aan de macht dat de buffer dun is. Zoals Mises al in de jaren veertig aangaf, is het 'reservefonds' dat door laissez-faire was gecreëerd, 'uitgeput'. Alles wat de overheid nu doet, leidt onmiddellijk tot negatieve neveneffecten die voor iedereen duidelijk zijn, zelfs voor veel van de meest fervente verdedigers van het statisme.

In de communistische landen van Oost-Europa hebben de communisten steeds meer ingezien dat socialistische centrale planning niet werkt voor een industriële economie. Dit heeft geleid tot een snelle terugtrekking van centrale planning naar vrije markten, vooral in Joegoslavië. Ook in de Westerse wereld verkeert het staatskapitalisme in een crisis. Het wordt steeds duidelijker dat de overheid geen geld meer heeft. Het verhogen van de belastingen zal de industrie en stimuleringsmaatregelen onherstelbaar verlammen. Aan de andere kant zal het creëren van meer nieuw geld leiden tot rampzalige, ongecontroleerde inflatie. Daarom horen we steeds vaker de 'noodzaak van lagere verwachtingen van de overheid' terug van eens zo enthousiaste voorstanders van de staat. In West-Duitsland heeft de sociaal-democratische partij de roep om socialisme al lang laten varen. In Groot-Brittannië, waar de economie gebukt gaat onder hoge belastingen en toenemende inflatie---een situatie die de Britten zelfs de 'Engelse ziekte' noemen---is de Tory-partij, jarenlang in handen van toegewijde statisten, nu overgenomen door een vrijemarktgerichte fractie. Zelfs de Labor-partij heeft zich teruggetrokken uit de chaos van het op hol geslagen statisme.

In de Verenigde Staten kunnen we bijzonder optimistisch zijn, omdat we de cirkel van optimisme kunnen verkleinen tot een kortetermijndimensie. We kunnen met gerustgesteld zeggen dat de Verenigde Staten zich in een permanente crisissituatie bevinden, en we kunnen zelfs de oorsprong van die crisis aanwijzen: 1973-1975. Gelukkig voor de zaak van de vrijheid is er niet alleen een crisis van het statisme in de Verenigde Staten ontstaan, maar heeft deze zich ook breed in de samenleving verspreid, op verschillende terreinen van het leven en bijna gelijktijdig. Deze ineenstortingen van het statisme hebben een synergetisch effect gehad; ze hebben elkaar versterkt in hun cumulatieve impact. Bovendien worden deze crises door iedereen gezien als een gevolg van het statisme, en niet van de vrije markt, publieke hebzucht of iets anders. Uiteindelijk kunnen deze crises alleen worden verlicht door de overheid uit het spel te halen. We hebben libertariërs nodig om de weg te wijzen.

Laten we de verschillende gebieden van systemische crisis op een rijtje zetten en bekijken hoe veel daarvan samenhing in de periode van 1973 tot 1975 en daarna. Van de herfst van 1973 tot 1975 verkeerden de Verenigde Staten in een inflatoire depressie, ondanks veertig jaar van vermeende Keynesiaanse fine-tuning die beide problemen voor altijd zou moeten oplossen. Ook in deze tijd bereikte de inflatie angstaanjagende proporties met dubbele cijfers.

Bovendien beleefde New York City in 1975 zijn eerste grote schuldencrisis, die leidde tot een gedeeltelijke wanbetaling. De gevreesde term 'wanbetaling' werd echter vermeden; men sprak eerder van een 'stretchout', waarbij kortetermijnschuldeisers gedwongen werden om langetermijnobligaties van New York City te accepteren. Deze crisis was de eerste van vele wanbetalingen op staats- en lokale obligaties in het hele land. Staats- en lokale overheden komen steeds vaker voor onaangename 'crisis'-keuzes te staan: radicaal snijden in de uitgaven, hogere belastingen die bedrijven en middenklasse-burgers uit het gebied zullen verdrijven, of in gebreke blijven bij het aflossen van schulden.

Sinds het begin van de jaren zeventig is steeds duidelijker geworden dat hoge belastingen op inkomen, spaargeld en investeringen de bedrijfsactiviteit en productiviteit hebben stilgelegd. Accountants beginnen nu pas te beseffen dat deze belastingen, vooral in combinatie met inflatoire verstoringen in de zakelijke besluitvorming, hebben geleid tot een groeiende schaarste aan kapitaal. Hierdoor dreigt de vitale kapitaalvoorraad van Amerika geleidelijk uitgeput te raken, zonder dat we dat opmerken.

Het land wordt gekweld door belastingoproeren tegen de hoge belastingen op eigendom, inkomen en omzet. Het is dan ook veilig om te stellen dat verdere belastingverhogingen politiek zelfmoord zouden betekenen voor politici op elk bestuursniveau.

Het Sociale Zekerheidssysteem, dat ooit zo heilig was in de Amerikaanse opinie dat het letterlijk boven kritiek stond, wordt nu gezien als volledig in verval. Libertarische en vrije-markt schrijvers wijzen hier al lange tijd op. Zelfs de gevestigde orde erkent inmiddels dat het Sociale Zekerheidssysteem failliet is en dat het in geen enkel opzicht een echt 'verzekeringssysteem' is.

Regulering van de industrie wordt steeds meer beschouwd als een falen. Zelfs figuren zoals senator Edward Kennedy pleiten inmiddels voor deregulering van de luchtvaartmaatschappijen. Daarnaast is er veel discussie over de afschaffing van de ICC en de CAB.

Op sociaal vlak komt het ooit zo heilige openbare schoolsysteem steeds meer onder vuur te liggen. Openbare scholen, die onderwijsbeslissingen voor de hele gemeenschap moeten nemen, veroorzaken intense sociale conflicten over ras, geslacht, religie en onderwij inhoud. Ook de overheidspraktijken rond criminaliteit en opsluiting staan steeds meer onder druk. Libertarische denker Dr. Thomas Szasz heeft bijna alleenhandig veel mensen bevrijd van onvrijwillige opsluiting. Inmiddels erkent de overheid dat haar beleid om criminelen te 'rehabiliteren' volledig is mislukt. De handhaving van drugswetten, zoals het verbod op marihuana en wetten tegen verschillende vormen van seksuele relaties, is compleet ingestort. In het hele land groeit de roep om alle wetten tegen misdaden zonder slachtoffers af te schaffen. Dit zijn wetten die misdaden aanduiden waarbij er geen slachtoffers zijn. Het wordt steeds duidelijker dat de pogingen om deze wetten te handhaven enkel leiden tot ontberingen en een soort politiestaat. De tijd nadert snel dat het prohibitionisme op het gebied van persoonlijke moraliteit net zo ineffectief en onrechtvaardig zal blijken te zijn als bij alcohol.

Samen met de desastreuze gevolgen van het statisme op economisch en sociaal vlak volgde de traumatische nederlaag in Vietnam, die culmineerde in 1975. De volslagen mislukking van de Amerikaanse interventie in Vietnam heeft geleid tot een groeiende heroverweging van het hele interventionistische buitenlandse beleid dat de Verenigde Staten sinds Woodrow Wilson en Franklin D. Roosevelt voeren. Er heerst steeds meer de opvatting dat de Amerikaanse macht moet worden teruggedrongen en dat de regering de wereld niet succesvol kan besturen. Dit is de 'neoisolationistische' reactie op het terugdringen van de interventies van de Grote Regering in eigen land. Hoewel het Amerikaanse buitenlandse beleid nog steeds agressief globalistisch is, slaagde dit neo-isolationistische sentiment er in 1976 in om de Amerikaanse interventie in Angola te beperken.

Misschien wel het meest sprekende teken van de afbraak van de mystiek rond de Amerikaanse staat, en van zijn morele basis, was de onthulling van Watergate in 1973-1974. Watergate biedt ons de grootste hoop op een korte termijn overwinning voor de vrijheid in Amerika. Politici wijzen ons sindsdien op de vernietiging van het 'vertrouwen in de overheid' bij het publiek -- iets dat ook hoog tijd was. Watergate leidde tot een radicale verandering in de diepgewortelde attitudes van iedereen, ongeacht hun ideologie, ten opzichte van de overheid. Watergate maakte ons in de eerste plaats wakker voor de invasies van persoonlijke vrijheid en privébezit door de overheid: afluisteren, drugsgebruik, het onderscheppen van post, provocateurs en zelfs moordaanslagen. Het schandaal ontheiligde eindelijk onze voormalige iconen, de FBI en CIA, en zorgde ervoor dat ze met een nuchtere blik werden bekeken. Maar belangrijker nog, door de afzetting van de president te bewerkstelligen, ontheiligde Watergate voorgoed een functie die door het Amerikaanse publiek vrijwel als soeverein werd beschouwd. De president zal niet langer boven de wet staan; hij zal niet langer zonder gevolgen kunnen handelen.

Maar het allerbelangrijkste is dat de overheid in Amerika grotendeels ontheiligd is. Niemand vertrouwt politici of de regering nog; alle overheden worden met blijvende vijandigheid bekeken. Dit brengt ons terug naar de staat van gezond wantrouwen jegens de regering die het Amerikaanse publiek en de revolutionairen van de achttiende eeuw kenmerkte.

Even leek het erop dat Jimmy Carter zijn doel om het vertrouwen van de mensen in de overheid terug te brengen, zou kunnen realiseren. Maar door het fiasco met Bert Lance en andere misstappen is hij daar gelukkig niet in geslaagd. De voortdurende regeringscrisis gaat nog altijd door.

De omstandigheden in de Verenigde Staten zijn rijp voor de triomf van de vrijheid, zowel nu als in de toekomst. Wat we nodig hebben, is een groeiende en levendige libertarische beweging die deze systeemcrisis duidt en ons door de overheid gecreëerde moeras de libertarische weg wijst. Zoals we aan het begin van dit werk hebben gezien, is dat precies wat er gaande is. En nu komen we eindelijk bij het beloofde antwoord op de vraag die we in het inleidende hoofdstuk stelden: Waarom nu? Amerika heeft een diepgewortelde erfenis van libertarische waarden, maar waarom komen ze dan pas de laatste vier of vijf jaar naar voren?

Ons antwoord is dat het ontstaan en de snelle groei van de libertarische beweging geen toeval zijn. Het is een gevolg van de crisissituatie die Amerika tussen 1973 en 1975 trof en sindsdien aanhoudt. Crisissituaties wekken altijd interesse en zetten mensen aan tot het zoeken naar oplossingen. Deze crisis heeft veel nadenkende Amerikanen geïnspireerd om te beseffen dat de overheid ons in deze puinhoop heeft gebracht. Alleen vrijheid -- het terugdringen van de overheid -- kan ons eruit helpen. We groeien omdat de omstandigheden gunstig zijn. In zekere zin heeft, net als op de vrije markt, de vraag zijn eigen aanbod gecreëerd.

En daarom kreeg de Libertarische Partij in 1976, bij haar eerste poging voor een nationaal ambt, 174.000 stemmen. Een recent nummer van The Baron Report, een gezaghebbende nieuwsbrief over politiek in Washington die bepaald niet libertarisch is, ontkende beweringen van de media over een huidige trend richting conservatisme onder kiezers. In plaats daarvan wijst het rapport erop dat 'als er al een trend in de opinie zichtbaar is, deze richting het libertarisme gaat -- de filosofie die tegen overheidsbemoeienis is en pleit voor persoonlijke rechten.' Het rapport voegt eraan toe dat libertarisme een aantrekkingskracht heeft aan beide uiteinden van het politieke spectrum: 'Conservatieven verwelkomen deze trend omdat het aangeeft dat het publiek sceptisch is over federale programma's; liberalen zien het als een groeiende acceptatie van individuele rechten op gebieden zoals drugs, seksueel gedrag, enzovoort, en als een toenemende terughoudendheid van het publiek om buitenlandse interventie te steunen.'

## Naar een vrij Amerika
De omstandigheden in de Verenigde Staten zijn zowel nu als in de toekomst ideaal voor de triomf van de vrijheid. Wat we nodig hebben, is een groeiende en levendige libertarische beweging die deze systeemcrisis toelicht en ons door het door de overheid gecreëerde moeras naar de libertarische weg leidt. Zoals we aan het begin van dit werk hebben gezien, is dat precies wat er gebeurt. Nu komen we eindelijk bij het beloofde antwoord op de vraag die we in het inleidende hoofdstuk stelden: Waarom nu? Amerika heeft een diepgewortelde erfenis van libertarische waarden, maar waarom komen deze pas de laatste vier of vijf jaar naar voren? Het antwoord is dat het ontstaan en de snelle groei van de libertarische beweging geen toeval zijn. Dit is een gevolg van de crisissituatie die Amerika tussen 1973 en 1975 trof en die nog steeds voortduurt. Crisissituaties wekken altijd belangstelling en zetten mensen aan tot het zoeken naar oplossingen. Deze crisis heeft veel nadenkende Amerikanen geïnspireerd om te beseffen dat de overheid ons in deze puinhoop heeft gebracht. Alleen vrijheid -- het terugdringen van de overheid -- kan ons eruit helpen. We groeien omdat de omstandigheden gunstig zijn. In zekere zin heeft, net als op de vrije markt, de vraag zijn eigen aanbod gecreëerd. Daarom kreeg de Libertarische Partij in 1976, bij haar eerste poging voor een nationaal ambt, 174.000 stemmen. Een recent nummer van The Baron Report, een invloedrijke nieuwsbrief over politiek in Washington die allesbehalve libertarisch is, ontkende de mediaberichten over een trend richting conservatisme onder de kiezers. Het rapport wijst er namelijk op dat, 'als er al een trend in de opinie zichtbaar is, deze richting het libertarisme gaat -- de filosofie die oproept tot minder overheidsinterventie en meer persoonlijke rechten.' Tevens voegt het rapport toe dat libertarisme aantrekkelijk is voor zowel conservatieven als liberalen: 'Conservatieven verwelkomen deze trend omdat het toont dat het publiek sceptisch staat tegenover federale programma's; liberalen zien het als een groeiende acceptatie van individuele rechten op gebieden zoals drugs en seksueel gedrag, en een toenemende terughoudendheid van het publiek om buitenlandse interventie te steunen.'

Het libertarische credo belichaamt eindelijk het beste van het Amerikaanse verleden, samen met de belofte van een veel betere toekomst. Libertariërs staan, meer dan conservatieven, die vaak vastklampen aan monarchale tradities uit een vervlogen Europees verleden, stevig in de grote klassiek-liberale traditie. Deze traditie heeft de Verenigde Staten gevormd en ons het erfgoed van individuele vrijheid, een vreedzaam buitenlands beleid, minimale overheidsinterventie en een vrije markteconomie gegeven. Libertariërs zijn de enige echte erfgenamen van Jefferson, Paine, Jackson en de abolitionisten.

En toch, terwijl we meer traditioneel en geworteld Amerikaans zijn dan de conservatieven, zijn we in sommige opzichten radicaler dan de radicalen. Niet omdat we de wens of hoop hebben om de menselijke natuur door politiek te herschikken, maar omdat alleen wij een echte, scherpe en oprechte breuk aanbieden met het oprukkende statisme van de twintigste eeuw. Oud Links vraagt enkel om meer van datgene waar we nu onder lijden, terwijl Nieuw Links uiteindelijk slechts nog ernstiger statisme of verplicht egalitarisme en uniformiteit voorstelt. Libertarisme is de logische uitkomst van het inmiddels vergeten 'Oud Rechts' uit de jaren '30 en '40, dat zich verzette tegen de New Deal, oorlog, centralisatie en staatsinterventie. Wij willen breken met alle aspecten van de liberale staat: met zijn welvaart en oorlogvoering, zijn monopolieprivileges en egalitarisme, alsook met de onderdrukking van slachtofferloze misdaden, of deze nu persoonlijk of economisch van aard zijn. Enkel wij bieden technologie zonder technocratie, groei zonder vervuiling, vrijheid zonder chaos, wet zonder tirannie en de verdediging van eigendomsrechten op zowel iemands persoon als zijn materiële bezittingen.

Overblijfselen van libertarische doctrines zijn overal om ons heen te vinden, zowel in delen van ons glorieuze verleden als in waarden en ideeën van het verwarrende heden. Maar alleen het libertarisme slaagt erin deze elementen te integreren tot een krachtig, logisch en consistent systeem. Het enorme succes van Karl Marx en het marxisme komt niet door de geldigheid van zijn ideeën -- die zijn immers allemaal misleidend -- maar doordat hij het aandurfde om de socialistische theorie in een krachtig systeem te verweven. Vrijheid kan niet slagen zonder een gelijkwaardige en contrasterende theoretische basis. Tot de laatste paar jaren hadden we, ondanks onze rijke erfenis van economisch en politiek denken, geen volledig geïntegreerde en consistente theorie van vrijheid. Die systematische theorie hebben we nu wel. We zijn volledig gewapend met kennis en klaar om onze boodschap te verspreiden en de verbeelding te prikkelen van alle groepen in de samenleving. Andere theorieën en systemen hebben duidelijk gefaald: het socialisme is overal op zijn retour, vooral in Oost-Europa. Het liberalisme heeft ons vastgezet in een scala aan onoplosbare problemen. Het conservatisme biedt niets meer dan een steriele verdediging van de status quo. Vrijheid is in de moderne wereld nog nooit volledig uitgetest. Libertariërs stellen nu voor om de Amerikaanse droom en de wereldwijde droom van vrijheid en welvaart voor iedereen waar te maken.
